### ISSUE TITLE
[material:1.1.0] Android resource linking failed after update to 1.1.0

### ISSUE THREAD

**Issue by meli-w** [material-components/material-components-android#1018]
**Description:** 
I'm using the material components via AppCompat Theme. Since the update from 1.0.0 to 1.1.0 I can't build anymore. I'm getting the following error:
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: resource style/Widget.AppCompat.TextView (aka my.company:style/Widget.AppCompat.TextView) not found.
     error: resource style/Widget.AppCompat.TextView (aka my.company:style/Widget.AppCompat.TextView) not found.
     error: resource style/Widget.AppCompat.TextView (aka my.company:style/Widget.AppCompat.TextView) not found.
     error: resource style/Widget.AppCompat.TextView (aka my.company:style/Widget.AppCompat.TextView) not found.
     error: resource style/Widget.AppCompat.TextView (aka my.company:style/Widget.AppCompat.TextView) not found.
     error: failed linking references.
```

**Expected behavior:** 
I want to build.

**Source code:** 
Project gradle: 
```
ext.deps = [
        material                   : "com.google.android.material:material:1.0.0", 
        ...
]
```
app gradle:
```
dependencies {
    implementation deps.material
   ...
}
```
themes xml:
```
<style name="Theme.MyApp" parent="Theme.AppCompat">

  <!-- Original AppCompat attributes. -->
  <item name="colorPrimary">@color/my_app_primary_color</item>
  <item name="colorSecondary">@color/my_app_secondary_color</item>
  <item name="android:colorBackground">@color/my_app_background_color</item>
  <item name="colorError">@color/my_app_error_color</item>

  <!-- New MaterialComponents attributes. -->
  <item name="colorPrimaryVariant">@color/my_app_primary_variant_color</item>
  <item name="colorSecondaryVariant">@color/my_app_secondary_variant_color</item>
  <item name="colorSurface">@color/my_app_surface_color</item>
  <item name="colorOnPrimary">@color/my_app_color_on_primary</item>
  <item name="colorOnSecondary">@color/my_app_color_on_secondary</item>
  <item name="colorOnBackground">@color/my_app_color_on_background</item>
  <item name="colorOnError">@color/my_app_color_on_error</item>
  <item name="colorOnSurface">@color/my_app_color_on_surface</item>
  <item name="scrimBackground">@color/mtrl_scrim_color</item>
  <item name="textAppearanceHeadline1">@style/TextAppearance.MaterialComponents.Headline1</item>
  <item name="textAppearanceHeadline2">@style/TextAppearance.MaterialComponents.Headline2</item>
  <item name="textAppearanceHeadline3">@style/TextAppearance.MaterialComponents.Headline3</item>
  <item name="textAppearanceHeadline4">@style/TextAppearance.MaterialComponents.Headline4</item>
  <item name="textAppearanceHeadline5">@style/TextAppearance.MaterialComponents.Headline5</item>
  <item name="textAppearanceHeadline6">@style/TextAppearance.MaterialComponents.Headline6</item>
  <item name="textAppearanceSubtitle1">@style/TextAppearance.MaterialComponents.Subtitle1</item>
  <item name="textAppearanceSubtitle2">@style/TextAppearance.MaterialComponents.Subtitle2</item>
  <item name="textAppearanceBody1">@style/TextAppearance.MaterialComponents.Body1</item>
  <item name="textAppearanceBody2">@style/TextAppearance.MaterialComponents.Body2</item>
  <item name="textAppearanceCaption">@style/TextAppearance.MaterialComponents.Caption</item>
  <item name="textAppearanceButton">@style/TextAppearance.MaterialComponents.Button</item>
  <item name="textAppearanceOverline">@style/TextAppearance.MaterialComponents.Overline</item>

...
</style>
```
**Android API version:**
28

**Gradle Version**
6.1.1

**Material Library version:** 
1.1.0

**Device:** 
n.a.

**Comment by hearsilent** [comment]
Upgrade `androidx.appcompat:appcompat` to `1.1.0` will resolve your problem.

**Comment by rohitrt89aricent** [comment]
After upgrading androidx.appcompat:appcompat to 1.1.0 App is crashing and the error i got :
` java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManagerImpl.isDestroyed()' on a null object reference
        at androidx.fragment.app.Fragment.performDetach(Fragment.java:2849)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1034)
        at androidx.fragment.app.FragmentManagerImpl$3$1.run(FragmentManagerImpl.java:1099)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`
