### ISSUE TITLE
[TextInputLayout] [Exposed Dropdown Menu] NPE on re-entrant showPopupMenu()

### ISSUE THREAD

**Issue by realdadfish** [material-components/material-components-android#1027]
Since MDC 1.2.0-alpha03 (more exactly, since 201ec6241cec4cc590dd806fd0896da5fa3140f0, as I bisected my way down) there is an issue with `AutoCompleteTextView`'s `showDropDown`:

```
java.lang.NullPointerException
	at android.widget.PopupWindow.getDecorViewLayoutParams(PopupWindow.java:2201)
	at android.widget.PopupWindow.update(PopupWindow.java:2257)
	at android.widget.PopupWindow.update(PopupWindow.java:2235)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:657)
	at android.widget.ListPopupWindow$GeneratedProxy/707354032.show(Unknown Source)
	at org.robolectric.shadows.ShadowListPopupWindow.show(ShadowListPopupWindow.java:22)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java)
	at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1217)
	at android.widget.AutoCompleteTextView.setFrame(AutoCompleteTextView.java:1163)
	at android.view.View.layout(View.java:20669)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at com.google.android.material.textfield.TextInputLayout.onLayout(TextInputLayout.java:3587)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.widget.ScrollView.onLayout(ScrollView.java:1552)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20672)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowLegacyMessageQueue.dispatchMessage(ShadowLegacyMessageQueue.java:157)
	at org.robolectric.shadows.ShadowLegacyMessageQueue.access$200(ShadowLegacyMessageQueue.java:42)
	at org.robolectric.shadows.ShadowLegacyMessageQueue$1.run(ShadowLegacyMessageQueue.java:135)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:407)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:279)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:261)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:244)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:234)
	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:89)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:124)
	at org.robolectric.shadows.ShadowLegacyLooper.unPause(ShadowLegacyLooper.java:267)
	at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:324)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:36)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at android.view.ViewGroup.addView(ViewGroup.java:4837)
	at android.widget.PopupWindow.createBackgroundView(PopupWindow.java:1388)
	at android.widget.PopupWindow.preparePopup(PopupWindow.java:1350)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1277)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:696)
	at android.widget.ListPopupWindow$GeneratedProxy/707354032.show(Unknown Source)
	at org.robolectric.shadows.ShadowListPopupWindow.show(ShadowListPopupWindow.java:22)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java)
	at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1217)
	at com.google.android.material.textfield.DropdownMenuEndIconDelegate.showHideDropdown(DropdownMenuEndIconDelegate.java:238)
	at com.google.android.material.textfield.DropdownMenuEndIconDelegate.access$400(DropdownMenuEndIconDelegate.java:65)
	at com.google.android.material.textfield.DropdownMenuEndIconDelegate$5.onTouch(DropdownMenuEndIconDelegate.java:351)
	at android.view.View.dispatchTouchEvent(View.java:12509)
```

`PopupWindow.createBackgroundView()` adds the `contentView` of the popup to a new instance of `PopupBackgroundView`. This `addView` call changes the layout and new measuring for the tree kicks in (in the above stacktrace the `addView` on the `ViewGroup` is executed through Robolectric shadowLooper in PAUSED mode). So far, so good.

Now this addition triggers the measurement of the surrounding `TextInputLayout`s newly introduced placeholder (https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/textfield/TextInputLayout.java#L2670) and this in turn triggers  `AutoCompleteTextView.setFrame` in between.

Here, in case the popup is showing (which technically it isn't, but the flag for it was already switched), the code tries to show the popup again. Because we're re-entrant, the previous invocation did not yet assigned the `mDecorView` from which it transcended, effectively throwing an NPE it comes across it.

I'm further investigating the issue to see if there is any workaround with the current 1.2.0 alphas.

**Comment by realdadfish** [comment]
And, I have to add, the crash only occurs when the Exposed Dropdown Menu is opened programmatically, through Robolectric. A normal `click()` action on the underlying `AppCompatAutoCompleteTextView` does not work, since the menu is opened only for ACTION_UP touch events, as seen here: https://github.com/material-components/material-components-android/blob/497cb97ef092243a73904d8842d93df85db7adc3/lib/java/com/google/android/material/textfield/DropdownMenuEndIconDelegate.java#L347 

So I'm obtaining and firing an touch event to trigger the menu which, until now, worked fine. My current workaround is now to open the popup by calling `showPopupMenu` on the `AutoCompleteTextView`, this seems to work. Sorry for the noise.
