### ISSUE TITLE
MaterialSharedAxisTransition calls OnCheckedChangeListener in ChipGroup when run

### ISSUE THREAD

**Issue by tunjid** [material-components/material-components-android#1050]
**Description:** When the `MaterialSharedAxisTransition` is run when performing a `FragmentTransaction`, it causes the `OnCheckedChangeListener` for a `ChipGroup` to fire causing unwanted side effects. 

**Expected behavior:** Running a MaterialSharedAxisTransition should not programmatically induce a OnCheckedChangeListener to fire for a `ChipGroup`. The root issue occurs in the `TransitionUtils.createViewBitmap` method in the framework's `Transition` class. Somehow the `Transition` removes a `Chip` from the `ChipGroup` when running and attempts to re-add it later.

```java
        if (addToOverlay) {
            sceneRoot.getOverlay().remove(view);
            parent.addView(view, indexInParent);
        }
```

**Source code:** 

https://github.com/tunjid/Android-Extensions/blob/develop/app/src/main/java/com/tunjid/androidx/fragments/MultipleStacksFragment.kt#L76

**Android API version:** Android API version here 
API 29

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)
1.2.0-alpha05

**Device:** Device on which the bug was encountered here
Google Pixel 3

**Stacktrace**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tunjid.andoidbootstrap.sample, PID: 13815
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1689)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1729)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
        at com.tunjid.androidx.navigation.MultiStackNavigator.showInternal(MultiStackNavigator.kt:320)
        at com.tunjid.androidx.navigation.MultiStackNavigator.show(MultiStackNavigator.kt:119)
        at com.tunjid.androidx.fragments.MultipleStacksFragment$onViewCreated$4.onCheckedChanged(MultipleStacksFragment.kt:77)
        at com.google.android.material.chip.ChipGroup.setCheckedId(ChipGroup.java:368)
        at com.google.android.material.chip.ChipGroup.setCheckedId(ChipGroup.java:361)
        at com.google.android.material.chip.ChipGroup.addView(ChipGroup.java:215)
        at android.view.ViewGroup.addView(ViewGroup.java:4919)
        at android.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:192)
        at android.transition.TransitionUtils.copyViewImage(TransitionUtils.java:103)
        at android.transition.Visibility.onDisappear(Visibility.java:420)
        at android.transition.Visibility.createAnimator(Visibility.java:255)
        at android.transition.Transition.createAnimators(Transition.java:733)
        at android.transition.TransitionSet.createAnimators(TransitionSet.java:444)
        at android.transition.TransitionSet.createAnimators(TransitionSet.java:444)
        at android.transition.Transition.playTransition(Transition.java:1777)
        at android.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:327)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2769)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    
    
    --------- beginning of system
```
To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
I think it's fixed in the recent library versions.
