### ISSUE TITLE
[MaterialCardView] Inflation crash when used with android:onClick in 1.1.0

### ISSUE THREAD

**Issue by Ethan1983** [material-components/material-components-android#1054]
**Description:** Null pointer exception when inflating MaterialCardView with android:onClick set in xml

**Expected behavior:** MaterialCardView should inflate as expected

**Source code:**

<com.google.android.material.card.MaterialCardView
                android:id="@+id/card_view"
                android:layout_gravity="center"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:onClick="onClickHandler"
                tools:ignore="OnClick">

**Android API version:** 29

**Material Library version:** 1.1.0

**Device:** Pixel 2 XL

Note, this works in 1.0.0 but crashes in 1.1.0 with this trace as cardViewHelper is null.

 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.card.a.p()' on a null object reference
        at com.google.android.material.card.MaterialCardView.setClickable(:293)
        at android.view.View.setOnClickListener(View.java:7065)
        at android.view.View.<init>(View.java:5666)
        at android.view.ViewGroup.<init>(ViewGroup.java:675)
        at android.widget.FrameLayout.<init>(FrameLayout.java:99)
        at android.widget.FrameLayout.<init>(FrameLayout.java:94)
        at a.d.f.a.<init>(:121)
        at com.google.android.material.card.MaterialCardView.<init>(:118)
        at com.google.android.material.card.MaterialCardView.<init>(:114)
        	... 33 more

**Comment by ymarian** [comment]
I set this as a p3 as this isn't a recommended pattern. 
Using setOnClickListener should work fine. We accept pull requests if you want to tackle this issue.
