### ISSUE TITLE
[AppBarLayout] Not detecting Material Theme enforcement in Android 7.0

### ISSUE THREAD

**Issue by jordyamc** [material-components/material-components-android#1130]
**Description:** AppBarLayout crashing on init with `IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant)`, only on Android 7,  when the AppBarLayout have a MaterialComponents theme, and the only child is a TabLayout.

A workaround is to remove the theme attr.

Following the Exception it seems that only on Android 7 the code is not detecting the enforce_material_theme attr.

![imagen](https://user-images.githubusercontent.com/6831873/77238850-b17aba00-6b99-11ea-99e0-a95f3d86e4c1.png)

**Expected behavior:** No problems expected, other parts of my app uses AppBarLayout with Toolbar, and other with Toolbar and TabsLayout without problem using the same MaterialComponets theme.

**Source code:** 

```
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
        at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:213)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:148)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
        at com.google.android.material.appbar.ViewUtilsLollipop.setStateListAnimatorFromAttrs(ViewUtilsLollipop.java:46)
        at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:215)
        at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:199)
```

```
<com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.MaterialComponents.Dark">

        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/transparent"
            app:tabMode="auto">
        </com.google.android.material.tabs.TabLayout>
    </com.google.android.material.appbar.AppBarLayout>
```

**Android API version:** Android 7.0 (SDK 24)

**Material Library version:** 1.2.0-alpha05

**Device:** Any device with Android 7.0

**Comment by wcshi** [comment]
The error tells you that you need to use an AppCompat theme, you are applying a theme overlay.

re: "other parts of my app uses AppBarLayout with Toolbar, and other with Toolbar and TabsLayout without problem using the same MaterialComponets theme."

Please share a sample app that can reproduce your bug.

**Comment by jordyamc** [comment]
Theme overlay its a valid AppCompat Theme
### No Crash
```xml
<com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.MaterialComponents.Dark">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:popupTheme="@style/ThemeOverlay.MaterialComponents.Dark" />
    </com.google.android.material.appbar.AppBarLayout>
```
### No Crash
```xml
<com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.MaterialComponents.Dark">

<androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:popupTheme="@style/ThemeOverlay.MaterialComponents.Dark" />

        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/transparent"
            app:tabMode="auto">
        </com.google.android.material.tabs.TabLayout>
    </com.google.android.material.appbar.AppBarLayout>
```
### **CRASH**
```xml
<com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.MaterialComponents.Dark">

        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/transparent"
            app:tabMode="auto">
        </com.google.android.material.tabs.TabLayout>
    </com.google.android.material.appbar.AppBarLayout>
```
