### ISSUE TITLE
MaterialComponentsViewInflater ClassNotFoundException

### ISSUE THREAD

**Issue by iKirby** [material-components/material-components-android#115]
### Overview

When using `Theme.MaterialComponents` theme, the following error can be found in logcat. It won't crash the app though.

```
2018-05-21 19:57:17.821 4193-4193/com.example.demo I/AppCompatDelegate: Failed to instantiate custom view inflater com.google.android.material.theme.MaterialComponentsViewInflater . Falling back to default.
    java.lang.ClassNotFoundException: Invalid name: com.google.android.material.theme.MaterialComponentsViewInflater 
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1226)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1297)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1885)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2599)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2672)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2071)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:566)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:509)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:457)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.example.demo.MainActivity.onCreate(MainActivity.java:13)
        at android.app.Activity.performCreate(Activity.java:7130)
        at android.app.Activity.performCreate(Activity.java:7121)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1262)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4792)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4711)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:110)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4753)
        at android.app.Activity.recreate(Activity.java:5580)
        at com.example.demo.MainActivity.onClick(MainActivity.java:30)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25881)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6649)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```

### Reproduction steps

Use `Theme.MaterialComponents` for an activity and start the activity.
The light theme doesn't have the error.

This can also be reproduced using `Theme.MaterialComponents.Dialog` and `Theme.MaterialComponents.Dialog.Light` theme.

### Version number

1.0.0-alpha1

### Operating system and device

Android P PPP2.180412.012

**Comment by dsn5ft** [comment]
I'm thinking this may be a proguard issue. Can you try adding com.google.android.material.theme. MaterialComponentsViewInflater to your proguard file to see if it has an effect?

**Comment by iKirby** [comment]
@dsn5ft This also happens on my debug build so I think it's not related to proguard.

**Comment by dsn5ft** [comment]
Gotcha, will see if I can reproduce.

**Comment by NickM-27** [comment]
I am also having this error, on debug, and I made sure to add it to proguard as well

**Comment by dsn5ft** [comment]
Unfortunately I'm unable to reproduce this. Here is my setup:

**build.gradle**
```
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**app/build.gradle**
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 'android-P'
    defaultConfig {
        applicationId "com.example.scratchpad"
        minSdkVersion 14
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    api 'androidx.appcompat:appcompat:1.0.0-alpha1'
    api 'com.google.android.material:material:1.0.0-alpha1'

    testImplementation 'junit:junit:4.12'

    androidTestImplementation 'androidx.test:runner:1.1.0-alpha1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha1'
}
```

**theme**
```
<style name="AppTheme" parent="Theme.MaterialComponents">
  <item name="colorPrimary">@color/colorPrimary</item>
  <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
  <item name="colorAccent">@color/colorAccent</item>
</style>
```

**layout**
```
<Button
    android:id="@+id/button"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="Button"/>
```

And finally when I log the class of the "<Button />" I get `com.google.android.material.button.MaterialButton`, which means that the `MaterialComponentsViewInflater` is working. Also, I don't see the exception you mentioned in the logs.

```
06-04 11:02:05.544 22857-22857/com.example.scratchpad D/Class: BUTTON CLASS: com.google.android.material.button.MaterialButton
```

Can you check for any differences in our setups and try pulling in pieces from above to see if the issue gets resolved?

**Comment by NickM-27** [comment]
@dsn5ft The first thing that immediately pops out to me is that I am using targetSdkVersion 28. Also you have api 'com.google...material' meanwhile I have implementation 'com.google...material' which might be another difference?

Finally, my layout is a bit more complicated than a button (FAB, Recyclerview, etc.) so perhaps it is a specific element which is not correctly themed which causes the issue. Let me know what information you need and I will be happy to help.

**Comment by dsn5ft** [comment]
I just tried targetSdkVersion 28 and implementation instead of api, and the view inflater still works. My sample layout also has many more widgets in it.

Can you try creating a new simple project, verify that the view inflater works, and then add pieces from your app to it until you can reproduce the issue?

**Comment by iKirby** [comment]
@dsn5ft Your setup works well. And I think I've found the cause. I was using Android Gradle plugin 3.2.0-alpha15. After going back to 3.1.2, the error is gone. I also tried 3.2.0-alpha16, it causes the same error.

**Comment by dsn5ft** [comment]
Interesting, I will reach out to the team that manages the Android Gradle plugin to see if there was a regression.

**Comment by NickM-27** [comment]
This appears to have been fixed in the latest alphas as my dark theme now works flawlessly

**Comment by iKirby** [comment]
Tried the latest version, and I can also confirm that it has been fixed.
Thanks!
