### ISSUE TITLE
Build Failed 

### ISSUE THREAD

**Issue by WYPhyoe** [material-components/material-components-android#123]
com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
Output:  /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1326: error: resource android:attr/fontVariationSettings not found.
/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1326: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: /Users/elissa/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-alpha14-4748712-osx.jar/1dd06ca9a0b666d1cc6defad96ecdca3/aapt2-3.2.0-alpha14-4748712-osx/aapt2 link -I\
        /Users/elissa/Library/Android/sdk/platforms/android-27/android.jar\
        --manifest\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --custom-package\
        wyp.mcd\
        -0\
        apk\
        --output-text-symbols\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-alpha14-4748712-osx Daemon #0
Output:  /Users/elissa/.gradle/caches/transforms-1/files-1.1/appcompat-1.0.0-alpha1.aar/acf923962ce8ef806a63dd49b561a43f/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
    
/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
    
/Users/elissa/.gradle/caches/transforms-1/files-1.1/constraint-layout-1.1.0.aar/a0d503af98c765e9dde86fbdff745eb2/res/values/values.xml:130:5-108: AAPT: error: resource android:attr/fontVariationSettings not found.
    
/Users/elissa/.gradle/caches/transforms-1/files-1.1/constraint-layout-1.1.0.aar/a0d503af98c765e9dde86fbdff745eb2/res/values/values.xml:130:5-108: AAPT: error: resource android:attr/ttcIndex not found.
    
error: failed linking references.
Command: /Users/elissa/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-alpha14-4748712-osx.jar/1dd06ca9a0b666d1cc6defad96ecdca3/aapt2-3.2.0-alpha14-4748712-osx/aapt2 link -I\
        /Users/elissa/Library/Android/sdk/platforms/android-27/android.jar\
        --manifest\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --custom-package\
        wyp.mcd\
        -0\
        apk\
        --output-text-symbols\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-alpha14-4748712-osx Daemon #0
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:97)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteLinkException(Aapt2ErrorUtils.kt:73)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:528)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.doFullTaskAction(LinkApplicationAndroidResourcesTask.java:276)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
	at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
Output:  /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1326: error: resource android:attr/fontVariationSettings not found.
/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1326: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: /Users/elissa/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-alpha14-4748712-osx.jar/1dd06ca9a0b666d1cc6defad96ecdca3/aapt2-3.2.0-alpha14-4748712-osx/aapt2 link -I\
        /Users/elissa/Library/Android/sdk/platforms/android-27/android.jar\
        --manifest\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --custom-package\
        wyp.mcd\
        -0\
        apk\
        --output-text-symbols\
        /Users/elissa/Downloads/WaiYanPhyoe/Bitbucket/android-projects/mm_computer_dictionary_android/app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-alpha14-4748712-osx Daemon #0
	at com.android.builder.internal.aapt.v2.Aapt2DaemonImpl.doLink(Aapt2DaemonImpl.kt:177)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.link(Aapt2Daemon.kt:103)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonManager$LeasedAaptDaemon.link(Aapt2DaemonManager.kt:176)
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:811)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:526)
	... 49 more

**Comment by EboMike** [comment]
I've seen this kind of error when you're not using "compileSdkVersion 'android-P'".

**Comment by dbacinski** [comment]
Same here, 
latest design lib (com.android.support:design:28.0.0-alpha1) only complies when preview P sdk is set (compileSdkVersion 'android-P'), 
which is kind of annoying because we cannot use it in a production build

**Comment by dsn5ft** [comment]
This is a common requirement for each major update of the Support Libraries. You will be able to start publishing to the Play Store soon with the next Preview version of Android P. This page has some useful information about that and the timeline for Android P - https://developer.android.com/preview/overview.

**Comment by Dwite** [comment]
@dsn5ft by "next" you mean DP3?
