### ISSUE TITLE
[BottomAppBar] setting elevation crashes in version 1.1.0 stable material libraray android

### ISSUE THREAD

**Issue by githubashutoshsoni** [material-components/material-components-android#1245]
```
    --------- beginning of crash
2020-04-25 12:05:30.436 27240-27240/com.example.spabooking E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.spabooking, PID: 27240
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.spabooking/com.example.spabooking.LandingActivity}: android.view.InflateException: Binary XML file line #33 in com.example.spabooking:layout/activity_landing: Binary XML file line #33 in com.example.spabooking:layout/activity_landing: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.view.InflateException: Binary XML file line #33 in com.example.spabooking:layout/activity_landing: Binary XML file line #33 in com.example.spabooking:layout/activity_landing: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
     Caused by: android.view.InflateException: Binary XML file line #33 in com.example.spabooking:layout/activity_landing: Error inflating class com.google.android.material.bottomappbar.BottomAppBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.example.spabooking.LandingActivity.onCreate(LandingActivity.java:337)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-04-25 12:05:30.436 27240-27240/com.example.spabooking E/AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.shape.MaterialShapeDrawable.setElevation(float)' on a null object reference
        at com.google.android.material.bottomappbar.BottomAppBar.setElevation(BottomAppBar.java:410)
        at android.view.View.<init>(View.java:5900)
        at android.view.ViewGroup.<init>(ViewGroup.java:686)
        at android.view.ViewGroup.<init>(ViewGroup.java:682)
        at androidx.appcompat.widget.Toolbar.<init>(Toolbar.java:236)
        at com.google.android.material.bottomappbar.BottomAppBar.<init>(BottomAppBar.java:219)
        at com.google.android.material.bottomappbar.BottomAppBar.<init>(BottomAppBar.java:215)
        	... 28 more
```

**Description:** setting an android:elevation causes nullpointer exception in material version 1.1.0 stable.in bottomAPPbar. 

**Expected behavior:** it should not crash obviously

**Source code:** <?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/landing_container"
    android:layout_width="match_parent"
    app:elevation="@dimen/dimens_16dp"
    android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBarLayout"
        app:elevation="@dimen/dimens_16dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"

        android:fitsSystemWindows="true">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:layout_width="match_parent"
            app:elevation="@dimen/dimens_16dp"
            android:layout_height="wrap_content">

            <include layout="@layout/layout_toolbar_landing">

            </include>

        </com.google.android.material.appbar.CollapsingToolbarLayout>
    </com.google.android.material.appbar.AppBarLayout>

    <com.google.android.material.bottomappbar.BottomAppBar
        android:id="@+id/bar"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:layout_gravity="bottom"
        android:background="@color/colorBehindCard"
        android:elevation="24dp"
        android:foregroundGravity="center"
        android:gravity="center"

        app:contentInsetStart="0dp"
        app:fabAlignmentMode="center"
        app:fabCradleMargin="10dp"
        app:fabCradleRoundedCornerRadius="16dp"
        app:fabCradleVerticalOffset="8dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:background="@color/colorPrimary"
            android:elevation="55dp"
            android:gravity="center">

            <ImageView
                android:id="@+id/iv_home_icon"
                android:layout_width="0dp"
                android:layout_height="@dimen/bottom_navigation_icon_height"
                android:layout_gravity="center"
                android:layout_weight="1"

                android:background="?attr/selectableItemBackgroundBorderless"
                android:src="@drawable/img_home" />

            <ImageView
                android:id="@+id/ic_icon_my_order"
                android:layout_width="0dp"

                android:layout_height="@dimen/bottom_navigation_icon_height"
                android:layout_gravity="center"
                android:layout_marginEnd="50dp"
                android:layout_weight="1"
                android:background="?attr/selectableItemBackgroundBorderless"

                android:src="@drawable/img_my_orders">

            </ImageView>

            <ImageView
                android:id="@+id/iv_icon_membership"
                android:layout_width="0dp"
                android:layout_height="@dimen/bottom_navigation_icon_height"
                android:layout_gravity="center"
                android:layout_marginStart="50dp"
                android:layout_weight="1"
                android:background="?attr/selectableItemBackgroundBorderless"
                android:clickable="true"
                android:focusable="auto"
                android:src="@drawable/img_membership">

            </ImageView>

            <ImageView
                android:id="@+id/bottom_my_membership"
                android:layout_width="0dp"
                android:layout_height="@dimen/bottom_navigation_icon_height"
                android:layout_gravity="center"
                android:layout_weight="1"
                android:background="?attr/selectableItemBackgroundBorderless"
                android:src="@drawable/img_my_membership">

            </ImageView>

        </LinearLayout>

    </com.google.android.material.bottomappbar.BottomAppBar>

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/landing_offer"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:backgroundTint="#212121"
        android:clickable="true"
        android:focusable="true"
        app:elevation="@dimen/dimens_200dp"
        android:src="@drawable/ic_icon_menu_offer"
        app:layout_anchor="@id/bar"
        app:maxImageSize="50dp" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>

**Android API version:** 28

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0 stable)

**Device:** OnePlus 6 , emulator pixel xl 

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by wcshi** [comment]
Please try using app:elevation instead of android:elevation and app:backgroundTint instead of android:background

https://github.com/material-components/material-components-android/blob/70cc027b15945f8bd917403b23bb3b2dd22172b4/lib/java/com/google/android/material/bottomappbar/res/values/attrs.xml#L20-L22
