### ISSUE TITLE
[Slider] IllegalStateException: Not enough labels to display all the values

### ISSUE THREAD

**Issue by JustinFincher** [material-components/material-components-android#1284]
**Description:** Hi, I am using an alpha version of Material Components to use the slider class so I certainly understand this is not production-ready yet. However, I got some logs from the crash report that the slider occasionally throws **IllegalStateException of 'Not enough labels to display all the values'** on some users' devices (as in `ensureLabels()` line 1734)
https://github.com/material-components/material-components-android/blob/59c156013f7f2401d8331e6b53df13486cba8157/lib/java/com/google/android/material/slider/Slider.java#L1734
As this is more of an internal method, I don't know if this is a bug or a result of misconfiguration, please let me know if I am using the Slider class wrong, thanks. 
Crash stack trace:
```
java.lang.IllegalStateException: Not enough labels to display all the values
    at com.google.android.material.slider.Slider.ensureLabels(Slider.java:9)
    at com.google.android.material.slider.Slider.onDraw(Slider.java:15)
    at android.view.View.draw(View.java:23190)
    at android.view.View.updateDisplayListIfDirty(View.java:22065)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5214)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5186)
    at android.view.View.updateDisplayListIfDirty(View.java:22020)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:4263)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4047)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3320)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
    at android.view.Choreographer.doCallbacks(Choreographer.java:797)
    at android.view.Choreographer.doFrame(Choreographer.java:732)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8016)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Expected behavior:** Slider works normally across on all devices

**Source code:** 
Layout:
```xml
<com.google.android.material.slider.Slider
android:id="@+id/fluid_speed_slider"
android:valueTo="1"
android:valueFrom="0"
app:valueEnd="@={viewModel.noiseSpeedMax}"
app:valueStart="@={viewModel.noiseSpeedMin}"
style="@style/Widget.MaterialComponents.Slider"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:animateLayoutChanges="true"
android:fontFamily="@font/product_sans_bold"
android:textAppearance="@style/TextAppearance.MaterialComponents.Overline"
app:labelBehavior="floating" />
```
My data binding class (to use with my customized `app:valueStart` and `app:valueEnd` attribute to represent a range of values):
```java
package com.justzht.lwp.music.apple.helper.binding;

import androidx.annotation.NonNull;
import androidx.databinding.BindingAdapter;
import androidx.databinding.InverseBindingAdapter;
import androidx.databinding.InverseBindingListener;

import com.google.android.material.slider.Slider;

public class SliderBindingAdapter {

    @BindingAdapter("android:enabled")
    public static void setEnabled(Slider view, boolean enabled)
    {
        if (view.isEnabled() != enabled)
        {
            view.setEnabled(enabled);
        }
    }

    @InverseBindingAdapter(attribute = "android:value")
    public static float getValue(Slider view) {
        return view.getValue();
    }

    @BindingAdapter("android:value")
    public static void setValue(Slider view, float progress) {
        if (progress != view.getValue()) {
            view.setValue(progress);
        }
    }

    @BindingAdapter(value = {"valueStart","valueEnd"})
    public static void setValue(Slider view, float start, float end) {

        float startCurrent, endCurrent;
        if (view.getValues().size() != 2) { startCurrent = view.getValueFrom(); endCurrent = view.getValueTo(); }
        else { startCurrent = view.getValues().get(0); endCurrent = view.getValues().get(1); }

        if (start < view.getValueFrom()) { start = view.getValueFrom(); }
        if (end < view.getValueFrom()) { end = view.getValueFrom(); }
        if (start > view.getValueTo()) { start = view.getValueTo(); }
        if (end > view.getValueTo()) { end = view.getValueTo(); }
        if (start > end) { start = end; }
        if (start != startCurrent || end != endCurrent)
        {
            view.setValues(start, end);
        }
    }

    @InverseBindingAdapter(attribute = "valueStart")
    public static float getValueStart(Slider view) {
        if (view.getValues().size() > 0)
        {
            return view.getValues().get(0);
        }else {
            return view.getValueFrom();
        }
    }

    @InverseBindingAdapter(attribute = "valueEnd")
    public static float getValueEnd(Slider view) {
        if (view.getValues().size() > 1)
        {
            return view.getValues().get(1);
        }else {
            return view.getValueTo();
        }
    }

    public interface OnStartTrackingTouch {
        void onStartTrackingTouch(Slider slider);
    }

    public interface OnStopTrackingTouch {
        void onStopTrackingTouch(Slider slider);
    }

    public interface OnValueChange {
        void onValueChange(Slider slider, float value, boolean fromUser);
    }

    public interface OnValueUserChange {
        void onValueChange(float value);
    }

    @BindingAdapter(value = {"valueStartAttrChanged", "valueEndAttrChanged"}, requireAll = false)
    public static void setValueListener(Slider view, final InverseBindingListener start, final InverseBindingListener end)
    {
        view.clearOnChangeListeners();
        if (start != null || end != null)
        {
            view.addOnChangeListener((slider, value, fromUser) -> {
                if (start != null) { start.onChange(); }
                if (end != null) { end.onChange(); }
            });
        }
    }

    @BindingAdapter(value = {"android:onValueChange", "android:onValueUserChange"}, requireAll = false)
    public static void setValueListener(Slider view, final OnValueChange change, final OnValueUserChange userChange)
    {
        view.clearOnChangeListeners();
        if (change != null || userChange != null)
        {
            view.addOnChangeListener((slider, value, fromUser) -> {
                if (change != null) { change.onValueChange(slider,value,fromUser); }
                if (userChange != null && fromUser) { userChange.onValueChange(value); }
            });
        }
    }

    @BindingAdapter(value = {"android:onStartTrackingTouch", "android:onStopTrackingTouch"}, requireAll = false)
    public static void setListener(Slider view, final OnStartTrackingTouch start, final OnStopTrackingTouch stop)
    {
        view.clearOnSliderTouchListeners();
        if (start != null || stop != null)
        {
            view.addOnSliderTouchListener(new Slider.OnSliderTouchListener() {
                @Override
                public void onStartTrackingTouch(@NonNull Slider slider) {
                    if (start != null) {
                        start.onStartTrackingTouch(slider);
                    }
                }

                @Override
                public void onStopTrackingTouch(@NonNull Slider slider) {
                    if (stop != null) {
                        stop.onStopTrackingTouch(slider);
                    }
                }
            });
        }
    }
}

```

**Android API version:** Android 10

**Material Library version:** `com.google.android.material:material:1.2.0-alpha06`

**Device:** `Motorola One Vision` / `Samsung Galaxy S10`

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by wcshi** [comment]
could you please share a small demo app that reproduces your bug? thank you!

**Comment by JustinFincher** [comment]
Sure, will get back to you once I made a demo :-D. However, this issue only happens occasionally, so it might several tries before the exception is actually raised.

**Comment by pekingme** [comment]
Hi @JustinFincher, there's a change on the message of this exception in 1.3.0-alpha. If you upgrade your app to this version or later by any chance, let's see if the message of new crashes can give us some more clues about what the potential causes are.
