### ISSUE TITLE
[TextInputLayout] NoSuchFieldError: mtrl_textinput_box_bottom_offset

### ISSUE THREAD

**Issue by realdadfish** [material-components/material-components-android#1455]
Material Library version: 1.2.0-beta01
Robolectric version: 4.3.1

When running UI tests with Espresso and Robolectric, they crash in some test configurations consistently on Linux and macOS, regardless whether they're executed in Android Studio or via Gradle command line, because of an unknown field, like so

```
android.view.InflateException: Binary XML file line #48: Binary XML file line #48: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #48: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at androidx.databinding.DataBindingUtil.$$robo$$androidx_databinding_DataBindingUtil$inflate(DataBindingUtil.java:126)
	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java)
	at androidx.databinding.ViewDataBinding.$$robo$$androidx_databinding_ViewDataBinding$inflateInternal(ViewDataBinding.java:1368)
	at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java)
	at OurFragmentBinding.inflate(OurFragmentBinding.java:173)
	at OurFragmentBinding.inflate(OurFragmentBinding.java:159)
	at OurFragment.onCreateView(OurFragment.kt:84)
	at androidx.fragment.app.Fragment.$$robo$$androidx_fragment_app_Fragment$performCreateView(Fragment.java:2698)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java)
	at androidx.fragment.app.FragmentStateManager.$$robo$$androidx_fragment_app_FragmentStateManager$createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
	at androidx.fragment.app.BackStackRecord.$$robo$$androidx_fragment_app_BackStackRecord$executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$execSingleAction(FragmentManager.java:1818)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java)
	at androidx.fragment.app.BackStackRecord.$$robo$$androidx_fragment_app_BackStackRecord$commitNow(BackStackRecord.java:297)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java)
	at androidx.fragment.app.testing.FragmentScenario$1.$$robo$$androidx_fragment_app_testing_FragmentScenario_1$perform(FragmentScenario.java:312)
	at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java:291)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:551)
	at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:561)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$internalLaunch(FragmentScenario.java:290)
	at androidx.fragment.app.testing.FragmentScenario.internalLaunch(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$launchInContainer(FragmentScenario.java:272)
	at androidx.fragment.app.testing.FragmentScenario.launchInContainer(FragmentScenario.java)
	at OurFragmentScenarioRule.launchFragment(OurFragmentScenarioRule.kt:95)
	at OurFragmentScenarioRule.launchFragment$default(OurFragmentScenarioRule.kt:94)
	at OurFragmentStepDefinitions$1.accept(OurFragmentStepDefinitions.kt:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java8.Java8StepDefinition.execute(Java8StepDefinition.java:113)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:46)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:142)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:65)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:172)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:62)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:49)
	at OurFeatureTestRunner.testFeature(OurFeatureTestRunner.kt:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at androidx.databinding.DataBindingUtil.$$robo$$androidx_databinding_DataBindingUtil$inflate(DataBindingUtil.java:126)
	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java)
	at androidx.databinding.ViewDataBinding.$$robo$$androidx_databinding_ViewDataBinding$inflateInternal(ViewDataBinding.java:1368)
	at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java)
	at OurViewDropdownBinding.inflate(OurViewDropdownBinding.java:60)
	at OurViewDropdownBinding.inflate(OurViewDropdownBinding.java:46)
	at OurDropdownView.<init>(OurDropdownView.kt:84)
	at OurDropdownView.<init>(OurDropdownView.kt:33)
	at OurDropdownView.<init>(OurDropdownView.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at androidx.databinding.DataBindingUtil.$$robo$$androidx_databinding_DataBindingUtil$inflate(DataBindingUtil.java:126)
	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java)
	at androidx.databinding.ViewDataBinding.$$robo$$androidx_databinding_ViewDataBinding$inflateInternal(ViewDataBinding.java:1368)
	at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java)
	at OurFragmentBinding.inflate(OurFragmentBinding.java:173)
	at OurFragmentBinding.inflate(OurFragmentBinding.java:159)
	at OurFragment.onCreateView(OurFragment.kt:84)
	at androidx.fragment.app.Fragment.$$robo$$androidx_fragment_app_Fragment$performCreateView(Fragment.java:2698)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java)
	at androidx.fragment.app.FragmentStateManager.$$robo$$androidx_fragment_app_FragmentStateManager$createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
	at androidx.fragment.app.BackStackRecord.$$robo$$androidx_fragment_app_BackStackRecord$executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.$$robo$$androidx_fragment_app_FragmentManager$execSingleAction(FragmentManager.java:1818)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java)
	at androidx.fragment.app.BackStackRecord.$$robo$$androidx_fragment_app_BackStackRecord$commitNow(BackStackRecord.java:297)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java)
	at androidx.fragment.app.testing.FragmentScenario$1.$$robo$$androidx_fragment_app_testing_FragmentScenario_1$perform(FragmentScenario.java:312)
	at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java:291)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:551)
	at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:561)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$internalLaunch(FragmentScenario.java:290)
	at androidx.fragment.app.testing.FragmentScenario.internalLaunch(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$launchInContainer(FragmentScenario.java:272)
	at androidx.fragment.app.testing.FragmentScenario.launchInContainer(FragmentScenario.java)
	at OurFragmentScenarioRule.launchFragment(OurFragmentScenarioRule.kt:95)
	at OurFragmentScenarioRule.launchFragment$default(OurFragmentScenarioRule.kt:94)
	at OurFragmentStepDefinitions$1.accept(OurFragmentStepDefinitions.kt:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java8.Java8StepDefinition.execute(Java8StepDefinition.java:113)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:46)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:142)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:65)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:172)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:62)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:49)
	at OurFeatureTestRunner.testFeature(OurFeatureTestRunner.kt:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchFieldError: mtrl_textinput_box_bottom_offset
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:278)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:247)
	... 150 more
```

I am unable to find the said field in the current sources, so I don't know where it comes from actually. From what I figured is that it seems to be some kind of `dimen` resource value that apparently is not part of the compiled `R.java`, though I see it in my module's build output when I grep for it:

```
build/intermediates/res/merged/debug/values/values.xml:    <dimen name="mtrl_textinput_box_bottom_offset">3dp</dimen>
```

**Comment by realdadfish** [comment]
It seems to be a local problem of unknown origin. Sorry for the noise.
