### ISSUE TITLE
[Slider] invalidateChildInParentFast (NoSuchMethodException)

### ISSUE THREAD

**Issue by mwrod** [material-components/material-components-android#1486]
**Description:** 
I am testing the Slider on an old API version 15. After finishing dragging the slider I am getting a `RuntimeException`. This is happening, because `OverlayViewGroup` tries to find the method `invalidateChildInParentFast` of `ViewGroup` through Reflection. I also tried to disable the label, but this is not fixing the issue. On newer API versions there is no problem at all. Why is it, that in my case the method can not be found? Is there some kind of issue or I am doing something wrong?

<details>
<summary>Stacktrace:</summary>

07-16 23:04:56.533 19323-19323/com.wrodarczyk.showtracker2 E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
        at com.google.android.material.internal.ViewOverlayApi14.<init>(ViewOverlayApi14.java:46)
        at com.google.android.material.internal.ViewGroupOverlayApi14.<init>(ViewGroupOverlayApi14.java:27)
        at com.google.android.material.internal.ViewOverlayApi14.createFrom(ViewOverlayApi14.java:59)
        at com.google.android.material.internal.ViewUtils.getOverlay(ViewUtils.java:281)
        at com.google.android.material.internal.ViewUtils.getContentViewOverlay(ViewUtils.java:313)
        at com.google.android.material.slider.BaseSlider.onTouchEvent(BaseSlider.java:1539)
        at com.google.android.material.slider.Slider.onTouchEvent(Slider.java:40)
        at android.view.View.dispatchTouchEvent(View.java:5541)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1912)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1371)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:738)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1860)
        at android.view.View.dispatchPointerEvent(View.java:5721)
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2890)
        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2466)
        at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:845)
        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2475)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4424)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: invalidateChildInParentFast [int, int, class android.graphics.Rect]
        at com.google.android.material.internal.ViewOverlayApi14$OverlayViewGroup.<clinit>(ViewOverlayApi14.java:102)
        at com.google.android.material.internal.ViewOverlayApi14.<init>(ViewOverlayApi14.java:46) 
        at com.google.android.material.internal.ViewGroupOverlayApi14.<init>(ViewGroupOverlayApi14.java:27) 
        at com.google.android.material.internal.ViewOverlayApi14.createFrom(ViewOverlayApi14.java:59) 
        at com.google.android.material.internal.ViewUtils.getOverlay(ViewUtils.java:281) 
        at com.google.android.material.internal.ViewUtils.getContentViewOverlay(ViewUtils.java:313) 
        at com.google.android.material.slider.BaseSlider.onTouchEvent(BaseSlider.java:1539) 
        at com.google.android.material.slider.Slider.onTouchEvent(Slider.java:40) 
        at android.view.View.dispatchTouchEvent(View.java:5541) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957) 
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726) 
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1912) 
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1371) 
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:738) 
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69) 
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1860) 
        at android.view.View.dispatchPointerEvent(View.java:5721) 
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2890) 
        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2466) 
        at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:845) 
        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2475) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4424) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.NoSuchMethodException: invalidateChildInParentFast [int, int, class android.graphics.Rect]
        at java.lang.Class.getConstructorOrMethod(Class.java:460)
        at java.lang.Class.getDeclaredMethod(Class.java:685)
    	at com.google.android.material.internal.ViewOverlayApi14$OverlayViewGroup.<clinit>(ViewOverlayApi14.java:9

</details> 

**Source code:**
This should happen with any Slider on the mentioned API version.

**Android API version:** 15

**Material Library version:** 1.3.0-alpha01

**Device:** Galaxy NexusAndroid 4.0.3. x86 AVD

**Comment by matpag** [comment]
In Transition library there is the same check for the API availability [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:transition/transition/src/main/java/androidx/transition/ViewOverlayApi14.java;l=118;bpv=1;bpt=0).
But here they do not `throw RuntimeException(e)` like we have here:
https://github.com/material-components/material-components-android/blob/889fca55a2c48d3f8d3a00b42fbe07923fc763de/lib/java/com/google/android/material/internal/ViewOverlayApi14.java#L102

Should the throw clause be removed?
