### ISSUE TITLE
[Slider] internal IllegalStateException

### ISSUE THREAD

**Issue by palicka** [material-components/material-components-android#1496]
device: Huawei HUAWEI Y6 Pro 2019 (HWMRD-M1), 2816MB RAM, Android 9
material lib version: "1.3.0-alpha01"
Stacktrace from Play console (I can't reproduce it):

```
java.lang.IllegalStateException: 
  at com.google.android.material.slider.BaseSlider.c (BaseSlider.java:38)
  at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty (BaseSlider.java:4)
  at com.google.android.material.slider.BaseSlider.onDraw (BaseSlider.java:5)
  at android.view.View.draw (View.java:20483)
  at android.view.View.updateDisplayListIfDirty (View.java:19294)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.draw (View.java:20486)
  at android.view.View.updateDisplayListIfDirty (View.java:19294)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.draw (View.java:20486)
  at android.widget.ScrollView.draw (ScrollView.java:1790)
  at android.view.View.updateDisplayListIfDirty (View.java:19294)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at androidx.drawerlayout.widget.DrawerLayout.drawChild (DrawerLayout.java:95)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.draw (View.java:20486)
  at android.view.View.updateDisplayListIfDirty (View.java:19294)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.updateDisplayListIfDirty (View.java:19285)
  at android.view.View.draw (View.java:20211)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4394)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4170)
  at android.view.View.draw (View.java:20486)
  at com.android.internal.policy.DecorView.draw (DecorView.java:928)
  at android.view.View.updateDisplayListIfDirty (View.java:19294)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:740)
  at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:746)
  at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:861)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:3586)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3382)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2714)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1636)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7946)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1092)
  at android.view.Choreographer.doCallbacks (Choreographer.java:893)
  at android.view.Choreographer.doFrame (Choreographer.java:812)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1078)
  at android.os.Handler.handleCallback (Handler.java:907)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

**Comment by matpag** [comment]
Can you post the de-obfuscated stacktrace?

**Comment by palicka** [comment]
unfortunately no, this everything what I see in report.

**Comment by dsn5ft** [comment]
As of `1.3.0-alpha01`, we updated all the `IllegalStateException`s in Slider to have more information on what caused the illegal state. E.g., validateValueFrom(), validateValueTo(), validateStepSize(), and validateValues() all called from within the validateConfigurationIfDirty() in the stacktrace should have a message with the exception (https://github.com/material-components/material-components-android/commit/e521fda39595e800e4c2d3c70d4d85a7c1796ff1). All of these illegal states have to do with invalid values or step sizes, so can you double check any related logic in your app?

Maybe the Play Console is grouping the exceptions together and dropping the message. Is it possible to dig into one of the exceptions and see if the message is there? Also are you sure these exceptions are with the `1.3.0-alpha01` version? I think we'll need more information to investigate this.

**Comment by palicka** [comment]
I understand, no problem. I'll close this issue and in case it will happen again or I have more information I'll create new issue.

**Comment by matpag** [comment]
@palicka Next release you upload on Google Play remember to add the mapping.txt to be able to read the de-obfuscated stacktrace :)

**Comment by palicka** [comment]
@matpag  I did it every time. it's strange there was no reference to my part of the code in stack trace , that's why I created this issue...

**Comment by vaidadry** [comment]
We keep experiencing these crashes too, but only on Huawei devices and only Android 9. When using another device on same user account, no crashes occur. Current version `1.4.0-beta01`

```
Fatal Exception: java.lang.IllegalStateException: Value(475.0) must be equal to valueFrom(100.0) plus a multiple of stepSize(100.0) when using stepSize(100.0)
       at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:553)
       at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:587)
       at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1521)
       at android.view.View.draw(View.java:20483)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.draw(View.java:20486)
       at android.widget.ScrollView.draw(ScrollView.java:1790)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.draw(View.java:20486)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.draw(View.java:20486)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.draw(View.java:20486)
       at com.android.internal.policy.DecorView.draw(DecorView.java:928)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:740)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:746)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3586)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3382)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2714)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:812)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)```
