### ISSUE TITLE
Path.op() not supported

### ISSUE THREAD

**Issue by kuuuurt** [material-components/material-components-android#1538]
**Description:** 
When using IntelliJ IDEA 2020.2, the layout editor is having an error on rendering the UI preview.

![Screen Shot 2020-07-29 at 7 11 08 PM](https://user-images.githubusercontent.com/18444033/88793390-48eabc00-d1cf-11ea-8371-0dd1fac5b009.png)

I'm also using the new layout rendering engine but for some reason, it's still suggesting it there. Maybe an issue with IntelliJ IDEA. 

Here's the code to the XML layout

```xml
<androidx.constraintlayout.widget.ConstraintLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:clipChildren="false"
    android:clipToPadding="false"
    android:padding="16dp">

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/til_email"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="48dp"
        android:hint="@string/email_address_hint"
        app:errorEnabled="true"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/edt_email"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textEmailAddress" />

    </com.google.android.material.textfield.TextInputLayout>

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/til_password"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="4dp"
        android:layout_marginBottom="32dp"
        android:hint="@string/password_hint"
        app:endIconMode="password_toggle"
        app:errorEnabled="true"
        app:errorIconDrawable="@null"
        app:layout_constraintBottom_toTopOf="@id/btn_login"
        app:layout_constraintTop_toBottomOf="@id/til_email"
        app:layout_constraintVertical_bias="0"
        tools:layout_editor_absoluteX="16dp">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/edt_password"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textPassword" />

    </com.google.android.material.textfield.TextInputLayout>

</androidx.constraintlayout.widget.ConstraintLayout>
```

Style:

```xml
<style name="Widget.App.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.FilledBox">
    <item name="boxBackgroundColor">@color/light_blue</item>
    <item name="boxCornerRadiusTopStart">4dp</item>
    <item name="boxCornerRadiusTopEnd">4dp</item>
    <item name="boxCornerRadiusBottomStart">4dp</item>
    <item name="boxCornerRadiusBottomEnd">4dp</item>
    <item name="boxStrokeWidth">0dp</item>
    <item name="hintTextColor">@color/blue</item>
    <item name="android:textColorHint">@color/light_blue</item>
</style>
```

Stack trace:

```
java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at java.desktop/java.awt.geom.Path2D$Double.needRoom(Path2D.java:1221)
	at java.desktop/java.awt.geom.Path2D.closePath(Path2D.java:1910)
	at android.graphics.Path_Delegate.close(Path_Delegate.java:824)
	at android.graphics.Path_Delegate.nClose(Path_Delegate.java:329)
	at android.graphics.Path.nClose(Path.java)
	at android.graphics.Path.close(Path.java:513)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:123)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:83)
	at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1160)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:945)
	at com.google.android.material.textfield.TextInputLayout.drawBoxUnderline(TextInputLayout.java:3793)
	at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:3779)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1800)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1998)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:404)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:556)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:115)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:142)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:124)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$11(RenderTask.java:895)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior:** It should generate the preview correctly.

**Android API version:** 29

**Material Library version:** 1.3.0-alpha02

**Comment by dsn5ft** [comment]
This does seem like it could be an issue with the layout editor. Can you file a bug here:

https://issuetracker.google.com/issues/new?component=192747&template=1023344

**Comment by kuuuurt** [comment]
Sure. The reason I filed it here was because this issue occured on previous versions too. Apparently, [downgrading solves it on earlier versions](https://stackoverflow.com/q/59809654/6126461). In this case, Android Studio 4.0.1 perfectly renders the view. The problem only occurs in IntelliJ IDEA 2020.2.
