### ISSUE TITLE
[RangeSlider/Slider] Invalid validation of step size

### ISSUE THREAD

**Issue by ansman** [material-components/material-components-android#1587]
**Description:** The validation of slider values is incorrect and thus some valid values are not allowed.

**Expected behavior:** I'm trying to set up a slider with the range `0.1..10.0` and a step of `0.1` should be valid but the slider throws an exception:
```
    java.lang.IllegalStateException: The stepSize(0.1) must be 0, or a factor of the valueFrom(0.1)-valueTo(10.0) range
        at com.google.android.material.slider.BaseSlider.validateStepSize(BaseSlider.java:456)
        at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:490)
        at com.google.android.material.slider.BaseSlider.calculateTicksCoordinates(BaseSlider.java:1268)
        at com.google.android.material.slider.BaseSlider.onSizeChanged(BaseSlider.java:1261)
```

**Source code:**
```kotlin
val slider: Slider = ...
slider.valueFrom = 0.1f
slider.valueTo = 10f
slider.stepSize = 0.1f
```

**Android API version:** Android 10 (API 29)

**Material Library version:** 1.2.0

**Device:** Google Pixel 4XL

**Comment by ansman** [comment]
As a workaround you can set the step size to `0.09999999f` which will produce the same effect but without the crash.
