### ISSUE TITLE
[BottomSheetBehavior] Crash during applying window insets

### ISSUE THREAD

**Issue by alexzatsepin** [material-components/material-components-android#1617]
**Description:** We get the crash on app launch. Seems that it's incompatible version of **BottomSheetBehaviort** that is from material components and **WindowInsetsCompat** that is from AndroidX. The crash started to be reproduced from the material components library 1.2.0 on any Android 10 device. On version 1.1.0 - it wasn't. Please help us to fix this issue or send us to right solution with correct libraries configuration. Thank you!

```
java.lang.NoSuchMethodError: No virtual method getMandatorySystemGestureInsets()Landroidx/core/graphics/Insets; in class Landroidx/core/view/WindowInsetsCompat; or its super classes (declaration of 'androidx.core.view.WindowInsetsCompat' appears in /data/app/~~ms6ZatdeJKYW5ygqX389kQ==/com.mapswithme.maps.pro.debug-8H1lPMHurxdkDeyFfUxcaQ==/base.apk)
        at com.google.android.material.bottomsheet.BottomSheetBehavior$3.onApplyWindowInsets(BottomSheetBehavior.java:1260)
        at com.google.android.material.internal.ViewUtils$3.onApplyWindowInsets(ViewUtils.java:227)
        at androidx.core.view.ViewCompat$1.onApplyWindowInsets(ViewCompat.java:2431)
        at android.view.View.dispatchApplyWindowInsets(View.java:11299)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7247)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7261)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7252)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7261)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7252)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7261)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7252)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7261)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7252)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7261)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7252)
        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7261)
        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7252)
        at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:2265)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2502)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1934)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8127)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

P.S. @dsn5ft probably you know what is the problem with our configuration...I see that you recently touched that code in material components. Thanks looking forward!

**Source code:** https://s.mail.ru/6WPU/v2bE6kkCR

**Android API version:** 10

**Material Library version:** 1.2.0

**Device:** Emulator Pixel 3 API 30, Huawei p20, Huawei p30

**Comment by gabrielemariotti** [comment]
Which version of androidx.core (`androidx.core:core`) library are you using in your project?

**Comment by alexzatsepin** [comment]
@gabrielemariotti 1.1.0. But now, I'm building the project with  "androidx.core:core:1.3.1" and I guess the problem will be gone. If so, I'll close issue, thank you!

**Comment by alexzatsepin** [comment]
The problem was in incorrect(obsolete) version of androidx.core.core library version (1.1.0). After update to 1.3.1 the problem is gone.
