### ISSUE TITLE
[ProgressIndicator] java.lang.StackOverflowError

### ISSUE THREAD

**Issue by EliuTimana** [material-components/material-components-android#1665]
**Description:** App crashes randomly and I get this exception trace, this does not happen when using normal ProgressBar
```
com.eliutimana.medicamentos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eliutimana.medicamentos, PID: 20661
    java.lang.StackOverflowError: stack size 8MB
        at com.google.android.material.progressindicator.DrawableWithAnimatedVisibilityChange.hideNow(DrawableWithAnimatedVisibilityChange.java:191)
        at com.google.android.material.progressindicator.IndeterminateDrawable.hideNow(IndeterminateDrawable.java:30)
        at com.google.android.material.progressindicator.ProgressIndicator.setIndeterminate(ProgressIndicator.java:627)
        at com.google.android.material.progressindicator.ProgressIndicator$2.onAnimationEnd(ProgressIndicator.java:990)
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate$2.onAnimationEnd(CircularIndeterminateAnimatorDelegate.java:109)
        at android.animation.AnimatorSet.cancel(AnimatorSet.java:340)
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate.cancelAnimatorImmediately(CircularIndeterminateAnimatorDelegate.java:149)
        at com.google.android.material.progressindicator.IndeterminateDrawable.setVisible(IndeterminateDrawable.java:68)
        at com.google.android.material.progressindicator.DrawableWithAnimatedVisibilityChange.hideNow(DrawableWithAnimatedVisibilityChange.java:191)
        at com.google.android.material.progressindicator.IndeterminateDrawable.hideNow(IndeterminateDrawable.java:30)
        at com.google.android.material.progressindicator.ProgressIndicator.setIndeterminate(ProgressIndicator.java:627)
        at com.google.android.material.progressindicator.ProgressIndicator$2.onAnimationEnd(ProgressIndicator.java:990)
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate$2.onAnimationEnd(CircularIndeterminateAnimatorDelegate.java:109)
        at android.animation.AnimatorSet.cancel(AnimatorSet.java:340)
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate.cancelAnimatorImmediately(CircularIndeterminateAnimatorDelegate.java:149)
        at com.google.android.material.progressindicator.IndeterminateDrawable.setVisible(IndeterminateDrawable.java:68)
        at com.google.android.material.progressindicator.DrawableWithAnimatedVisibilityChange.hideNow(DrawableWithAnimatedVisibilityChange.java:191)
        at com.google.android.material.progressindicator.IndeterminateDrawable.hideNow(IndeterminateDrawable.java:30)
        at com.google.android.material.progressindicator.ProgressIndicator.setIndeterminate(ProgressIndicator.java:627)
        at com.google.android.material.progressindicator.ProgressIndicator$2.onAnimationEnd(ProgressIndicator.java:990)
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate$2.onAnimationEnd(CircularIndeterminateAnimatorDelegate.java:109)
        at android.animation.AnimatorSet.cancel(AnimatorSet.java:340)
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate.cancelAnimatorImmediately(CircularIndeterminateAnimatorDelegate.java:149)
        at com.google.android.material.progressindicator.IndeterminateDrawable.setVisible(IndeterminateDrawable.java:68)
        at com.google.android.material.progressindicator.DrawableWithAnimatedVisibilityChange.hideNow(DrawableWithAnimatedVisibilityChange.java:191)
        at com.google.android.material.progressindicator.IndeterminateDrawable.hideNow(IndeterminateDrawable.java:30)
        at com.google.android.material.progressindicator.ProgressIndicator.setIndeterminate(ProgressIndicator.java:627)
        at com.google.android.material.progressindicator.ProgressIndicator$2.onAnimationEnd(ProgressIndicator.java:990)
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate$2.onAnimationEnd(CircularIndeterminateAnimatorDelegate.java:109)
        at android.animation.AnimatorSet.cancel(AnimatorSet.java:340)
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate.cancelAnimatorImmediately(CircularIndeterminateAnimatorDelegate.java:149)
        at com.google.android.material.progressindicator.IndeterminateDrawable.setVisible(IndeterminateDrawable.java:68)
    	at com.google.android.material.progressindicator.DrawableW
com.eliutimana.medicamentos E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
com.eliutimana.medicamentos E/AndroidRuntime: Error reporting crash
    android.os.TransactionTooLargeException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:504)
        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4294)
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89)
        at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-SystemWebViewGoogle.aab-stable-1:6)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

```
**Expected behavior:** Progress Indicator should work without errors

**Source code:** 
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

        <variable
            name="viewModel"
            type="com.eliutimana.medicamentos.ui.main.MainViewModel" />
    </data>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/recyclerView_suggestions"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:clipToPadding="false"
                android:paddingTop="8dp"
                android:paddingBottom="8dp"
                app:items="@{viewModel.autocompleteItems}"
                app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
                app:status="@{viewModel.status}"
                tools:listitem="@layout/item_history" />

            <com.google.android.material.progressindicator.ProgressIndicator
                android:id="@+id/progressBar"
                style="@style/Widget.MaterialComponents.ProgressIndicator.Circular.Indeterminate"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <TextView
                android:id="@+id/textViewLoading"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:text="@string/loading"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/progressBar" />

            <ImageView
                android:id="@+id/imageView"
                android:layout_width="120dp"
                android:layout_height="120dp"
                android:contentDescription="@string/medicine_cabinet_with_magnifying_glass"
                app:layout_constraintBottom_toTopOf="@+id/textView"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_chainStyle="packed"
                app:status="@{viewModel.status}"
                tools:srcCompat="@drawable/ic_search_property" />

            <TextView
                android:id="@+id/textView"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="32dp"
                android:layout_marginTop="16dp"
                android:layout_marginEnd="32dp"
                android:textAlignment="center"
                android:textAppearance="@style/TextAppearance.MaterialComponents.Subtitle1"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/imageView"
                app:status="@{viewModel.status}"
                tools:text="@string/enter_medicine_name_or_active_ingredient" />

            <Button
                android:id="@+id/button_retry"
                style="?attr/materialButtonOutlinedStyle"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:text="@string/retry"
                app:layout_constraintEnd_toEndOf="@+id/imageView"
                app:layout_constraintStart_toStartOf="@+id/imageView"
                app:layout_constraintTop_toBottomOf="@+id/textView"
                app:status="@{viewModel.status}" />
        </androidx.constraintlayout.widget.ConstraintLayout>
    </LinearLayout>
</layout>
```

```
//fragment.kt

viewModel.status.observe(viewLifecycleOwner, {
    binding.progressBar.apply {
        if (it == MainViewModel.MainViewStatus.LOADING) {
            show()
        } else {
            hide()
        }
    }
    binding.textViewLoading.isVisible = it == MainViewModel.MainViewStatus.LOADING
})
```
**Android API version:** 21 

**Material Library version:** 1.3.0-alpha02

**Device:** BLU STUDIO ONE PLUS - Android 5.1 (i was not able to reproduce in an emulator)

**Comment by pekingme** [comment]
Sorry for the late update. The AnimationCallback used in indeterminate animator delegates caused several issues. It has been updated in fdb420f540910315140b2d410e6b95d21d538a06 and 2163e3d2cbf4d259364f883d642edd6c97638f0b. Could you please verify the bug with the [snapshot version](https://github.com/material-components/material-components-android/blob/master/docs/using-snapshot-version.md)? And feel free to reopen the issue if it persists. Thanks.
