### ISSUE TITLE
[ShapeableImageView] Unable to create layer for ShapeableImageView

### ISSUE THREAD

**Issue by Jeff11** [material-components/material-components-android#1671]
Stacktrace
```
Fatal Exception: java.lang.IllegalStateException: Unable to create layer for ShapeableImageView
    at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
    at android.os.MessageQueue.next(MessageQueue.java:143)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:6917)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Source xml
```
    <com.google.android.material.imageview.ShapeableImageView
        android:id="@+id/profileIv"
        android:layout_width="80dp"
        android:layout_height="80dp"
        android:layout_gravity="center"
        android:padding="4dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.34"
        app:shapeAppearanceOverlay="@style/CircleImageView"
        app:strokeColor="@color/white"
        app:strokeWidth="4dp"
        tools:src="@tools:sample/avatars"/>
```
```
    <style name="CircleImageView">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">50%</item>
    </style>
```

**Android API version:** Only Android 5.1.1

**Material Library version:** 1.3.0-alpha02

**Device:** Exclusively Samsung devices, in descending order: Galaxy J3(2016), J1(2016), J4+, J6+, Tab A 7.0, J3

**Comment by ymarian** [comment]
Can you share a sample app that repros the issue?
