### ISSUE TITLE
"onclick" throw exception on Lollipop devices when view uses materialThemeOverlay

### ISSUE THREAD

**Issue by EmpowerZ** [material-components/material-components-android#1680]
**Description:** When clicking on floatingActionButton (or com.google.android.material.textfield.TextInputEditText) which has onClick registered via xml. This happens:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tonedownlabs.automoney, PID: 9434
    java.lang.IllegalStateException: Could not find a method onAddButtonClicked(View) in the activity class androidx.appcompat.view.ContextThemeWrapper for onClick handler on view class com.google.android.material.floatingactionbutton.FloatingActionButton with id 'myFab'
        at android.view.View$1.onClick(View.java:3994)
        at android.view.View.performClick(View.java:4756)
        at android.view.View$PerformClick.run(View.java:19749)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NoSuchMethodException: onAddButtonClicked [class android.view.View]
        at java.lang.Class.getMethod(Class.java:664)
        at java.lang.Class.getMethod(Class.java:643)
        at android.view.View$1.onClick(View.java:3987)
        at android.view.View.performClick(View.java:4756) 
        at android.view.View$PerformClick.run(View.java:19749) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
```
The same code works perfectly fine on newer APIs.
The issue stops reproducing when I remove materialThemeOverlay from fab's style.

**Source code:** 
styles.xml:
```
<item name="floatingActionButtonStyle">@style/Fab.Full</item>
....

<style name="Fab.Full" parent="Widget.MaterialComponents.FloatingActionButton">
        <item name="materialThemeOverlay">@style/Fab.Full.Overlay</item>
</style>

<style name="Fab.Full.Overlay" parent="">
</style>
```

layout:
```
<com.google.android.material.floatingactionbutton.FloatingActionButton
                android:id="@+id/noDataFabAdd"
                android:layout_height="wrap_content"
                android:layout_width="wrap_content"
                android:onClick="onAddButtonClicked"

/>
```

Activity.java:
```
  public void onAddButtonClicked(View view) {
  ...
  }
```

**Android API version:** Reproduced on 21 API. On new versions of API (tried 26) it does not reproduce

**Material Library version:** 1.2.0

**Device:** Galaxy Nexus

**Comment by ymarian** [comment]
A material theme overlay will wrap the context in a new one which won't have your method. 

Unfortunately we cannot do anything to support this. This is one of the reasons why setting android:onClick is deprecated and should be avoided.
