### ISSUE TITLE
[TextInputLayout] Loading state solution using END_ICON_CUSTOM and END_ICON_CLEAR_TEXT crashes app  

### ISSUE THREAD

**Issue by vpuonti** [material-components/material-components-android#1748]
**Description:** 

Setting a custom loading state to TextInputLayout using guide described [here](https://stackoverflow.com/a/57661169/13088785) causes unexpected crash of the application on most versions of the library. 

Stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fi.vpuonti.textinputlayoutbug, PID: 26919
    java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.get(ArrayList.java:437)
        at android.widget.TextView.sendOnTextChanged(TextView.java:10610)
        at android.widget.TextView.handleTextChanged(TextView.java:10700)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:13454)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1282)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:591)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:522)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:42)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
        at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:393)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

![broken](https://user-images.githubusercontent.com/25032592/94000536-f7f6de80-fd9f-11ea-857d-a8813c4bcdfd.gif)

**Expected behavior:** 

- Text is entered
- Text is sent to ViewModel
- ViewModel updates search state to `Loading`
- Activity reacts to search state and calls `showLoading()`
- Progress drawable is shown in `endIconDrawable`
- ViewModel completes search processing and updates Search state to `Success`
- Activity reacts to Search-state and calls `hideLoading()`
- Default "X"-drawable is shown in `endIconDrawable`

![working](https://user-images.githubusercontent.com/25032592/94000354-bfef9b80-fd9f-11ea-9d85-b5704cf28adf.gif)

**Source code:** 

Sample app: https://github.com/vpuonti/TextInputLayoutBug

Relevant snippets:
```kotlin
    private fun showLoading() {
        mTextInputLayout.endIconMode = TextInputLayout.END_ICON_CUSTOM
        mTextInputLayout.endIconDrawable = mProgressDrawable
        (mTextInputLayout.endIconDrawable as Animatable).start()
    }

    private fun hideLoading() {
        (mTextInputLayout.endIconDrawable as Animatable).stop()
        mTextInputLayout.endIconMode = TextInputLayout.END_ICON_CLEAR_TEXT
    }
```

**Android API version:** 

Android 10 API 29. 

**Material Library version:** 

Used version in repro-app: `1.2.1`.

Also tested on other versions:

| Version | Working as expected |
|---|---|
| 1.1.0 | no (loading icon sometimes disappears) |
| 1.2.0-alpha05 | yes |
| 1.2.0-alpha06 | yes |
| 1.2.0-beta01 | no |
| 1.2.0-rc01 | no |
| 1.2.0 | no |
| 1.2.1 | no |
| 1.3.0-alpha01 | no |
| 1.3.0-alpha02 | no |

**Device:** 

OnePlus 7. Bug also reproducible on emulators.

**Comment by vpuonti** [comment]
Possibly related to https://github.com/material-components/material-components-android/issues/1724
