### ISSUE TITLE
[MaterialCardView] stroke not rendering in preview

### ISSUE THREAD

**Issue by AlaaZarifa** [material-components/material-components-android#1806]
**Description:** When applying stroke for the card it doesn't show at all in the preview, but in the emulator and physical device it shows normally with no issues.

**Expected behavior:**

Preview
-
![preview](https://user-images.githubusercontent.com/18426012/96362584-151c9400-1137-11eb-9a04-4907de785a8f.jpg)

Physical device 
-
![device](https://user-images.githubusercontent.com/18426012/96362582-13eb6700-1137-11eb-94bd-4ee3658f7ba5.jpg)

**Source code:**  

```
    <com.google.android.material.card.MaterialCardView
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_gravity="top|center_horizontal"
        android:layout_margin="20dp"
        app:cardCornerRadius="10dp"
        app:cardElevation="10dp"
        app:strokeColor="@color/red"
        app:strokeWidth="5dp">


        <TextView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:padding="10dp"
            android:text="Stroke should be showing"
            android:textColor="@color/textDark"
            android:textSize="@dimen/text_mini" />

    </com.google.android.material.card.MaterialCardView>
```

**Android API version:** tested on 29 and 30

**Material Library version:** `1.3.0-alpha03`

**Device:** no problem with the device

**Comment by hunterstich** [comment]
Hey @AlaaZarifa,

Can you click on the red exclamation point icon in your first comment and post what the error message says?

**Comment by AlaaZarifa** [comment]
Hey @hunterstich 
I just checked, there are two **render** problems

**First one** 
`Path.op() not supported`

**Second one** 
```
 java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at java.awt.geom.Path2D$Float.needRoom(Path2D.java:324)
	at java.awt.geom.Path2D.closePath(Path2D.java:1877)
	at android.graphics.Path_Delegate.close(Path_Delegate.java:824)
	at android.graphics.Path_Delegate.nClose(Path_Delegate.java:329)
	at android.graphics.Path.nClose(Path.java)
	at android.graphics.Path.close(Path.java:513)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:139)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:99)
	at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1167)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:952)
	at android.graphics.drawable.DrawableWrapper.draw(DrawableWrapper.java:240)
	at android.view.View.onDrawForeground(View.java:23350)
	at android.view.View.draw_Original(View.java:21456)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:404)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:556)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:115)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:142)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:124)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$11(RenderTask.java:894)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hunterstich** [comment]
Perfect. Thanks for the quick response.

I've passed this along to the Android Studio team

**Comment by hunterstich** [comment]
@AlaaZarifa what version of Android Studio are you using?

**Comment by jgaillard85** [comment]
This should be fixed by the new rendering engine introduced in Android Studio 4.0. If you are using Android Studio 4.0 or newer, you can enable the new rendering engine in the Experimental tab of the Settings dialog
![Screen Shot 2020-10-20 at 3 01 22 PM](https://user-images.githubusercontent.com/15216610/96596944-8c942400-12ed-11eb-8bd8-b31a8c583e12.png)

**Comment by AlaaZarifa** [comment]
@hunterstich 4.0.2
@jgaillard85 Awesome, it shows perfectly fine now 😃 🥳  ..but should I expect any issues after enabling the new engine?

**Comment by hunterstich** [comment]
Nice! Thanks for jumping in @jgaillard85

**Comment by jgaillard85** [comment]
We are not aware of any issues specific to the new rendering engine. But if you encounter any problem, please file a bug at issuetracker.google.com

**Comment by AlaaZarifa** [comment]
@jgaillard85 Great. Thanks.
