### ISSUE TITLE
[MaterialTimePicker] Error Inflating MaterialTimePicker, missing layout_height attribute

### ISSUE THREAD

**Issue by waltojac** [material-components/material-components-android#1955]
**Description:** With the latest update to 1.3.0-beta01, my app crashes when trying to show the MaterialTimePicker dialog. Here is the stack trace of the crash:
```
Caused by: android.view.InflateException: Binary XML file line #46 in [my_app_id]:layout/material_timepicker_dialog: Error inflating class com.google.android.material.timepicker.TimePickerView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at com.google.android.material.timepicker.MaterialTimePicker.onCreateView(MaterialTimePicker.java:205)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.view.InflateException: Binary XML file line #27 in [my_app_id]:layout/material_timepicker: Binary XML file line #35: You must supply a layout_height attribute.
     Caused by: java.lang.UnsupportedOperationException: Binary XML file line #35: You must supply a layout_height attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:830)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8232)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8429)
        at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2023)
        at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1917)
        at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:89)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:654)
2020-12-28 15:22:07.350 1705-1705/[my_app_id] E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at com.google.android.material.timepicker.TimePickerView.<init>(TimePickerView.java:100)
        at com.google.android.material.timepicker.TimePickerView.<init>(TimePickerView.java:95)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at com.google.android.material.timepicker.MaterialTimePicker.onCreateView(MaterialTimePicker.java:205)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
I don't define the time picker in a layout file at all in my app, only programmatically. The crash seems to be coming from the library's .xml layout file from what I can see in the trace.

**Expected behavior:** No crash when executing the dialog.show(...) method.

**Source code:** 
```
private lateinit var materialTimePicker: MaterialTimePicker
...

materialTimePicker = MaterialTimePicker.Builder()
                .setTitleText(title)
                .setHour(jodaLocalTime.hourOfDay)
                .setMinute(jodaLocalTime.minuteOfHour)
                .setTimeFormat(TimeFormat.CLOCK_12H)
                .build()

// Show the material time picker
materialTimePicker.show(requireActivity().supportFragmentManager, materialTimePicker.toString())
```
**Android API version:** Android 11 (30)

**Material Library version:** 1.3.0-beta01

**Device:** Pixel 3XL

**Comment by adrcotfas** [comment]
I see the same behavior with an API level 26 Samsung device.

**Comment by Abdqadr1** [comment]
I see the same error when i tried to show timepicker from a dialog activity

**Comment by cpferschy** [comment]
Hi there, I experienced the same problem but could resolve it by inheriting the MaterialTimePicker ThemeOverlay from the new ThemeOverlay.MaterialComponents.TimePicker. See release notes: https://github.com/material-components/material-components-android/releases/tag/1.3.0-beta01

**Comment by waltojac** [comment]
> Hi there, I experienced the same problem but could resolve it by inheriting the MaterialTimePicker ThemeOverlay from the new ThemeOverlay.MaterialComponents.TimePicker. See release notes: https://github.com/material-components/material-components-android/releases/tag/1.3.0-beta01

cpferschy: Thank you! I saw that line in there, but didn't think to change anything since I was not explicitly inheriting the old theme. I changed my modified`MaterialTimePickerTheme` style parent from `""` to `"ThemeOverlay.MaterialComponents.TimePicker"` and it worked again. 

Source:
```

    <!--  Theme for App -->
    <style name="AppTheme" parent="Theme.MaterialComponents">
        ...
       <item name="materialTimePickerTheme">@style/AppTheme.MaterialTimePickerTheme</item>
    </style>


    <!-- Theme for Material Time Picker - default for app -->
    <style name="AppTheme.MaterialTimePickerTheme" parent="ThemeOverlay.MaterialComponents.TimePicker">
        <item name="colorPrimary">@color/blue_light</item>
    </style>
```

**Comment by arosca-nl** [comment]
I'm seeing the same crash for AlertDialog 

`<style name="AppComponents.AlertDialog" parent="ThemeOverlay.MaterialComponents.MaterialAlertDialog">`

issues is in `mrtl_alert_dialog_title` where  layout_width/layout_height are missing in the layout and are applied via style

**Comment by Zalecom** [comment]
I'm seeing the same crash for material Library version: 1.3.0

You need to add a layout with the name **material_clock_period_toggle.xml** to the project. Layout_height is missing for this layout 

**Solution:**
```
<?xml version="1.0" encoding="utf-8"?>
<com.google.android.material.button.MaterialButtonToggleGroup
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/material_clock_period_toggle"
    android:layout_width="@dimen/material_clock_period_toggle_width"
    android:layout_height="@dimen/material_clock_period_toggle_height"
    android:layout_marginStart="@dimen/material_clock_period_toggle_margin_left"
    android:background="?attr/colorSurface"
    android:orientation="vertical"
    android:contentDescription="@string/material_clock_toggle_content_description"
    app:checkedButton="@id/material_clock_period_am_button"
    app:layout_constraintStart_toEndOf="@id/material_clock_display"
    app:layout_constraintTop_toTopOf="parent"
    android:visibility="gone"
    app:selectionRequired="true"
    app:singleSelection="true">

    <com.google.android.material.button.MaterialButton
        style="?attr/materialButtonOutlinedStyle"
        android:id="@+id/material_clock_period_am_button"
        android:insetTop="8dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:shapeAppearanceOverlay="?attr/shapeAppearanceMediumComponent"
        android:text="@string/material_timepicker_am"/>
    <com.google.android.material.button.MaterialButton
        style="?attr/materialButtonOutlinedStyle"
        android:id="@+id/material_clock_period_pm_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:insetBottom="8dp"
        app:shapeAppearanceOverlay="?attr/shapeAppearanceMediumComponent"
        android:text="@string/material_timepicker_pm"/>

</com.google.android.material.button.MaterialButtonToggleGroup>
```

**Comment by Nailik** [comment]
For me the Problem is, that i use 
`<style name="AppTheme" parent="@style/Theme.AppCompat.Light">`
instead of
`<style name="AppTheme" parent="ThemeOverlay.MaterialComponents">`

But when i change the parent Theme it obviously destroys all other themeing in my app (or at least a lot). Also MaterialDatePicker is working with `Theme.AppCompat.Light`.

**Comment by gringofe** [comment]
TimePicker works fine with 
`<style name="AppTheme" parent="Theme.MaterialComponents.DayNight">`

but crashes when set to

`<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.DarkActionBar.Bridge">`

(but only if the system darktheme is enabled)

**Comment by drchen** [comment]
I think this has been fixed for a while. : )   (The fix was submitted around mid-Oct last year.)

Feel free to reopen the issue if this is still happening with the latest library version.

**Comment by telpat0298** [comment]
I have the same issue for the MaterialDatePicker component. I tried all the solutions above, but nothing seems to work. It just says:

`layout/mtrl_picker_dialog: Binary XML file line #31: You must supply a layout_width attribute.
                                                                                                    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #31: You must supply a layout_width attribute.`

**Comment by meor9zcu12** [comment]
I used 1.10.0, it still work on `@style/Theme.MaterialComponents.NoActionBar` but not `@style/Theme.MaterialComponents.NoActionBar.Bridge`.
It does not make sense it still not support `Bridge` as it is under `MaterialComponents`

**Comment by KrupaliSangani45** [comment]
> I have the same issue for the MaterialDatePicker component. I tried all the solutions above, but nothing seems to work. It just says:
> 
> `layout/mtrl_picker_dialog: Binary XML file line #31: You must supply a layout_width attribute. Caused by: java.lang.UnsupportedOperationException: Binary XML file line #31: You must supply a layout_width attribute.`


Hey @telpat0298 
Can you please guide how you fixed this?

**Comment by singgihsaputro** [comment]
This issue still happened to me on 1.12.0 https://github.com/material-components/material-components-android/issues/1955#issuecomment-1565312583

**Comment by singgihsaputro** [comment]
sorry, I've found the solution, we need to use theme that have parent of ThemeOverlay.MaterialComponents.MaterialCalendar @KrupaliSangani45

**Comment by lorobode** [comment]
I have this:

`<style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar.Bridge">
..
    <item name="materialTimePickerTheme">@style/AppTheme.MaterialTimePickerTheme</item>
 </style>

<style name="AppTheme.MaterialTimePickerTheme" parent="ThemeOverlay.MaterialComponents.TimePicker">
    <item name="colorPrimary">@color/accent</item>
</style>`

And the issue still happened. If I remove `Bridge` it works. Any hints?

**Comment by lorobode** [comment]
I have this:

`<style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar.Bridge">`
..
`    <item name="materialTimePickerTheme">@style/AppTheme.MaterialTimePickerTheme</item>`
`</style>`
`<style name="AppTheme.MaterialTimePickerTheme" parent="ThemeOverlay.MaterialComponents.TimePicker">`
`    <item name="colorPrimary">@color/accent</item>`
`</style>`

And the issue still happened. If I remove Bridge it works. Any hints?
