### ISSUE TITLE
Rendering Problem in Android Studio with Basic Activity

### ISSUE THREAD

**Issue by Aniket-Das-Coder** [material-components/material-components-android#1994]
java.awt.geom.IllegalPathStateException: missing initial moveto in path definition
	at java.awt.geom.Path2D$Double.needRoom(Path2D.java:1193)
	at java.awt.geom.Path2D.closePath(Path2D.java:1877)
	at android.graphics.Path_Delegate.close(Path_Delegate.java:824)
	at android.graphics.Path_Delegate.nClose(Path_Delegate.java:329)
	at android.graphics.Path.nClose(Path.java)
	at android.graphics.Path.close(Path.java:513)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:123)
	at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:83)
	at com.google.android.material.shape.MaterialShapeDrawable.calculateStrokePath(MaterialShapeDrawable.java:1160)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:945)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1018)
	at android.graphics.drawable.RippleDrawable.drawContent(RippleDrawable.java:821)
	at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:678)
	at android.view.View.drawBackground(View.java:21671)
	at android.view.View.draw_Original(View.java:21435)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at android.view.View.draw_Original(View.java:21317)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21315)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:21089)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4388)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw_Original(View.java:21446)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:21417)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:404)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:556)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:115)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:143)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:125)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$11(RenderTask.java:966)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

-----------------------------------------------------------------------------------------------------------------------------------

I just created a Basic Activity a this Rendering Problem popped up.......

Need Suggestions how to fix this issue......

**Comment by pekingme** [comment]
Sorry to hear that. It sounds frustrating. Is this consistent when you close/delete the project and create a new one? If it consistently fails, please share more details to help us reproduce it and look deeper, such as android studio version, library version, project configuration while creating (if not default), etc. Thanks.

**Comment by pekingme** [comment]
Feel free to reopen with more details.
