### ISSUE TITLE
[Material 1.2.1] NoSuchMethodError Crash specific for Android 10

### ISSUE THREAD

**Issue by chnerypriyono** [material-components/material-components-android#2029]
**Description:**
NoSuchMethodError Crash specific for Android 10
<img width="1168" alt="Screen Shot 2021-02-03 at 16 30 12" src="https://user-images.githubusercontent.com/13723945/106726577-1f5a9380-663d-11eb-8295-6e7db1ba5a5e.png">

**Expected behavior:**
Not Crashing

**Stack trace:**

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method getMandatorySystemGestureInsets()Landroidx/core/graphics/Insets; in class Landroidx/core/g/ae; or its super classes (declaration of 'androidx.core.g.ae' appears in base.apk)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$3.onApplyWindowInsets(BottomSheetBehavior.java:1276)
       at com.google.android.material.internal.ViewUtils$3.onApplyWindowInsets(ViewUtils.java:227)
       at androidx.core.view.ViewCompat$1.onApplyWindowInsets(ViewCompat.java:2431)
       at android.view.View.dispatchApplyWindowInsets(View.java:10559)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7256)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7268)
       at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7258)
       at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:2025)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2276)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7783)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
       at android.view.Choreographer.doCallbacks(Choreographer.java:865)
       at android.view.Choreographer.doFrame(Choreographer.java:800)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Android API version:**
10

**Material Library version:**
1.2.1

**Device:**
Xiaomi

**Comment by dsn5ft** [comment]
Hi @chnerypriyono, the getMandatorySystemGestureInsets() method comes from the [androidx.core library](https://developer.android.com/reference/androidx/core/view/WindowInsetsCompat#getMandatorySystemGestureInsets()). 

Can you check what version of androidx.core is using? It should be at least `androidx.core:core:1.2.0`.

**Comment by chnerypriyono** [comment]
hi @dsn5ft , we are still using `androidx.core:core:1.1.0-rc01` , will try to update it to 1.2.0, thanks for your help!

**Comment by chnerypriyono** [comment]
anyway, just wondering why this only happens on specific combination of Android 10, Xiaomi, with miui, and working fine on others?

**Comment by dsn5ft** [comment]
Nice, hopefully that works. I'm not really sure why it would only be on one device type.

**Comment by drchen** [comment]
Assuming this is fixed with the newer androidx.core versions. Closing the issue.
