### ISSUE TITLE
NPE in TextInputLayout with hint and empty text on Meizu Phones

### ISSUE THREAD

**Issue by DementorAl** [material-components/material-components-android#216]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
        at android.widget.Editor.updateCursorPositionMz(Editor.java:7598)
        at android.widget.Editor.updateCursorsPositions(Editor.java:1932)
        at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5742)
        at android.widget.TextView.onDraw(TextView.java:5928)
        at android.view.View.draw(View.java:17301)
        at android.view.View.updateDisplayListIfDirty(View.java:16283)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.View.draw(View.java:17067)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17304)
        at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
        at android.view.View.updateDisplayListIfDirty(View.java:16283)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
        at android.view.View.updateDisplayListIfDirty(View.java:16246)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2838)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2640)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2244)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1279)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6477)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6286)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by Lomovskiy** [comment]
I had the same problem on Meizu M5c Android 6.0

**Comment by cketcham** [comment]
https://issuetracker.google.com/issues/117662940
