### ISSUE TITLE
[AppBarLayout] Resources$NotFoundException: design_appbar_state_list_animator.xml

### ISSUE THREAD

**Issue by pengfeigao** [material-components/material-components-android#2186]
**Description:** 

Firebase crash log：
```
Caused by android.view.InflateException: Binary XML file line #20: Error inflating class <unknown>
```

```
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:658)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.****.***.****.base.BaseActivity.onCreate(BaseActivity.java:175)
       at android.app.Activity.performCreate(Activity.java:7383)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

```
Caused by android.content.res.Resources$NotFoundException: File res/mipmap-xxhdpi-v4/ic_launcher.png from xml type anim resource ID #0x7f020000
       at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1435)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2312)
       at android.content.res.Resources.getAnimation(Resources.java:1317)
       at android.animation.AnimatorInflater.loadStateListAnimator(AnimatorInflater.java:171)
       at com.google.android.material.appbar.ViewUtilsLollipop.setStateListAnimatorFromAttrs(ViewUtilsLollipop.java:51)
       at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:215)
       at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:199)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:658)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.***.***.***.base.BaseActivity.onCreate(BaseActivity.java:175)
       at android.app.Activity.performCreate(Activity.java:7383)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

```
Caused by java.io.FileNotFoundException: Corrupt XML binary file
       at android.content.res.AssetManager.openXmlAssetNative(AssetManager.java)
       at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:862)
       at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1420)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2312)
       at android.content.res.Resources.getAnimation(Resources.java:1317)
       at android.animation.AnimatorInflater.loadStateListAnimator(AnimatorInflater.java:171)
       at com.google.android.material.appbar.ViewUtilsLollipop.setStateListAnimatorFromAttrs(ViewUtilsLollipop.java:51)
       at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:215)
       at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:199)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:658)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.***.***.***.base.BaseActivity.onCreate(BaseActivity.java:175)
       at android.app.Activity.performCreate(Activity.java:7383)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
![image](https://user-images.githubusercontent.com/9261499/115510792-bf29d400-a2b2-11eb-8620-f1423ab04c06.png)

![image](https://user-images.githubusercontent.com/9261499/115510732-ade0c780-a2b2-11eb-96db-a3a4661962bd.png)

![image](https://user-images.githubusercontent.com/9261499/115511777-d2896f00-a2b3-11eb-9683-ebb1affb4e5f.png)
![image](https://user-images.githubusercontent.com/9261499/115511793-d6b58c80-a2b3-11eb-9da7-d7f63607c414.png)

**Expected behavior:** 
I don't understand why the anim resource ID #0x7f020000(design_appbar_state_list_animator.xml)  is bound to the res/mipmap-xxhdpi-v4/ic_launcher.png.

**Source code:** 
I can't reproduce the bug,This bug only crash on some of Huawei's phones

**Android API version:** 
Android 8.0.0 8.1.0

**Material Library version:** 
1.2.1

**Device:** 
![image](https://user-images.githubusercontent.com/9261499/115510829-c7820f00-a2b2-11eb-8c5f-8356abc2fd76.png)

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by drchen** [comment]
Not sure what happened but why do you need to copy design_appbar_state_list_animator.xml to your project?
