### ISSUE TITLE
[MotionLayout] not found

### ISSUE THREAD

**Issue by danilshik** [material-components/material-components-android#2209]
**Description:** I used the 1.3.0-alpha01.
I wanted to fix the bug (https://github.com/material-components/material-components-android/issues/1719), so I updated to the latest version.
But I started to crash the app due to an error
`java.lang.RuntimeException: Unable to resume activity {com.app.peshkariki/com.app.peshkariki.newPesh.newTwoAuth.NewTwoAuthActivity}: java.lang.NullPointerException: Attempt to read from field 'int androidx.constraintlayout.motion.widget.p$b.e' on a null object reference`

By trial and error, I determined that the last version on which the application did not crash due to an error is 1.3.0-alpha02

**Expected behavior:** Bug fix

**Source code:** 
Fragment
```
class StartScreenFragment : Fragment() {
    private lateinit var viewModel: StartScreenViewModel

    private lateinit var layout: MotionLayout

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return inflater.inflate(R.layout.fr_start, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        layout = view.findViewById(R.id.layout)
        viewModel =
            ViewModelProvider(this).get(StartScreenViewModel::class.java)

        initViewModel()
    }

    override fun onResume() {
        super.onResume()
        viewModel.start()
    }

    private fun initViewModel() {
        viewModel.state.observe(viewLifecycleOwner, {
            when (it) {
                is StartScreenState.START_ANIMATION -> {

                    layout.setTransition(R.id.invisibleAll, R.id.visibleOnlyLogo)
                    layout.setTransitionDuration(1000)
                    layout.transitionToEnd()
                    Log.d("State", "Start Animation")
                }
                is StartScreenState.LOADING -> {

                }
            }
        })
    }
}

```
ViewModel

```
class StartScreenViewModel: ViewModel(){

    private val _state = MutableLiveData<StartScreenState>()
    val state : LiveData<StartScreenState>
        get() = _state

    fun start() {
        _state.value = StartScreenState.START_ANIMATION
        viewModelScope.launch(Dispatchers.IO) {
            delay(1000)
        }
    }
}

```

XML
```
<androidx.constraintlayout.motion.widget.MotionLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/layout"
    app:layoutDescription="@xml/fr_start_motion_scene">

    <ImageView
        android:id="@+id/iv_logo"
        android:layout_width="120dp"
        android:layout_height="120dp"
        android:layout_marginBottom="16dp"
        android:background="@drawable/logo2"
        app:layout_constraintBottom_toTopOf="@+id/iv_subtitle"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

    <ImageView
        android:id="@+id/iv_subtitle"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:layout_marginStart="24dp"
        android:layout_marginEnd="24dp"
        android:layout_marginBottom="24dp"
        app:layout_constraintBottom_toTopOf="@+id/btn_create_user"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

    <Button
        android:id="@+id/btn_create_user"
        style="@style/Widget.MaterialComponents.Button.OutlinedButton"
        android:layout_width="match_parent"
        android:layout_height="64dp"
        android:minHeight="64dp"
        android:layout_marginStart="24dp"
        android:layout_marginEnd="24dp"
        android:text="Создать аккаунт"
        android:textAllCaps="false"
        android:textSize="18sp"
        android:fontFamily="sans-serif"
        app:layout_constraintBottom_toTopOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="parent" />

    <Button
        android:id="@+id/btn_login"
        style="@style/Widget.MaterialComponents.Button.TextButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="24dp"
        android:layout_marginEnd="24dp"
        android:textAllCaps="false"
        android:fontFamily="sans-serif"
        android:textSize="18sp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/btn_create_user"
         />

    <Button
        android:id="@+id/btn_track_order"
        style="@style/Widget.MaterialComponents.Button.TextButton"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="24dp"
        android:layout_marginEnd="24dp"
        android:layout_marginBottom="32dp"
        android:textAllCaps="false"
        android:fontFamily="sans-serif"
        android:textSize="18sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

    <Button
        android:id="@+id/btn_create_order"
        android:layout_width="match_parent"
        android:layout_height="64dp"
        android:layout_marginStart="24dp"
        android:layout_marginEnd="24dp"
        app:layout_constraintBottom_toTopOf="@id/btn_track_order"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        android:text="Создать заказ"
        android:fontFamily="sans-serif"
        android:textAllCaps="false"
        android:textSize="18sp"/>

</androidx.constraintlayout.motion.widget.MotionLayout>

```

MotionScene
```
<MotionScene xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <ConstraintSet android:id="@+id/invisibleAll">
        <Constraint
            android:id="@+id/iv_logo"
            android:layout_width="240dp"
            android:layout_height="240dp"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent" />
        <Constraint
            android:id="@id/iv_subtitle"
            android:visibility="gone">
        </Constraint>
        <Constraint
            android:id="@+id/btn_create_user"
            android:visibility="gone">
        </Constraint>
        <Constraint
            android:id="@+id/btn_login"
            android:visibility="gone">
        </Constraint>
        <Constraint
            android:id="@+id/btn_track_order"
            android:visibility="gone">
        </Constraint>
        <Constraint
            android:id="@+id/btn_create_order"
            android:visibility="gone">
        </Constraint>
    </ConstraintSet>
    <ConstraintSet android:id="@+id/visibleOnlyLogo">
        <Constraint
            android:id="@+id/iv_logo"
            android:layout_width="240dp"
            android:layout_height="240dp"
            android:background="@drawable/logo2"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent" />
        <Constraint
            android:id="@+id/iv_subtitle"
            android:visibility="gone">
        </Constraint>
        <Constraint
            android:id="@+id/btn_create_user"
            android:visibility="gone">
        </Constraint>
        <Constraint
            android:id="@+id/btn_login"
            android:visibility="gone">
        </Constraint>
        <Constraint
            android:id="@+id/btn_track_order"
            android:visibility="gone">
        </Constraint>
        <Constraint
            android:id="@+id/btn_create_order"
            android:visibility="gone">
        </Constraint>

    </ConstraintSet>

    <ConstraintSet android:id="@+id/visibleAll">
        <Constraint
            android:id="@id/iv_logo"
            android:layout_width="120dp"
            android:layout_height="120dp"
            android:layout_marginBottom="16dp"
            app:layout_constraintBottom_toTopOf="@+id/iv_subtitle"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            android:visibility="visible">
        </Constraint>

        <Constraint
            android:id="@+id/iv_subtitle"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:layout_marginStart="24dp"
            android:layout_marginEnd="24dp"
            android:layout_marginBottom="24dp"
            app:layout_constraintBottom_toTopOf="@+id/btn_create_user"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            android:visibility="visible">
        </Constraint>

        <Constraint
            android:id="@+id/btn_create_user"
            style="@style/Widget.MaterialComponents.Button.OutlinedButton"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:minHeight="64dp"
            android:layout_marginStart="24dp"
            android:layout_marginEnd="24dp"
            android:text="Создать аккаунт"
            android:textAllCaps="false"
            android:textSize="18sp"
            android:fontFamily="sans-serif"
            app:layout_constraintBottom_toTopOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="parent"
            android:visibility="visible"/>

        <Constraint
            android:id="@+id/btn_login"
            style="@style/Widget.MaterialComponents.Button.TextButton"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="24dp"
            android:layout_marginEnd="24dp"
            android:textAllCaps="false"
            android:fontFamily="sans-serif"
            android:textSize="18sp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/btn_create_user"
            android:visibility="visible"/>

        <Constraint
            android:id="@+id/btn_track_order"
            style="@style/Widget.MaterialComponents.Button.TextButton"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="24dp"
            android:layout_marginEnd="24dp"
            android:layout_marginBottom="32dp"
            android:textAllCaps="false"
            android:fontFamily="sans-serif"
            android:textSize="18sp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            android:visibility="visible"/>

        <Constraint
            android:id="@+id/btn_create_order"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="24dp"
            android:layout_marginEnd="24dp"
            app:layout_constraintBottom_toTopOf="@id/btn_track_order"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            android:text="Создать заказ"
            android:minHeight="64dp"
            android:fontFamily="sans-serif"
            android:textAllCaps="false"
            android:textSize="18sp"
            android:visibility="visible"/>

    </ConstraintSet>



</MotionScene>
```

**Android API version:** 9.0

**Material Library version:** 1.3.0-alpha03 -  1.4.0-beta01

**Device:** Xiaomi Redmi 7

I cut out all the extra stuff and put it in the repository, but this way another error comes out, but with MotionLayout'int androidx.constraintlayout.motion.widget.MotionScene$Transition.mDefaultInterpolator'

Repository: https://github.com/danilshik/Bug

**Comment by drchen** [comment]
Can you provide your full stack trace?

**Comment by danilshik** [comment]
`
java.lang.RuntimeException: Unable to resume activity {com.app.peshkariki/com.app.peshkariki.newPesh.newTwoAuth.NewTwoAuthActivity}: java.lang.NullPointerException: Attempt to read from field 'int androidx.constraintlayout.motion.widget.q$b.e' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3828)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'int androidx.constraintlayout.motion.widget.q$b.e' on a null object reference
        at androidx.constraintlayout.motion.widget.q$b.g(MotionScene.java:431)
        at androidx.constraintlayout.motion.widget.q.p(MotionScene.java:1365)
        at androidx.constraintlayout.motion.widget.MotionLayout.v(MotionLayout.java:1734)
        at androidx.constraintlayout.motion.widget.MotionLayout.U(MotionLayout.java:1773)
        at com.app.peshkariki.newPesh.newTwoAuth.startScreen.a$a.a(StartScreenFragment.kt:111)
        at com.app.peshkariki.newPesh.newTwoAuth.startScreen.a$a.invoke(StartScreenFragment.kt:28)
        at com.app.peshkariki.Fragment.base.a$b.a(BaseViewModel.kt:56)
        at com.app.peshkariki.Fragment.base.a$b.d(BaseViewModel.kt:9)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.b(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.t.setValue(MutableLiveData.java:50)
        at com.app.peshkariki.newPesh.newTwoAuth.startScreen.c.l(StartScreenViewModel.kt:18)
        at com.app.peshkariki.newPesh.newTwoAuth.startScreen.a.onResume(StartScreenFragment.kt:81)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
        at androidx.fragment.app.r.m(FragmentStateManager.java:373)
        at androidx.fragment.app.l.D0(FragmentManager.java:1199)
        at androidx.fragment.app.l.C0(FragmentManager.java:1356)
        at androidx.fragment.app.l.A0(FragmentManager.java:1434)
        at androidx.fragment.app.l.B0(FragmentManager.java:1497)
        at androidx.fragment.app.l.J(FragmentManager.java:2625)
        at androidx.fragment.app.l.H(FragmentManager.java:2589)
        at androidx.fragment.app.g.p(FragmentController.java:269)
        at androidx.fragment.app.d.onResumeFragments(FragmentActivity.java:478)
        at androidx.fragment.app.d.onPostResume(FragmentActivity.java:467)
        at androidx.appcompat.app.d.onPostResume(AppCompatActivity.java:219)
        at android.app.Activity.performResume(Activity.java:7430)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3820)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) `

**Comment by drchen** [comment]
It looks like it has nothing to do with Material library. Closing the issue...
