### ISSUE TITLE
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by jhwsx** [material-components/material-components-android#2212]
**Log**
```text
Process Name: 'cc.client'
Thread Name: 'main'
Back traces starts.
java.lang.RuntimeException: Unable to start activity ComponentInfo{cc.client/cc.client.ui.splash.SplashActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
	at com.android.base.vm.BaseActivity.onCreate(BaseActivity.java:46)
	at cc.client.ui.splash.SplashActivity.onCreate(SplashActivity.java:61)
	at android.app.Activity.performCreate(Activity.java:8086)
	at android.app.Activity.performCreate(Activity.java:8074)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
	... 11 more
Back traces ends.
```
**Description:**
My `SplashActivity` use this `SplashTheme` theme:
```xml
<style name="Theme.StepTreasure" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
</style>

<style name="SplashTheme" parent="Theme.StepTreasure.NoActionBar">
    <item name="android:windowBackground">@drawable/splash_background</item>
    <item name="android:windowFullscreen">true</item>
</style>
```
values-v21:
```xml
<style name="SplashTheme" parent="Theme.StepTreasure.NoActionBar">
    <item name="android:windowBackground">@drawable/splash_background</item>
    <item name="android:windowFullscreen">true</item>
    <item name="android:windowDrawsSystemBarBackgrounds">false</item>
    <item name="android:windowTranslucentStatus">true</item>
    <item name="android:statusBarColor">@android:color/transparent</item>
</style>
```
values-v28:
```xml
<style name="SplashTheme" parent="Theme.StepTreasure.NoActionBar">
    <item name="android:windowBackground">@drawable/splash_background</item>
    <item name="android:windowFullscreen">true</item>
    <item name="android:windowDrawsSystemBarBackgrounds">false</item>
    <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    <item name="android:windowTranslucentStatus">true</item>
    <item name="android:statusBarColor">@android:color/transparent</item>
</style>
```

On the other hand, my colleague uses this theme on other Activities in a module:
```xml
<style name="Theme.Outside.Translucent" parent="Theme.MaterialComponents.Light.NoActionBar">
    <item name="android:windowIsTranslucent">true</item>
    <item name="android:windowBackground">@android:color/transparent</item>
    <item name="android:windowActionBar">false</item>
    <item name="android:windowContentOverlay">@null</item>
    <item name="android:windowNoTitle">true</item>
    <item name="android:backgroundDimEnabled">true</item>
    <item name="android:statusBarColor">@android:color/transparent</item>
</style>
```

**Android API version:**
10

**Material Library version:** 
1.3.0

**Device:** 
HONOR HRY-AL00a

I wonder if we are using different theme results in this exception. I think so, but I cannot persuade my colleague to use `Theme.AppCompat`.

Could you please explain this for me?

**Comment by drchen** [comment]
Can you show me the definition of your Theme.StepTreasure.NoActionBar?

Theme.MaterialComponents.Light.NoActionBar is a descent of Theme.AppCompat so it should be fine.
