### ISSUE TITLE
[BadgeDrawable] Should the APP's theme must to be Theme.MaterialComponents?

### ISSUE THREAD

**Issue by johnwatsondev** [material-components/material-components-android#2248]
**Description:**
I just need use the BadgeDrawable feature in my APP.  What is the reason that my APP's theme must to be Theme.MaterialComponents? 
I really confused about this enforcement.

**Expected behavior:** 
```
     Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
        at com.google.android.material.badge.BadgeDrawable.<init>(BadgeDrawable.java:427)
        at com.google.android.material.badge.BadgeDrawable.createFromAttributes(BadgeDrawable.java:342)
        at com.google.android.material.badge.BadgeDrawable.create(BadgeDrawable.java:310)
        at com.google.android.material.navigation.NavigationBarMenuView.getOrCreateBadge(NavigationBarMenuView.java:551)
        at com.google.android.material.navigation.NavigationBarView.getOrCreateBadge(NavigationBarView.java:669)
```

**Source code:** 

XML setup
```
    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/google_material_nav"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="20dp"
        android:background="@color/white"
        app:itemHorizontalTranslationEnabled="false"
        app:itemIconTint="@color/selector_bnv"
        app:itemTextAppearanceActive="@style/BottomNavigationView.Demo.Text"
        app:itemTextAppearanceInactive="@style/BottomNavigationView.Demo.Text"
        app:labelVisibilityMode="labeled"
        app:menu="@menu/bottom_nav_menu" />
```

Java setup
```
    private fun setupBadge(bn: com.google.android.material.bottomnavigation.BottomNavigationView) {
        var menuItemId = bn.menu.getItem(0).itemId
        // An icon only badge will be displayed.
        var badge = bn.getOrCreateBadge(menuItemId)
        badge.isVisible = true
    }
```

APP's Theme
```
    <style name="Theme.Demo" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryDark">@color/purple_700</item>
        <item name="colorAccent">@color/teal_200</item>
    </style>
```

**Android API version:**
ANDROID_COMPILE_SDK=30
ANDROID_MIN_SDK=14
ANDROID_TARGET_SDK=29

**Material Library version:**
1.4.0-alpha02

**Device:**
Google Pixel 4 XL

**Comment by drchen** [comment]
The badge implementation is using attributes only defined in material themes. 

If you are not using material themes, it may not work correctly.
