### ISSUE TITLE
[Slider] IllegalStateException on Huawei (Android 9)

### ISSUE THREAD

**Issue by vaidadry** [material-components/material-components-android#2272]
We keep experiencing IllegalStateException, but only on Huawei devices and only Android 9. When using another device on same user account, no crashes occur. Current version `1.4.0-beta01`

```
Fatal Exception: java.lang.IllegalStateException: Value(475.0) must be equal to valueFrom(100.0) plus a multiple of stepSize(100.0) when using stepSize(100.0)
       at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:553)
       at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:587)
       at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1521)
       at android.view.View.draw(View.java:20483)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.draw(View.java:20486)
       at android.widget.ScrollView.draw(ScrollView.java:1790)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.draw(View.java:20486)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.draw(View.java:20486)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.updateDisplayListIfDirty(View.java:19285)
       at android.view.View.draw(View.java:20211)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
       at android.view.View.draw(View.java:20486)
       at com.android.internal.policy.DecorView.draw(DecorView.java:928)
       at android.view.View.updateDisplayListIfDirty(View.java:19294)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:740)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:746)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3586)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3382)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2714)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:812)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by drchen** [comment]
Can you provide your settings? 

The exception message seems clear:
Fatal Exception: java.lang.IllegalStateException: Value(475.0) must be equal to valueFrom(100.0) plus a multiple of stepSize(100.0) when using stepSize(100.0)

I would suggest you debug on your end first and check if the situation is reproducible. : )

**Comment by drchen** [comment]
Closing the bug for now until we have further info.
