### ISSUE TITLE
> I'm OK with submitting PR and add callback null check in`CircularIndeterminateAnimatorDelegate`, but I'm not sure if this going to break some logic behind.

### ISSUE THREAD

**Issue by Jaydipnathani** [material-components/material-components-android#2278]
> I'm OK with submitting PR and add callback null check in`CircularIndeterminateAnimatorDelegate`, but I'm not sure if this going to break some logic behind.

> Fixed with [f732070](https://github.com/material-components/material-components-android/commit/f732070619797d8af5fa5ac0ab535ad8dd59d420)

Please tell me
 Which Version fix this issue ?

_Originally posted by @Jaydipnathani in https://github.com/material-components/material-components-android/issues/2251#issuecomment-868952383_

**Comment by drchen** [comment]
Please see reply in the original issue.

**Comment by Jaydipnathani** [comment]
> Please see reply in the original issue.

This Issue not resolve in version 1.4.0

'com.google.android.material:material:1.4.0'

please fix this problem Is it generate every 

> time` java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.vectordrawable.graphics.drawable.Animatable2Compat$AnimationCallback.onAnimationEnd(android.graphics.drawable.Drawable)' on a null object reference
        at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate$2.onAnimationEnd(CircularIndeterminateAnimatorDelegate.java:112)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1233)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1475)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1007)
        at android.view.Choreographer.doCallbacks(Choreographer.java:821)
        at android.view.Choreographer.doFrame(Choreographer.java:753)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`
