### ISSUE TITLE
[CircularProgressIndicator] Crash in CircularProgressIndicator

### ISSUE THREAD

**Issue by FitApps7** [material-components/material-components-android#2324]
I am getting crash report from firebase

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void e.z.a.a.b.a(android.graphics.drawable.Drawable)' on a null object reference
       at com.google.android.material.progressindicator.CircularIndeterminateAnimatorDelegate$2.onAnimationEnd(CircularIndeterminateAnimatorDelegate.java:112)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1242)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1484)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:725)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

This crash on android 10 and 11 mostly.

material library version = '1.4.0'

**Devices:** Galaxy A30, Galaxy J4, Galaxy A20s, Galaxy A01, Galaxy A20, Galaxy A51, Galaxy A41, Moto G (3rd Gen), moto e(7), Redmi 9 Power

**Comment by matpag** [comment]
You should post a fully de-obfuscated stack trace, `e.z.a.a.b.a` is obfuscated

**Comment by pekingme** [comment]
@FitApps7 I believe it's fixed in f732070, which is just checked in 1.5.0-alpha01.
Duplicated with #2278

**Comment by FitApps7** [comment]
thanks
