### ISSUE TITLE
[MaterialTimePicker] Crash on inflate picker

### ISSUE THREAD

**Issue by DemiN0u** [material-components/material-components-android#2339]
**Description:** 
I tried to add time picker to my project but it got crashed each time when i try to call it whatever params i set. I've try run it on `1.4.0` and `1.5.0-alpha02` versions.

After some investigation I found that crash appears when my app theme is extended from ```Theme.MaterialComponents.Light.DarkActionBar.Bridge``` and works good for ```Theme.MaterialComponents.Light.DarkActionBar```

**Expected behavior:** Time picker dialog is appeared on screen.

**Source code:** 
```
MaterialTimePicker picker = new MaterialTimePicker.Builder()
                .setTitleText(question.getText())
                .setHour(0)
                .setMinute(0)
                .setTimeFormat(TimeFormat.CLOCK_12H)
                .setInputMode(MaterialTimePicker.INPUT_MODE_KEYBOARD)
                .build();
        picker.addOnPositiveButtonClickListener(v -> processTimeFormat(picker.getHour(), picker.getMinute()));
        picker.show(getFragmentManager(), "time_picker_dialog");
```

Styles:
```
<style name="AppThemeInspection" parent="Theme.MaterialComponents.Light.DarkActionBar.Bridge">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimaryInspection</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDarkInspection</item>
        <item name="colorAccent">@color/colorAccentInspection</item>
        <item name="materialCalendarTheme">@style/ThemeOverlay.MaterialComponents.MaterialCalendar</item>
        <item name="materialTimePickerTheme">@style/ThemeOverlay.MaterialComponents.TimePicker</item>
</style>
```

**Android API version:** 31(Android 12 Beta 4)

**Material Library version:** 1.4.0

**Device:** Pixel 3a XL

`android.view.InflateException: Binary XML file line #80 in com.inspection.driveroo.launch:layout/material_timepicker_dialog: Binary XML file line #80 in com.inspection.driveroo.launch:layout/material_timepicker_dialog: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #80 in com.inspection.driveroo.launch:layout/material_timepicker_dialog: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at com.google.android.material.timepicker.MaterialTimePicker.onCreateView(MaterialTimePicker.java:214)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7822)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 36: TypedValue{t=0x2/d=0x7f0402f7 a=9}
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:783)
        at android.view.View.<init>(View.java:5788)
        at android.widget.TextView.<init>(TextView.java:1032)
        at android.widget.Button.<init>(Button.java:166)
        at android.widget.Button.<init>(Button.java:141)
        at androidx.appcompat.widget.AppCompatButton.<init>(AppCompatButton.java:74)
        at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:224)
        at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:220)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:858) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485) 
        at com.google.android.material.timepicker.MaterialTimePicker.onCreateView(MaterialTimePicker.java:214) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356) 
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447) 
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849) 
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7822) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) `

**Comment by drchen** [comment]
Hi, bridge themes are meant to support AppCompat components with Material styles. MaterialTimePicker is a Material component so you will need to use a full theme (for example, Theme.MaterialComponents.Light.DarkActionBar) to provide necessary theme attributes required by the component.
