### ISSUE TITLE
BottomAppBar Android P  ;  Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by NW0LC** [material-components/material-components-android#235]
com.google.android.material:material:1.1.0-alpha01

**Comment by douo** [comment]
Same ISSUE
Device: Pixel 2 
OS: Android 9
IDE: Android Studio 3.4 C5

Even in android studio layout preview:

```
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
	at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
	at android.graphics.Canvas.clipRect(Canvas.java:826)
	at com.google.android.material.shape.MaterialShapeDrawable.prepareCanvasForShadow(MaterialShapeDrawable.java:850)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:746)
	at android.view.View.drawBackground(View.java:20412)
	at android.view.View.draw_Original(View.java:20198)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:20177)
	at android.view.View.draw_Original(View.java:20077)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:67)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20075)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:67)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20075)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:67)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20210)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:20177)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:403)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:555)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:424)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:120)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:151)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:133)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$8(RenderTask.java:744)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Gericop** [comment]
Happens in the API 28 emulator, too.

**Comment by NW0LC** [comment]
androidx




------------------ 原始邮件 ------------------
发件人: "ldjcmu"<notifications@github.com>;
发送时间: 2018年11月29日(星期四) 晚上11:25
收件人: "material-components/material-components-android"<material-components-android@noreply.github.com>;
抄送: "「T」还不够好"<704796146@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [material-components/material-components-android] BottomAppBarAndroid P  ;  Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed(#235)




Can you provide a small code/layout sample, so we can understand how this might be happening? BottomAppBar works for me on P, so some setup difference is causing the issue; anything you can provide to help us track it down would be great.

**Comment by 9and3r** [comment]
I also have this problem with 1.1.0-alpha01 version and Android P.

The issue seems to be the same as [https://issuetracker.google.com/issues/118921801](https://issuetracker.google.com/issues/118921801). According to that link this was fixed in [this commit](https://www.google.com/url?q=https://github.com/material-components/material-components-android/commit/3d8e2b408c28ad9426128cc6205a41edd3f827c0&sa=D&usg=AFQjCNHAig98UpYtyFej6DeU_M4qvPDlvg).

**Comment by milanPansuriya** [comment]
Still, I am facing this issue 
Device Nokia 7+
OS: Pie 
Android Studio Version: 3.2.1
Lib version:  implementation 'com.google.android.material:material:1.1.0-alpha01'


E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wmt.androidxsupport, PID: 4156
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.google.android.material.shape.MaterialShapeDrawable.prepareCanvasForShadow(MaterialShapeDrawable.java:850)
        at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:746)
        at android.view.View.getDrawableRenderNode(View.java:20463)
        at android.view.View.drawBackground(View.java:20399)
        at android.view.View.draw(View.java:20198)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ldjcmu** [comment]
@milanPansuriya Yes, you will see this issue with that version. The presumed fix is not in a release (alpha or otherwise) yet.

**Comment by calmmycode** [comment]
Same problem here on Pixel 1 gen Android P. But on Huawei P20 pro Android 8.1 no problems.

**Comment by cketcham** [comment]
1.0.0-alpha02 will be released soon and has a fix for this.

**Comment by Superblazer** [comment]
This was an unexpected end.
