### ISSUE TITLE
[TextView & AppBarLayout (maybe more)] Material3 crash with light theme

### ISSUE THREAD

**Issue by Jolanrensen** [material-components/material-components-android#2370]
**Description:** 
Using a theme with `Theme.Material3.DayNight.NoActionBar` as parent, my app crashes when running a light theme. The dark theme works fine. Here are parts of the stack trace regarding the AppBarLayout:
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.jolanrensen.widgetscreensaver/nl.jolanrensen.widgetscreensaver.SettingsActivity}: android.view.InflateException: Binary XML file line #16 in nl.jolanrensen.widgetscreensaver:layout/activity_settings: Binary XML file line #16 in nl.jolanrensen.widgetscreensaver:layout/activity_settings: Error inflating class com.google.android.material.appbar.AppBarLayout
...
Caused by: android.view.InflateException: Binary XML file line #16 in nl.jolanrensen.widgetscreensaver:layout/activity_settings: Binary XML file line #16 in nl.jolanrensen.widgetscreensaver:layout/activity_settings: Error inflating class com.google.android.material.appbar.AppBarLayout
     Caused by: android.view.InflateException: Binary XML file line #16 in nl.jolanrensen.widgetscreensaver:layout/activity_settings: Error inflating class com.google.android.material.appbar.AppBarLayout
     Caused by: java.lang.reflect.InvocationTargetException
...
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0300f1 a=10}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:998)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:982)
        at android.view.View.<init>(View.java:5520)
        at android.view.ViewGroup.<init>(ViewGroup.java:702)
        at android.widget.LinearLayout.<init>(LinearLayout.java:254)
        at android.widget.LinearLayout.<init>(LinearLayout.java:250)
        at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:215)
        at com.google.android.material.appbar.AppBarLayout.<init>(AppBarLayout.java:211)
```

If I take out the AppBarLayout from the project, the app simply crashes on the next TextView:
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.jolanrensen.widgetscreensaver/nl.jolanrensen.widgetscreensaver.SettingsActivity}: android.view.InflateException: Binary XML file line #65 in nl.jolanrensen.widgetscreensaver:layout/activity_settings: Binary XML file line #38 in nl.jolanrensen.widgetscreensaver:layout/content_settings: Error inflating class TextView
...
 Caused by: android.view.InflateException: Binary XML file line #65 in nl.jolanrensen.widgetscreensaver:layout/activity_settings: Binary XML file line #38 in nl.jolanrensen.widgetscreensaver:layout/content_settings: Error inflating class TextView
     Caused by: android.view.InflateException: Binary XML file line #38 in nl.jolanrensen.widgetscreensaver:layout/content_settings: Error inflating class TextView
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:598)
        at android.widget.TextView.readTextAppearance(TextView.java:4062)
        at android.widget.TextView.<init>(TextView.java:1088)
        at android.widget.TextView.<init>(TextView.java:1026)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:108)
        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:93)
        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:88)
        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:83)
        at com.google.android.material.theme.MaterialComponentsViewInflater.createTextView(MaterialComponentsViewInflater.java:61)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:121)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1570)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1621)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
```

It looks like there is an attribute somewhere, that only exists in the light theme, which both TextView and AppBarLayout use, that can't be read or found somehow.

**Expected behavior:**
There shouldn't be a crash.

**Source code:** 
My app does use ViewBinding if that could be the cause of the issue. Other than that I use a simple AppBarLayout:
```xml
<com.google.android.material.appbar.AppBarLayout
    android:id="@+id/appbar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent">

    <com.google.android.material.appbar.MaterialToolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:transitionName="toolbar">

        <include
            android:id="@+id/activity_settings_toolbar_content"
            layout="@layout/activity_settings_toolbar_content" />

    </com.google.android.material.appbar.MaterialToolbar>
</com.google.android.material.appbar.AppBarLayout>
```
and TextView:
```xml
<TextView
    android:id="@+id/orientation_text"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:text="@string/orientation"
    android:textAppearance="@style/TextAppearance.AppCompat.Body1"
    android:textColor="?attr/colorOnSurface"
    android:textSize="14sp"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintEnd_toStartOf="@id/guideline5"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent" />
```

My main theme is based on MaterialThemeBuilder, with the parent theme being replaced with `Theme.Material3.DayNight.NoActionBar`

**Android API version:** 31

**Material Library version:** 1.5.0-alpha03

**Device:** Pixel 4XL: Android 12 beta 5

**Comment by Jolanrensen** [comment]
What I found out is that adding all types of text appearances manually solves the issue for now

**Comment by drchen** [comment]
Hi @Jolanrensen, thanks for the update. It might be resulted from the out-of-sync state between themes and styles during development. 

Can you provide more info about what text appearances you added manually to solve the issue so we can confirm that is the case? Thank you very much!!

**Comment by Jolanrensen** [comment]
First of all I added the Material You dynamic colors with a theme overlay in every activity using `android:theme`. 
```xml
<style name="ThemeOverlayDynamicColors" parent="ThemeOverlay.Material3.DynamicColors.DayNight">
        <!--Material You colors-->
</style>
```

This shifted the issue from the AppBarLayout and TextView to some Buttons and TextInputLayout where the error told me to look at missing text appearances. It might actually be the case that adding the dynamic colors fixed the first problem and that this other problem is another one, but anyways. For the Buttons I added ` android:textAppearance="@style/TextAppearance.Material3.LabelLarge"` manually and for the TextInputLayouts I had to add all text appearance occurrences:
```
android:textAppearance="@style/TextAppearance.Material3.BodyLarge"
app:counterTextAppearance="@style/TextAppearance.Material3.BodyLarge"
app:counterOverflowTextAppearance="@style/TextAppearance.Material3.BodyLarge"
app:errorTextAppearance="@style/TextAppearance.Material3.BodyLarge"
app:helperTextTextAppearance="@style/TextAppearance.Material3.BodyLarge"
app:hintTextAppearance="@style/TextAppearance.Material3.BodyLarge"
app:placeholderTextAppearance="@style/TextAppearance.Material3.BodyLarge"
app:prefixTextAppearance="@style/TextAppearance.Material3.BodyLarge"
```

The menus look a bit weird now (small text), but at least the app doesn't crash anymore

**Comment by drchen** [comment]
Hmm... can you use Theme.Material3.DayNight.NoActionBar or your custom themes inheriting it as the activities' android:theme instead, and see if that fixes your issue?

Dynamic color theme overlays are meant to be used as "overlays" over the regular M3 themes so they don't declare all theme attributes that may be required by component styles. 

The right/recommended way to apply dynamic colors is using DynamicColors.applyToActivitiesIfAvailable() method in your application class' onCreate() method. 

Please read the javadoc of the method to get more details:
https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/color/DynamicColors.java#L62

**Comment by Jolanrensen** [comment]
> Hmm... can you use Theme.Material3.DayNight.NoActionBar or your custom themes inheriting it as the activities' android:theme instead, and see if that fixes your issue?
> 
> Dynamic color theme overlays are meant to be used as "overlays" over the regular M3 themes so they don't declare all theme attributes that may be required by component styles.
> 
> The right/recommended way to apply dynamic colors is using DynamicColors.applyToActivitiesIfAvailable() method in your application class' onCreate() method.
> 
> Please read the javadoc of the method to get more details:
> https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/color/DynamicColors.java#L62

Nope, doing that (so adding `android:theme="@style/AppTheme"` (which inherits `Theme.Material3.DayNight.NoActionBar`) to each activity's layout file) crashes again on the first AppBarLayout in the light mode only.

**Comment by drchen** [comment]
What do you mean by "convert the old material theme builder to the material3 attributes"?

If you just use Theme.Material3.DayNight.NoActionBar plainly as your activity themes, will that crash?

**Comment by Jolanrensen** [comment]
Well the material theme builder doesn't yet produce colorPrimaryContainer and colorTertiary, right? So for people using older than android-12 versions I created those colors in the theme myself. That's what I meant by converting. I'm not sure if there's an easier way, since there aren't any guides yet.

I'll try that tomorrow when I have time and report back!

**Comment by Jolanrensen** [comment]
@drchen Yes, applying `Theme.Material3.DayNight.NoActionBar` as theme to every layout file in my app makes it so it doesn't crash! However, the `DynamicColors.applyToActivitiesIfAvailable(application)` now doesn't seem to do anything anymore (and of course, my theme colors don't work anymore for below android 12 versions). Does that mean that the issue lies in my theme specifically?

**Comment by drchen** [comment]
Did you set android:theme="@style/AppTheme" in your AndroidManifest.xml? 

You can set it under <application> (which applies it to the whole application) or <activity> (for a specific activity) tags, both of which should work with dynamic colors.

If you didn't set it in your AndroidManifest.xml, this might be the reason of the crash because application/activity level context doesn't have certain theme attributes defined.

**Comment by Jolanrensen** [comment]
@drchen yes I did. Both in the <application tag and in the <activity tags. Removing or adding it doesn't make any difference to the situation unfortunately

**Comment by drchen** [comment]
I'm wondering if you are overriding the theme inheritance anywhere in your night resources folders?

It's hard to make a guess out of all the info I got so far (but still thanks for trying!!). If applying Material3 theme to the view fix the crash, that means either:

1. Your app theme or activity theme may not be correctly applied to your views. Can you check that by log context.getTheme() when the problematic view is created and see if it points to the right theme? Or
2. You somehow override the theme inheritance in the light mode. So I suggest you try to set "Theme.Material3.DayNight.NoActionBar" as your app theme or activity theme and see if it works. If that's not possible because you need certain theme attributes, then I'll suggest you to create some minimal and clean theme to test if it works.

Let me know how it's going. : )

**Comment by Jolanrensen** [comment]
I did find something curious. If I give my activity the theme `android:theme="@style/Base.Theme.MyApp"` (as defined a couple of comments above, and only defined in the normal values), the app doesn't crash, but if I use `android:theme="@style/AppTheme"` (which, as can be seen only has that other theme as parent in the light theme, but also exists in night, v21, and v26 values) it crashes. Could values-v26 etc have any influence if I run it on an sdk 31 device? Or is there somehow getting more data into AppTheme, even when it doesn't have any items?
I'll try your tips next! Thanks for all your help :)

**Comment by drchen** [comment]
Yeah it absolutely... does. Anything defined in values-v26 will be applied to any sdk 26+. : )

**Comment by Jolanrensen** [comment]
I think I figured it out... In the values-v26 etc I didn't inherit from Base.Theme.MyApp, but from another Material Components theme. Since those values influence the new ones, I essentially had two different parent themes, a Material Components and a Material3 theme. Thanks for your help!
One last question:
How's the backwards compatibility for Material3 btw? I noticed for another app of mine that on android 7 colors and rendering was all over the place using a Material3 theme. Should I wait for AppCompat to support Material3 or is there already a guide on how to handle this?

**Comment by drchen** [comment]
Glad to hear you found the root cause!!

Material 3 should work without too much extra efforts if you are already using Material themes. 
We deprecate certain color roles, like colorPrimaryDark, so if you are customizing it somewhere in your app, you may want to double check if the new look and feel still serves your need.

We don't have an official migration guide yet. But we will probably have it when Material 3 is officially released. (The est. timeline is around Oct.)

Material library is more or less based on AppCompat, so in theory there won't be compatibility issues between them. Let me know if this answers your concern. : )
