### ISSUE TITLE
[TextField] Crash during fragment recreaton

### ISSUE THREAD

**Issue by ryandt** [material-components/material-components-android#2462]
**Description:** 
Hey there. I work on an app that supports multiple languages in app settings. When navigating to a screen with a `com.google.android.material.textfield.TextInputLayout` and then subsequently changing the app's language (specific language doesn't seem to matter), when the Fragment that contains the `TextInputLayout` is reloaded via `onCreateView()`, the app crashes with the following log output:
```
E/AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #29 in com.myapp.android.beta:layout/design_text_input_end_icon: Binary XML file line #29 in com.myapp.android.beta:layout/design_text_input_end_icon: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #29 in com.myapp.android.beta:layout/design_text_input_end_icon: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:613)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:428)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.myapp.android.style.views.SelectDropdown.<init>(CollageSelectDropdown.kt:40)
        at com.myapp.android.style.views.SelectDropdown.<init>(CollageSelectDropdown.kt:23)
        at com.myapp.android.style.views.SelectDropdown.<init>(Unknown Source:11)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.etsy.android.ui.core.listingnomapper.ListingFragmentNoMapper.onCreateView(ListingFragmentNoMapper.java:711)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
2021-11-05 14:15:30.398 11421-11421/com.etsy.android.beta E/AndroidRuntime:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f040002 a=-1}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:998)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:982)
        at android.view.View.<init>(View.java:5520)
        at android.widget.ImageView.<init>(ImageView.java:195)
        at android.widget.ImageButton.<init>(ImageButton.java:86)
        at android.widget.ImageButton.<init>(ImageButton.java:82)
        at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:75)
        at com.google.android.material.internal.CheckableImageButton.<init>(CheckableImageButton.java:56)
        at com.google.android.material.internal.CheckableImageButton.<init>(CheckableImageButton.java:52)
```

**Expected behavior:**
No crash occurs

**Source code:**
The suspected `TextInputLayout`:
```
<com.google.android.material.textfield.TextInputLayout
    android:id="@+id/select_layout"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:layout_marginTop="@dimen/clg_space_4"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@id/select_label">

    <AutoCompleteTextView
        android:id="@+id/select_input"
        style="@style/select_text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

</com.google.android.material.textfield.TextInputLayout>
```

**Android API version:** 
Android 12

**Material Library version:** 
Reproduced on 1.4.0 and 1.5.0-alpha02

**Device:** 
Pixel 5

**Comment by drchen** [comment]
Hi, I can't reproduce the issue on my end. Can you provide a minimal example app to reproduce the issue?

**Comment by ryandt** [comment]
Yes I can work on building a sample app for this. It's unfortunately a bit involved, so it will take some time. Hoping to find some time for this sometime this week.

**Comment by drchen** [comment]
Any updates? Is this still an issue?

**Comment by ryandt** [comment]
Hey @drchen. I actually just found a workaround for this yesterday. The app code that triggered this crash in the Material Library was unconventional enough to where I don't feel confident in saying that this is a Material bug. Closing this issue.

**Comment by sagar15795** [comment]
@ryandt I am also facing same issue. Have you resolved this issue?

**Comment by ryandt** [comment]
@sagar15795 Unfortunately I couldn't come up with an easy way to reproduce this crash outside of my project. I ended up adding a workaround in my project in a way where `TextField` no longer gets restored with a new locale.
