### ISSUE TITLE
[MaterialTimePicker] NullPointerException on MaterialTimePicker.initializeOrRetrieveActivePresenterForMode method

### ISSUE THREAD

**Issue by josechagas** [material-components/material-components-android#2482]
**Description:** A few days ago Firebase reported the error:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.timepicker.TimePickerView.addOnRotateListener(com.google.android.material.timepicker.ClockHandView$OnRotateListener)' on a null object reference
       at com.google.android.material.timepicker.TimePickerClockPresenter.initialize(TimePickerClockPresenter.java:78)
       at com.google.android.material.timepicker.TimePickerClockPresenter.<init>(TimePickerClockPresenter.java:69)
       at com.google.android.material.timepicker.MaterialTimePicker.initializeOrRetrieveActivePresenterForMode(MaterialTimePicker.java:311)
       at com.google.android.material.timepicker.MaterialTimePicker.updateInputMode(MaterialTimePicker.java:301)
       at com.google.android.material.timepicker.MaterialTimePicker.access$700(MaterialTimePicker.java:59)
       at com.google.android.material.timepicker.MaterialTimePicker$4.onClick(MaterialTimePicker.java:263)
       at android.view.View.performClick(View.java:6608)
       at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
       at android.view.View.performClickInternal(View.java:6585)
       at android.view.View.access$3100(View.java:785)
       at android.view.View$PerformClick.run(View.java:25921)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

```
Firebase reported this error for only once during 90 days

**OBS**: I could not reproduce the error

**Expected behavior:** Screenshots and/or description of expected behavior

**Source code:** I searched on my app for usages of MaterialTimePicker and I found only one

```
fun showTimePickerFor(fragmentManager: FragmentManager, date:Date?, completion: (Date) -> Unit) {
            val dateCalendar = Calendar.getInstance()
            date?.let {
                dateCalendar.time = it
            }
            val hour = dateCalendar.get(Calendar.HOUR_OF_DAY)
            val min = dateCalendar.get(Calendar.MINUTE)
            val timePicker = MaterialTimePicker.Builder()
                .setTimeFormat(TimeFormat.CLOCK_24H)
                .setHour(hour)
                .setMinute(min)
                .setTitleText(R.string.start_when)
                .build()
            timePicker.addOnPositiveButtonClickListener {
                dateCalendar.set(Calendar.HOUR_OF_DAY, timePicker.hour)
                dateCalendar.set(Calendar.MINUTE, timePicker.minute)
                completion(dateCalendar.time)
            }
            timePicker.show(fragmentManager,null)
}
```

**Android API version:** 28

**Material Library version:** 1.4.0

**Device:** Redmi Note 7

**Comment by drchen** [comment]
I think this issue has already been fixed. Please update your Material library version and check again.
