### ISSUE TITLE
[BottomNavigationView] IllegalArgumentException in preview mode

### ISSUE THREAD

**Issue by illuzor** [material-components/material-components-android#2489]
**Description:**
After update from 1.4.0 to 1.5.0 or 1.6.0 BottomNavigationView can`t be displayed in ide editor.
![image](https://user-images.githubusercontent.com/1530314/144483711-75b937ed-a7ff-42c3-be7d-b2cc78d71059.png)

**Expected behavior:** Display without exception

**Source code:** 
-

**Android API version:** 30,31

**Material Library version:** 
1.6.0-alpha01

**Device:**
Android Studio layout editor

**Stacktrace:**
```
java.lang.IllegalArgumentException: Motion easing theme attribute must be a string
	at com.google.android.material.motion.MotionUtils.resolveThemeInterpolator(MotionUtils.java:59)
	at com.google.android.material.navigation.NavigationBarMenuView.<init>(NavigationBarMenuView.java:121)
	at com.google.android.material.bottomnavigation.BottomNavigationMenuView.<init>(BottomNavigationMenuView.java:48)
	at com.google.android.material.bottomnavigation.BottomNavigationView.createNavigationBarMenuView(BottomNavigationView.java:215)
	at com.google.android.material.navigation.NavigationBarView.<init>(NavigationBarView.java:162)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:108)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:103)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:98)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:399)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:189)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:147)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:303)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1121)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1095)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:353)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:431)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:714)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$7(RenderTask.java:870)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run(RenderExecutor.kt:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by GordonHuangYong** [comment]
???
bug still happen
