### ISSUE TITLE
[TextInputLayout] Render problem 1.6.0-alpha01

### ISSUE THREAD

**Issue by Gizmodo** [material-components/material-components-android#2507]
**Description:** 
I am facing a crash at TextInputLayout after update my Material Android Library to version 1.6.0-alpha01 from 1.5.0-rc01.
**Expected behavior:**
1.5 - Render good:
![1 5](https://user-images.githubusercontent.com/1078610/146993767-a18967d9-3a6c-4f17-a03c-4a2ce33e5ccc.png)

1.6 - Render problem:
![1 6](https://user-images.githubusercontent.com/1078610/146993770-e4bc7ed2-f839-4acf-9bdd-66e6e45edadb.png)

**Source code:** 

***Font used***
[Google Inter Regular](https://fonts.google.com/specimen/Inter)

***theme.xml***
```
<style name="Theme.FragmentVM" parent="Theme.Material3.Light.NoActionBar">
```
***header.xml***
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <TextView
        android:id="@+id/textView"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="108dp"
        android:fontFamily="@font/inter"
        android:gravity="center_horizontal"
        android:text="@string/app_name"
        android:textColor="@color/md_theme_light_primary"
        android:textSize="36sp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>
```

***main_layout.xml***
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.LoginFragment">

    <include
        android:id="@+id/include"
        layout="@layout/header"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/tilEmail"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="64dp"
        android:layout_marginEnd="64dp"
        android:layout_marginBottom="8dp"
        android:hint="@string/email"
        app:layout_constraintBottom_toTopOf="@id/tilDescription"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/include"
        app:layout_constraintVertical_chainStyle="packed">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/edtEmail"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textEmailAddress" />
    </com.google.android.material.textfield.TextInputLayout>

    <com.google.android.material.textfield.TextInputLayout
        android:id="@+id/tilDescription"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="64dp"
        android:layout_marginEnd="64dp"
        android:layout_marginBottom="8dp"
        android:hint="@string/description"
        app:layout_constraintBottom_toTopOf="@id/btnLogin"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/tilEmail"
        app:layout_constraintVertical_chainStyle="packed">

        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/edtDescription"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="text" />
    </com.google.android.material.textfield.TextInputLayout>

    <Button
        android:id="@+id/btnLogin"
        android:layout_width="0dp"
        android:layout_height="50dp"
        android:layout_marginStart="40dp"
        android:layout_marginEnd="40dp"
        android:layout_marginBottom="40dp"
        android:text="@string/btnNext"
        app:icon="@drawable/ic_arrow"
        app:iconGravity="end"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```
**Android API version:** 31

**Material Library version:** Material Android Library version 1.6.0-alpha01

**Device:** Emulator

**Render propblem**
```
java.lang.IllegalArgumentException: weight is out of range of [0, 1000] (too low) 
at com.android.internal.util.Preconditions.checkArgumentInRange(Preconditions.java:527) 
at android.graphics.Typeface.create_Original(Typeface.java:979) 
at android.graphics.Typeface_Delegate.create(Typeface_Delegate.java:123) 
at android.graphics.Typeface.create(Typeface.java:979) 
at com.google.android.material.internal.CollapsingTextHelper.maybeCloneWithAdjustment(CollapsingTextHelper.java:525) 
at com.google.android.material.internal.CollapsingTextHelper.setCollapsedTypefaceInternal(CollapsingTextHelper.java:468) 
at com.google.android.material.internal.CollapsingTextHelper.setTypefaces(CollapsingTextHelper.java:452) 
at com.google.android.material.textfield.TextInputLayout.setEditText(TextInputLayout.java:1457) 
at com.google.android.material.textfield.TextInputLayout.addView(TextInputLayout.java:878) 
at android.view.ViewGroup.addView(ViewGroup.java:5048) 
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1131) 
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101) 
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088) 
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130) 
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101) 
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:686) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:505) 
Tip: Try to refresh the layout. 
```

**Comment by dsn5ft** [comment]
@veganafro this looks related to the bold text changes

**Comment by hoc081098** [comment]
Same issue with version `1.6.0-alpha02`

**Comment by drchen** [comment]
It's fixed by https://github.com/material-components/material-components-android/commit/5dce006a5c1649df4eb6631c85619017728726af
