### ISSUE TITLE
[TextInputLayout] Preview: LinearLayout cannot be cast to class TextInputLayout

### ISSUE THREAD

**Issue by eygraber** [material-components/material-components-android#2530]
I have a custom view that uses `TextInputLayout`. The following code results in the following error in Android Studio's preview. Running the code doesn't have a problem:

```
class TimeInputView @JvmOverloads constructor(
  context: Context,
  attrs: AttributeSet? = null
) : ConstraintLayout(context, attrs) {
  ...
  private val hourContainerView: TextInputLayout
  ...
  init {
    ..
    hourContainerView = findViewById(R.id.hourContainer)
    ..
  }
  ...
}
```

```
java.lang.ClassCastException: class android.widget.LinearLayout cannot be cast to class com.google.android.material.textfield.TextInputLayout (android.widget.LinearLayout is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @117a8e11; com.google.android.material.textfield.TextInputLayout is in unnamed module of loader org.jetbrains.android.uipreview.ModuleClassLoader @67f5f66)
	at com.eygraber.date_time_input.xml.TimeInputView.<init>(TimeInputView.kt:128)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:336)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:173)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:133)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:301)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:363)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:739)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$8(RenderTask.java:895)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run(RenderExecutor.kt:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by simunde** [comment]
Can I work on the issue ??

**Comment by drchen** [comment]
Absolutely! We are happy to accept PRs! : )

**Comment by drchen** [comment]
With a second look I don't think it looks like a Material library issue. I'll close the issue for now. If you still think it's a library issue please provide your layout file and reopen the issue.
