### ISSUE TITLE
[MaterialCardView] NPE on API <=  28 (Android 9) when applying setOnClickListener

### ISSUE THREAD

**Issue by AgnaldoNP** [material-components/material-components-android#2554]
**Description:** 
When I try to apply setOnClickListener to a MaterialCardView it is throwing a NullPointerException 

**Expected behavior:** 
The application must not throw an NPE

**Source code:**
Just inflate a MaterialCardView and apply setOnClickListener on it.
```xml
        <com.google.android.material.card.MaterialCardView
            android:id="@+id/mcdTest"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_constraintTop_toTopOf="parent">

            <androidx.appcompat.widget.AppCompatImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:srcCompat="@drawable/ic_attendance" />

        </com.google.android.material.card.MaterialCardView>

```
```kotlin
     mcvTest.setOnClickListener {  }
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample/com.sample.ui.AccessActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3122)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
        at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:141)
        at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:119)
        at com.google.android.material.card.MaterialCardViewHelper.getClickableForeground(MaterialCardViewHelper.java:634)
        at com.google.android.material.card.MaterialCardViewHelper.updateClickable(MaterialCardViewHelper.java:274)
        at com.google.android.material.card.MaterialCardView.setClickable(MaterialCardView.java:365)
        at android.view.View.setOnClickListener(View.java:6408)
        at com.sample.ui.AccessActivity.initUI(AccessActivity.kt:124)
```

**Android API version:**  target 31, min 23

**Material Library version:** 1.5.0-alpha02, 1.5.0, 1.6.0-alpha02 

**Device:** 
Moto Z3 - Android 9 and 

**Emulators: **
Error:  Androids 7.1, 8, 9
Normal:  Androids 10, 11 and 12

**Comment by drchen** [comment]
It's been fixed in https://github.com/material-components/material-components-android/commit/b4cab87015fa29e23460f4f47d4d06adfe3a9e9a
