### ISSUE TITLE
[Slider] The stepSize(1.0) must be 0, or a factor of the valueFrom(0.5)-valueTo(10.0) range

### ISSUE THREAD

**Issue by h6ah4i** [material-components/material-components-android#2590]
**Description:**

Recently, I got a crash report sent to Crashlytics. It seems a few users suffering from this strange issue.

The state of the Slider settings I can read from the error message looks like completely valid, and `validateStepSize` should never be failed though.

<details> 
<summary>
(Click here to display the full stacktrace)

```
Fatal Exception: java.lang.IllegalStateException: The stepSize(1.0) must be 0, or a factor of the valueFrom(0.5)-valueTo(10.0) range
```

</summary>

```
Fatal Exception: java.lang.IllegalStateException: The stepSize(1.0) must be 0, or a factor of the valueFrom(0.5)-valueTo(10.0) range
       at com.google.android.material.slider.BaseSlider.validateStepSize(BaseSlider.java:541)
       at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:601)
       at com.google.android.material.slider.BaseSlider.maybeCalculateTicksCoordinates(BaseSlider.java:1488)
       at com.google.android.material.slider.BaseSlider.updateTrackWidth(BaseSlider.java:1509)
       at com.google.android.material.slider.BaseSlider.onSizeChanged(BaseSlider.java:1479)
       at android.view.View.sizeChange(View.java:19895)
       at android.view.View.setFrame(View.java:19856)
       at android.view.View.layout(View.java:19759)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
       at android.view.View.layout(View.java:19762)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19762)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
       at android.view.View.layout(View.java:19762)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1136)
       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1972)
       at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3531)
       at android.view.View.dispatchTouchEvent(View.java:11832)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3036)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2714)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3042)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3042)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3042)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3042)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3042)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3042)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3042)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3042)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:473)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1857)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3326)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:435)
       at android.view.View.dispatchPointerEvent(View.java:12071)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5241)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5055)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4363)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4416)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4382)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4390)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4363)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4416)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4382)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4525)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4390)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4582)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4363)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4416)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4382)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4390)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4363)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7189)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7163)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7124)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7323)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7271)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7346)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
       at android.view.Choreographer.doCallbacks(Choreographer.java:791)
       at android.view.Choreographer.doFrame(Choreographer.java:720)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6687)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```
</details>

**Expected behavior:** 

No exception thrown when `valueFrom = 0.5f`, `valueTo = 10.0f` and `stepSize=0.5f`.

**Material Library version:**
- 1.6.0-alpha02

**Device:**

- LG Q6  (Android 8.1.0)
- Huawei Y9 Prime 2019 (Android 10)
(Maybe, this issue looks very rare and I cannot reproduce it myself...)

**Comment by h6ah4i** [comment]
Sorry, I have not noticed that the step size is different in the error message.

I thought it was configured as `stepSize=0.5f`, but the error message says `stepSize=1.0f`.

I'll check my app implementation.

**Comment by h6ah4i** [comment]
This was my fault. The slider was configured incorrectly depending on the specific screen size.
