### ISSUE TITLE
[BottomSheet] IndexOutOfBoundException on setStateInternal

### ISSUE THREAD

**Issue by waseefakhtar** [material-components/material-components-android#2820]
**Description:** We're experiencing some crashes in production related to BottomSheetBehavior among users running Android 12 on Samsung phones.

I updated the material library from 1.0.0 to 1.2.1 but still experience the same in the latest releases. I wonder if you're aware of the issue and if there's any fix.

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.remove(ArrayList.java:503)
       at androidx.core.view.ViewCompat.removeActionWithId(ViewCompat.java:1349)
       at androidx.core.view.ViewCompat.removeAccessibilityAction(ViewCompat.java:1339)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.updateAccessibilityActions(BottomSheetBehavior.java:1717)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1111)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1540)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:792)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.add(ArrayList.java:468)
       at androidx.core.view.ViewCompat.addAccessibilityAction(ViewCompat.java:1324)
       at androidx.core.view.ViewCompat.replaceAccessibilityAction(ViewCompat.java:1315)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.addAccessibilityActionForState(BottomSheetBehavior.java:1751)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.updateAccessibilityActions(BottomSheetBehavior.java:1720)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1111)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1540)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:655)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

**Screenshot:**

<img width="1312" alt="Screen Shot 2022-07-15 at 2 39 33 PM" src="https://user-images.githubusercontent.com/4093820/179197785-4f7fed8c-3407-41da-a90f-aa44199566d9.png">

**Android API version:** Android 12

**Material Library version:** 1.0.0, 1.2.1

**Device:** Samsung phones

**Comment by drchen** [comment]
Can you update the library version to 1.6 and see if it's still happening?

**Comment by drchen** [comment]
I'll close this issue for now due to no further info available. Please feel free to reopen it if this is still happening.
