### ISSUE TITLE
MaterialDatePicker crashing due to calling show() with tag

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#2901]
**Description:** 
Sometimes when the dialog is a bit slow to show and accidentally you call `dialog.show(fragmentManager, tag)` twice, it crashes with the following log.

```
FATAL EXCEPTION: main
    Process: com.sample.app, PID: 23149
    java.lang.IllegalStateException: Can't change tag of fragment MaterialDatePicker{274d712} (103dd30e-db63-4d2a-a34e-8eba30196a1a tag=MaterialDatePicker{274d712} (103dd30e-db63-4d2a-a34e-8eba30196a1a)): was MaterialDatePicker{274d712} (103dd30e-db63-4d2a-a34e-8eba30196a1a) now MaterialDatePicker{274d712} (103dd30e-db63-4d2a-a34e-8eba30196a1a tag=MaterialDatePicker{274d712} (103dd30e-db63-4d2a-a34e-8eba30196a1a))
        at androidx.fragment.app.FragmentTransaction.doAddOp(FragmentTransaction.java:312)
        at androidx.fragment.app.BackStackRecord.doAddOp(BackStackRecord.java:195)
        at androidx.fragment.app.FragmentTransaction.add(FragmentTransaction.java:224)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:261)
        at com.sample.app.presentation.ui.details.OverviewFragment.initViews$lambda-12$lambda-11$lambda-8(OverviewFragment.kt:208)
        at com.sample.app.presentation.ui.details.OverviewFragment.$r8$lambda$Lli1snZuqNoDo8aj4-bGFvOqdE8(OverviewFragment.kt:0)
        at com.sample.app.presentation.ui.details.OverviewFragment$$ExternalSyntheticLambda4.onClick(R8$$SyntheticClass:0)
        at android.view.View.performClick(View.java:7441)
        at android.widget.CompoundButton.performClick(CompoundButton.java:146)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Expected behavior:**
No crash

**Source code:** 
```
                fromDateChip.setOnClickListener {
                    datePickerFrom.show(parentFragmentManager, datePickerFrom.toString())
                }

                toDateChip.setOnClickListener {
                    datePickerTo.show(parentFragmentManager, datePickerTo.toString())
                }
```

Where `datePickerFrom` and `datePickerTo` is the actual dialog from `MaterialDatePicker.Builder.datePicker()`

**Minimal sample app repro:** 
N/A, intermittent

**Android API version:** 31

**Material Library version:** 1.7.0-alpha03

**Device:** Emulator Pixel 4

**Comment by drchen** [comment]
Hi so I believe it's an intended behavior of AndroidX DialogFragment implementation. You can either try-and-catch the exception, or having flag to prevent the same DialogFragment being showed twice.

**Comment by ArcherEmiya05** [comment]
> Hi so I believe it's an intended behavior of AndroidX DialogFragment implementation. You can either try-and-catch the exception, or having flag to prevent the same DialogFragment being showed twice.

Does leaving the tag as null will avoid such issue?

**Comment by ArcherEmiya05** [comment]
I know now how to reproduce this, I have a button with onclick listener that will call the `.show(fragmentManager, tag)` method. Now tapping it twice will cause crashing. I think this should be handle by the MDC itself?

**Comment by drchen** [comment]
Hmm... I think it's intentional that AndroidX DialogFragment implementation throws an exception if you try to show a fragment with the same tag twice. As a general-purpose library we probably want to follow the same behavior with Androidx and you can choose if you want to "recover/fail silently" in this case on the client side.

As for you question - if setting tag as null will prevent the crash - I'm not sure but I guess so. But won't that make your dialog show twice?

**Comment by ArcherEmiya05** [comment]
> Hmm... I think it's intentional that AndroidX DialogFragment implementation throws an exception if you try to show a fragment with the same tag twice. As a general-purpose library we probably want to follow the same behavior with Androidx and you can choose if you want to "recover/fail silently" in this case on the client side.
> 
> As for you question - if setting tag as null will prevent the crash - I'm not sure but I guess so. But won't that make your dialog show twice?

I tried to set the tag with null but the crashing still happens.

**Comment by drchen** [comment]
In that case how about just try-and-catch the exception, or having a flag to prevent show() from being called twice?

**Comment by ArcherEmiya05** [comment]
> In that case how about just try-and-catch the exception, or having a flag to prevent show() from being called twice?

Yes, but I think this should never happen or at least documented. Imagine having a bug in production because of this issue. It's just really bad to discover it later because it wasn't even mention in docs.

**Comment by drchen** [comment]
I totally agree the behavior should be documented. : )
