### ISSUE TITLE
[TabLayout] Instantiation error in AndroidStudio

### ISSUE THREAD

**Issue by daniel-reinhold** [material-components/material-components-android#3007]
**Description:** When I use the library `com.google.android.material:material:1.8.0-alhpa01` and add a TabLayout to any layout in AndroidStudio, I get the following notice:

```
java.lang.IllegalArgumentException: Motion easing theme attribute must be an @interpolator resource for ?attr/motionEasing*Interpolator attributes or a string for ?attr/motionEasing* attributes.
	at com.google.android.material.motion.MotionUtils.resolveThemeInterpolator(MotionUtils.java:74)
	at com.google.android.material.tabs.TabLayout.<init>(TabLayout.java:614)
	at com.google.android.material.tabs.TabLayout.<init>(TabLayout.java:509)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Expected behavior:** AndroidStudio should show a preview of the TabLayout

**Source code:** 

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.android.material.tabs.TabLayout
        android:id="@+id/tabLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <androidx.viewpager2.widget.ViewPager2
        android:id="@+id/viewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/tabLayout" />

</RelativeLayout>
```

```
implementation "androidx.core:core-ktx:1.9.0"
implementation "androidx.appcompat:appcompat:1.5.1"
implementation "com.google.android.material:material:1.8.0-alpha01"
```

**Android API version:** 33

**Material Library version:** 1.8.0-alpha01

**Device:** AndroidStudio

**Comment by pekingme** [comment]
Hmm, I don't see the error when add a `tablayout` to the layout file with 1.8.0-alpha01, either in preview or runtime. Could you share more details about the reproduce steps?

**Comment by hunterstich** [comment]
@daniel-reinhold What is your app's theme? Can you share your theme file?

**Comment by daniel-reinhold** [comment]
Here my theme file:

```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.Material3.Light.NoActionBar">
        <!-- Primary brand color. -->
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryVariant">@color/primary_variant</item>
        <item name="colorOnPrimary">@color/text_on_primary</item>

        <!-- Secondary brand color. -->
        <item name="colorSecondary">@color/secondary</item>
        <item name="colorSecondaryVariant">@color/secondary_variant</item>
        <item name="colorOnSecondary">@color/text_on_secondary</item>

        <!-- Status bar color. -->
        <item name="android:statusBarColor">@color/background_variant</item>
        <item name="android:windowLightStatusBar">true</item>

        <!-- Window background -->
        <item name="android:windowBackground">@color/background</item>

        <!-- Font family -->
        <item name="android:fontFamily">@font/muli</item>
        <item name="fontFamily">@font/muli</item>

        <!-- Global styles -->
        <item name="android:textViewStyle">@style/TextViewStyle</item>
        <item name="materialButtonOutlinedStyle">@style/MaterialButton.Primary</item>
        <item name="textInputFilledStyle">@style/TextField</item>
        <item name="snackbarStyle">@style/SnackbarStyle</item>
        <item name="snackbarTextViewStyle">@style/SnackbarTextViewStyle</item>
        <item name="snackbarButtonStyle">@style/SnackbarButtonStyle</item>
        <item name="materialSwitchStyle">@style/SwitchStyle</item>
        <item name="textInputOutlinedStyle">@style/TextField</item>
        <item name="circularProgressIndicatorStyle">@style/CircularProgressIndicator</item>
        <item name="bottomSheetDialogTheme">@style/BottomSheetDialog</item>
        <item name="floatingActionButtonPrimaryStyle">@style/FloatingActionButton</item>
        <item name="chipStyle">@style/ChipStyle</item>
        <item name="tabStyle">@style/TabStyle</item>
    </style>

    <style name="TextViewStyle" parent="android:Widget.TextView">
        <item name="android:textColor">@color/text_primary</item>
    </style>

    <!-- Button styles -->
    <style name="MaterialButton" parent="Widget.Material3.Button.TonalButton">
        <item name="android:paddingVertical">16dp</item>
        <item name="android:textSize">16sp</item>
        <item name="cornerRadius">12dp</item>
    </style>

    <style name="MaterialButton.Primary" parent="MaterialButton">
        <item name="backgroundTint">@color/button_primary_background</item>
        <item name="android:textColor">@color/button_primary_text</item>
    </style>

    <style name="MaterialButton.Secondary" parent="MaterialButton">
        <item name="backgroundTint">@color/button_secondary_background</item>
        <item name="android:textColor">@color/button_secondary_text</item>
    </style>

    <style name="MaterialButton.ToggleButton" parent="Widget.Material3.Button.OutlinedButton">
        <item name="strokeWidth">2dp</item>
        <item name="strokeColor">@color/toggle_button_stroke</item>
        <item name="backgroundTint">@color/toggle_button_background_color</item>
        <item name="iconTint">@color/toggle_button_icon_tint</item>
        <item name="android:textColor">@color/toggle_button_text_color</item>
    </style>

    <style name="AppleLoginButton" parent="Widget.Material3.Button.OutlinedButton">
        <item name="cornerRadius">5dp</item>
        <item name="icon">@drawable/ic_apple</item>
        <item name="android:paddingVertical">0dp</item>
        <item name="backgroundTint">@color/background_apple_login_button</item>
        <item name="iconTint">@color/icon_tint_apple_login_button</item>
        <item name="android:textColor">@color/text_on_apple_login_button</item>
        <item name="strokeWidth">0dp</item>
        <item name="rippleColor">@color/ripple_color_apple_login_button</item>
        <item name="iconGravity">textStart</item>
    </style>

    <style name="FacebookLoginButton" parent="Widget.Material3.Button.OutlinedButton">
        <item name="cornerRadius">5dp</item>
        <item name="icon">@drawable/ic_facebook</item>
        <item name="android:paddingVertical">0dp</item>
        <item name="backgroundTint">@color/background_facebook_login_button</item>
        <item name="iconTint">@color/icon_tint_facebook_login_button</item>
        <item name="android:textColor">@color/text_on_facebook_login_button</item>
        <item name="strokeWidth">0dp</item>
        <item name="rippleColor">@color/ripple_color_facebook_login_button</item>
        <item name="iconGravity">textStart</item>
    </style>

    <style name="IconButton" parent="Widget.Material3.Button.IconButton">
        <item name="android:width">48dp</item>
        <item name="android:height">48dp</item>
        <item name="iconTint">@color/icon_button_tint</item>
        <item name="rippleColor">@color/icon_button_ripple</item>
    </style>

    <style name="IconButton.Primary" parent="IconButton">
        <item name="android:backgroundTint">@color/icon_button_primary_background</item>
        <item name="iconTint">@color/icon_button_primary_tint</item>
        <item name="rippleColor">@color/icon_button_primary_ripple</item>
    </style>

    <style name="IconButton.Primary.NoBackground" parent="IconButton">
        <item name="iconTint">@color/icon_button_primary_tint</item>
        <item name="rippleColor">@color/icon_button_primary_ripple</item>
    </style>

    <style name="IconButton.Secondary" parent="IconButton">
        <item name="android:backgroundTint">@color/icon_button_secondary_background</item>
        <item name="iconTint">@color/icon_button_secondary_tint</item>
        <item name="rippleColor">@color/icon_button_secondary_ripple</item>
    </style>

    <style name="IconButton.Secondary.NoBackground" parent="IconButton">
        <item name="iconTint">@color/icon_button_secondary_tint</item>
        <item name="rippleColor">@color/icon_button_secondary_ripple</item>
    </style>

    <style name="IconButton.White" parent="IconButton">
        <item name="iconTint">@color/icon_button_white_tint</item>
        <item name="android:backgroundTint">@color/icon_button_white_background</item>
        <item name="rippleColor">@color/icon_button_white_ripple</item>
        <item name="shapeAppearanceOverlay">@style/IconButton.White.ShapeAppearance</item>
    </style>

    <style name="IconButton.White.ShapeAppearance" parent="ShapeAppearanceOverlay.Material3.Button">
        <item name="cornerSize">15%</item>
    </style>

    <style name="IconButton.White.NoBackground" parent="IconButton">
        <item name="iconTint">@color/icon_button_white_tint</item>
        <item name="rippleColor">@color/icon_button_secondary_ripple</item>
    </style>

    <style name="TextButton" parent="Widget.Material3.Button.TextButton">
        <item name="android:textColor">@color/text_button_text</item>
        <item name="rippleColor">@color/text_button_ripple</item>
    </style>

    <style name="FloatingActionButton" parent="Widget.Material3.FloatingActionButton.Primary">
        <item name="tint">@color/white</item>
        <item name="backgroundTint">@color/primary</item>
    </style>

    <!-- Switch styles -->
    <style name="SwitchStyle" parent="Widget.Material3.CompoundButton.MaterialSwitch">
        <item name="thumbTint">@color/switch_thumb_color</item>
        <item name="trackTint">@color/switch_track_color</item>
        <item name="trackDecorationTint">@android:color/transparent</item>
        <item name="android:thumb">@drawable/switch_thumb_animation</item>
    </style>

    <!-- Chip styles -->
    <style name="ChipStyle" parent="Widget.Material3.Chip.Assist">
        <item name="chipBackgroundColor">@color/chip_background</item>
        <item name="chipStrokeColor">@color/chip_stroke</item>
        <item name="android:textColor">@color/chip_text</item>
        <item name="chipStrokeWidth">1.5dp</item>
    </style>

    <!-- Tab style -->
    <style name="TabStyle" parent="Base.Widget.Material3.TabLayout">
        <item name="tabTextColor">@color/tab_text</item>
        <item name="tabBackground">@drawable/background_tab</item>
        <item name="tabIndicatorColor">@color/tab_indicator_selected</item>
        <item name="tabIndicatorFullWidth">true</item>
        <item name="tabIndicator">@drawable/tab_indicator</item>
    </style>

    <!-- TextField styles -->
    <style name="TextField" parent="Widget.Material3.TextInputLayout.OutlinedBox">
        <item name="boxBackgroundColor">@color/text_field_background</item>
        <item name="boxCornerRadiusTopStart">15dp</item>
        <item name="boxCornerRadiusTopEnd">15dp</item>
        <item name="boxCornerRadiusBottomStart">15dp</item>
        <item name="boxCornerRadiusBottomEnd">15dp</item>
        <item name="boxStrokeWidth">0dp</item>
        <item name="errorTextColor">@color/text_field_error_color</item>
        <item name="hintEnabled">false</item>
        <item name="hintTextColor">@color/text_field_hint_color</item>
    </style>

    <!-- Text styles -->
    <style name="ActionBarTitleTextStyle" parent="">
        <item name="android:textStyle">bold</item>
        <item name="android:textSize">20sp</item>
    </style>

    <!-- Flag TextView styles -->
    <style name="FlagTextView" parent="Widget.MaterialComponents.TextView">
        <item name="android:width">100dp</item>
        <item name="android:height">20dp</item>
        <item name="android:textSize">12sp</item>
        <item name="android:background">@drawable/background_flag</item>
        <item name="android:gravity">center_vertical</item>
        <item name="android:paddingStart">15dp</item>
        <item name="android:paddingEnd">0dp</item>
        <item name="android:textColor">@color/text_on_primary</item>
    </style>

    <!-- Progress Indicator styles -->
    <style name="CircularProgressIndicator" parent="Widget.Material3.CircularProgressIndicator">
        <item name="android:indeterminate">true</item>
        <item name="android:progressTint">@color/circular_progress_indicator_progress</item>
        <item name="trackThickness">@dimen/circular_progress_indicator_track_thickness</item>
        <item name="trackCornerRadius">@dimen/circularProgressIndicatorTrackCornerRadius</item>
    </style>

    <!-- Snackbar styles -->
    <style name="SnackbarStyle" parent="Widget.Material3.Snackbar">
        <item name="android:layout_margin">8dp</item>
    </style>

    <style name="SnackbarTextViewStyle" parent="Widget.Material3.Snackbar.TextView">
        <item name="android:textSize">16sp</item>
    </style>

    <style name="SnackbarButtonStyle" parent="Widget.Material3.Button.TextButton.Snackbar">
        <item name="android:textSize">16sp</item>
        <item name="android:textStyle">bold</item>
    </style>

    <!-- BottomNavigationMenu styles -->
    <style name="BottomNavigationMenuStyle" parent="Theme.Material3.Light.NoActionBar">
        <item name="colorSecondaryContainer">@android:color/transparent</item>
    </style>

    <!-- Sidebar styles -->
    <style name="SidebarItemTextAppearance" parent="TextAppearance.Material3.LabelMedium">
        <item name="android:textSize">18sp</item>
        <item name="android:textStyle">bold</item>
    </style>

    <style name="SidebarItemShapeAppearance" parent="">
        <item name="cornerFamily">cut</item>
        <item name="cornerSizeTopLeft">0dp</item>
        <item name="cornerSizeTopRight">0dp</item>
        <item name="cornerSizeBottomLeft">0dp</item>
        <item name="cornerSizeBottomRight">0dp</item>
    </style>

    <!-- DatePicker style -->
    <style name="DatePickerStyle" parent="ThemeOverlay.Material3.MaterialCalendar">
        <item name="android:background">@color/date_picker_background</item>
        <item name="materialCalendarStyle">@style/CalendarStyle</item>
        <item name="materialCalendarHeaderLayout">@style/CalendarStyle.Header</item>
        <item name="materialCalendarHeaderDivider">@style/CalendarStyle.HeaderDivider</item>
        <item name="materialCalendarHeaderTitle">@style/CalendarStyle.HeaderTitle</item>
        <item name="materialCalendarHeaderToggleButton">@style/CalendarStyle.HeaderToggleButton
        </item>
        <item name="materialCalendarYearNavigationButton">
            @style/CalendarStyle.YearNavigationButton
        </item>
        <item name="materialCalendarMonthNavigationButton">
            @style/CalendarStyle.MonthNavigationButton
        </item>
        <item name="materialCalendarDayOfWeekLabel">@style/CalendarStyle.DayOfWeekLabel</item>
        <item name="buttonBarPositiveButtonStyle">@style/CalendarStyle.ButtonPositive</item>
        <item name="buttonBarNegativeButtonStyle">@style/CalendarStyle.ButtonNegative</item>
    </style>

    <!-- TimePicker style -->
    <style name="TimePickerStyle" parent="ThemeOverlay.Material3.MaterialTimePicker">
        <item name="colorPrimary">@color/time_picker_background</item>
        <item name="colorOnPrimary">@color/time_picker_button</item>
        <item name="materialClockStyle">@style/TimePickerStyle.Clock</item>
        <item name="chipStyle">@style/TimePickerStyle.Chip</item>
        <item name="materialTimePickerTitleStyle">@style/TimePickerStyle.Title</item>
        <item name="borderlessButtonStyle">@style/TimePickerStyle.Button</item>
    </style>

    <!-- BottomSheet style -->
    <style name="BottomSheetDialog" parent="Theme.Material3.Light.BottomSheetDialog">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorSurface">@android:color/transparent</item>
        <item name="android:windowIsFloating">false</item>
        <item name="bottomSheetStyle">@style/BottomSheetDialog.Modal</item>
        <item name="android:windowTranslucentStatus">false</item>
        <item name="android:windowSoftInputMode">adjustResize</item>
        <item name="android:textViewStyle">@style/TextViewStyle</item>
    </style>

    <style name="BottomSheetDialog.Modal" parent="Widget.Material3.BottomSheet.Modal">
        <item name="colorSurface">@android:color/transparent</item>
        <item name="android:background">@android:color/transparent</item>
    </style>

    <style name="ImageViewRounded" parent="">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">50%</item>
    </style>

</resources>
```

**Comment by patzly** [comment]
Hi, with the new 1.8.0-alpha02 I have this exception also for every `MaterialCardView` and `AppBarLayout` so no layout previews are shown in Android Studio at all (because I use an app bar in each layout). Rebuilding, restarting, cache invalidation or layout preview refreshing has no effect. The error message:

```
The following classes could not be instantiated:
- com.google.android.material.card.MaterialCardView
- com.google.android.material.appbar.AppBarLayout

Exception Details:
java.lang.IllegalArgumentException: Motion easing theme attribute must be an @interpolator resource for ?attr/motionEasing*Interpolator attributes or a string for ?attr/motionEasing* attributes.
at com.google.android.material.motion.MotionUtils.resolveThemeInterpolator(MotionUtils.java:74)
at com.google.android.material.card.MaterialCardViewHelper.<init>(MaterialCardViewHelper.java:161) 
at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:174)
at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:160)
```

So it must have to do with newly added motion attributes in these views or maybe the motion system tokens. I had this errors on WIndows since Android Studio Chipmunk with only a few views like @daniel-reinhold described and now on Mac OS (Android Studio Dolphin) and 1.8.0-alpha02 with every fragment because of the `AppBarLayout`s and `MaterialCardView`s in them.
The app runs completely normal without any layout errors, it's just the layout preview.

**Comment by hunterstich** [comment]
Oh, okay. I didn't understand that this was only happening in the layout preview. If that's the case, this bug should be [filed for Android Studio](https://developer.android.com/studio/report-bugs).

I'm going to close this for now but if I've misunderstood or you have further questions feel free to re-open.

**Comment by Gizmodo** [comment]
Same trouble with TextInputLayout and MaterialCardView in the layout preview
Material -> 1.8.0-alpha02
Android Studio Dolphin | 2021.3.1 Patch 1
```
java.lang.IllegalArgumentException: Motion easing theme attribute must be an @interpolator resource for ?attr/motionEasing*Interpolator attributes or a string for ?attr/motionEasing* attributes.
	at com.google.android.material.motion.MotionUtils.resolveThemeInterpolator(MotionUtils.java:74)
	at com.google.android.material.textfield.IndicatorViewController.<init>(IndicatorViewController.java:148)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:225)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:451)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


```

**Comment by shalva97** [comment]
Any workaround for this? whole preview is broken

**Comment by patzly** [comment]
@shalva97 Yes for me too... I always switch to alpha01 when need a layout preview and then when I'm done I switch back to alpha03 but it's a hard pain... @hunterstich Are we alone with this or does your team also experience this issue? I have it on both Windows and Mac independently, so we shouldn't be alone with this I think🤷🏻‍♂️

**Comment by Gizmodo** [comment]
I created an issue here https://issuetracker.google.com/issues/258646238
Upvote it, please!

**Comment by patzly** [comment]
@Gizmodo @shalva97 @daniel-reinhold I just tested the latest Android Studio nightly built (2022.2.1) with 1.8.0-alpha03 and the layout preview works for me! The latest release candidate of Electric Eel still doesn't work, so I think I will work with Flamingo for the next months.

**Comment by Mik3Rizzo** [comment]
> @Gizmodo @shalva97 @daniel-reinhold I just tested the latest Android Studio canary build (2022.2.1) with 1.8.0-alpha03 and the layout preview works for me again!

I'm using 1.8.0-rc01 and Android Studio Flamingo Canary 11, I still have the AppBarLayout rendering problem. Is there any workaround? Thanks.

**Comment by patzly** [comment]
@Mik3Rizzo For me it works without any problems since I use Flamingo canary, weird that it doesn't work for you as this cuurently is the (only) working solution for most people I think.

**Comment by Mik3Rizzo** [comment]
@patzly I tried to clear the cache, to clean and rebuild the project, to restart the IDE, but nothing: the AppBarLayout still gives the rendering exception. Is there any 
other try I can make?

**Comment by patzly** [comment]
@Mik3Rizzo Hmm I don't know a solution then, sorry :(
Maybe try removing canary from time to time and reinstalling it again to check if later builds fix it for you..

**Comment by Mik3Rizzo** [comment]
@patzly I'll keep updated with the IDE Canary channel, thank you!
Can you give me the exact IDE and MDC versions in which the AppBarLayout preview works? Thanks.

**Comment by patzly** [comment]
@Mik3Rizzo I also use the latest rc release of MDC and the latest canary.

**Comment by Mik3Rizzo** [comment]
@patzly Thanks. Can you also tell me the JDK and the Gradle version please? I'm trying all the configurations.

**Comment by patzly** [comment]
@Mik3Rizzo AGP 7.3.1 and Gradle 7.6.

**Comment by deadfan** [comment]
It's fixed ?

**Comment by Mik3Rizzo** [comment]
> It's fixed ?

I'm just trying right now, it seems fixed!
I'm using Android Studio Giraffe Canary 1 and mdc-1.8.0-rc01.

**Comment by cyb3rko** [comment]
For MDC 1.8.0 and stable Electric Eel it doesn't work.
I just went with downgrading to 1.7.0.

**Comment by Mik3Rizzo** [comment]
> For MDC 1.8.0 and stable Electric Eel it doesn't work. I just went with downgrading to 1.7.0.
> 
> Maybe we just need that Android Studio update then...

It works with Android Studio Giraffe Canary 1 and mdc-1.8.0-rc01 (and above).

**Comment by cyb3rko** [comment]
Yeah, just left the comment because I don't really like to work with Canary versions anymore.  
In the past I only had problems with Canary versions breaking relevant features.

I'll wait for the next release then and upgrade then to MDC 1.8.0.

**Comment by Mik3Rizzo** [comment]
> but **1.8.0-alpha02** and above not work anymore

Did you try with 1.8.0 stable that has just been released?

**Comment by Baterka** [comment]
Here they say it is fixed: https://issuetracker.google.com/issues/257280452
But it looks like it is not.

**Comment by Stack-overflow-polished7** [comment]
https://cakephp7.github.io/climatic/ I sourced the answer
