### ISSUE TITLE
[SwitchMaterial] Crash Resources$NotFoundException in Nexus 5X with Android 8.1.0 

### ISSUE THREAD

**Issue by jdelga** [material-components/material-components-android#3032]
**Description:** 
I have been reported several issues in Crashlytics after integrating an app with Material 1.6.1

Caused by android.content.res.Resources$NotFoundException: File res/drawable/abc_switch_thumb_material.xml from drawable resource ID #0x7f080047
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:820)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:877)
       at android.content.res.XResources.getDrawableForDensity(XResources.java:868)
       at android.content.res.Resources.getDrawable(Resources.java:819)
       at android.content.res.XResources.getDrawable(XResources.java:790)
       at android.content.Context.getDrawable(Context.java:605)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:864)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:483)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:149)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
       at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:66)
       at androidx.appcompat.widget.TintTypedArray.getDrawable(TintTypedArray.java:84)
       at androidx.appcompat.widget.SwitchCompat.<init>(SwitchCompat.java:262)
       at com.google.android.material.switchmaterial.SwitchMaterial.<init>(SwitchMaterial.java:70)
       at com.google.android.material.switchmaterial.SwitchMaterial.<init>(SwitchMaterial.java:66)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at com.tal.tal.presentation.base.BaseFragment.onCreateView(BaseFragment.kt:21)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Expected behavior:** 
There is no crash

**Source code:** 
            <com.google.android.material.switchmaterial.SwitchMaterial
                android:id="@+id/id"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="40dp"
                android:layout_marginTop="10dp"
                android:layout_marginRight="40dp"
                android:layout_marginBottom="10dp"
                android:text="@string/string" />

**Minimal sample app repro:** 
Just add the previous code to any layout.

**Android API version:**
CompileSdk 33
TargetSdk 32

**Material Library version:** 
1.6.1

**Device:** 
Only happens in Nexus 5X, probably caused after Google Play distribution method with cuts resources for the different devices.

**Comment by drchen** [comment]
Hi, do you know the API level distribution of the crash?

It looks pretty like a resource cache issue on older APIs.

**Comment by jdelga** [comment]
In my case all errors are caused in Nexus 5X with Android 8.1.0. Only detected in Production code in Crashlytics

![image](https://user-images.githubusercontent.com/36664452/196559817-7e95b967-04a7-4475-b620-a287c4bd496c.png)

Other errors reported here: https://stackoverflow.com/questions/73486011/error-inflating-class-com-google-android-material-switchmaterial-switchmateria

**Comment by ytheekshana** [comment]
I got the same kind of issue on Android 12 on a range of brands.
I am using 'com.google.android.material:material:1.7.0-rc01'
Using Material3. But my app doesnt have a Material3 switch. But it does have a SwitchPreferenceCompat

![image](https://user-images.githubusercontent.com/24976965/196697842-55501d5f-e3a9-4ed7-bb27-9a2fe631e7f9.png)

![image](https://user-images.githubusercontent.com/24976965/196697987-a39565ee-02e9-4387-a079-fd896c7dc283.png)

![image](https://user-images.githubusercontent.com/24976965/196698098-b7e146a2-3cb9-4e3d-9371-b83e6e9e9378.png)

**Comment by SopraniDaniele23** [comment]
Hi, do you use proguard with shrinksize option enabled?

**Comment by jdelga** [comment]
> Hi, do you use proguard with shrinksize option enabled?

Yes, it is production code. Is there any configuration I should add ?

**Comment by ytheekshana** [comment]
> Hi, do you use proguard with shrinksize option enabled?
 yes minifyEnabled & shrinkResources both are set to true

**Comment by SopraniDaniele23** [comment]
Try adding '-printusage usage.txt' in proguard rules file and check if 'usage.txt' contains the missing resource.

**Comment by azartx** [comment]
> Try adding '-printusage usage.txt' in proguard rules file and check if 'usage.txt' contains the missing resource.

I have the same problem, play market show an issues on another devices and android apis.
Minifying and shrinking are true, usage.txt contains abc_switch_thumb_material

**Comment by azartx** [comment]
Add new line to my proguard-rules, let's see if it helps

`-keep class com.google.android.material.R$drawable { *; }`

**Comment by haykgalstyan** [comment]
> Add new line to my proguard-rules, let's see if it helps
> 
> `-keep class com.google.android.material.R$drawable { *; }`

How did it go?

**Comment by j4zib** [comment]
> Add new line to my proguard-rules, let's see if it helps
> 
> `-keep class com.google.android.material.R$drawable { *; }`

@azartx any updates?

**Comment by ytheekshana** [comment]
https://issuetracker.google.com/issues/243851373
This is the same issue with more details.

**Comment by drchen** [comment]
Hi apparently that's an AppCompat issue and not directly related to the Material library. 

Let me close this for now and keep track that in the issue tracker: https://issuetracker.google.com/issues/243851373
So the issue can have better visibility to the AppCompat team.

**Comment by cobraapps** [comment]
> Add new line to my proguard-rules, let's see if it helps
> 
> `-keep class com.google.android.material.R$drawable { *; }`

Still have this crash with this line in proguard

**Comment by EzequielAdrianM** [comment]
Having this same exact issue in production. Only happens in Nexus 5X with Android 8.1.0.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxxxxx/com.xxxxx.activity.SettingsActivity}: android.view.InflateException: Binary XML file line #387: Binary XML file line #307: Error inflating class androidx.appcompat.widget.SwitchCompat
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by SomnathS09** [comment]
Any update on the issue? experiencing this problem in Redmi 9i sport and other devices.
In my case, The problem arised because user has side-loaded (installed) the app from apk file shared from other device rather than installing from from play store.

**Comment by ronenfe** [comment]
I have the same on Nexus devices, it's been going on for 6 years with no fix.
