### ISSUE TITLE
[TextInputLayout] Motion easing theme

### ISSUE THREAD

**Issue by Gizmodo** [material-components/material-components-android#3075]
**Description:** Unable to use preview layout

**Steps to reproduce:** 
1. Create new project
2. Select "Basic Activity (Material3)" as a template
3. Upgrade material lib to 1.8.0-alpha02
4. Open frament_first.xml layout
5. Try to add TextInputLayout
6. Get exception in the message window and blank screen inside preview area.

P.S. This kind of exception occurs also if you replace TextInputLayout with MaterialCardView component.

**Android IDE:** Android Studio Dolphin | 2021.3.1 Patch 1
**Android API version:** 32
**Material Library version:** 1.8.0-alpha02
**Device:** Emulator
![image](https://user-images.githubusercontent.com/1078610/201176528-f55b4ac7-3863-4370-8908-bafb7aa921d0.png)

![image](https://user-images.githubusercontent.com/1078610/201176587-bbed01ab-88fb-4a25-9a92-bf9026ae2cbe.png)
```

java.lang.IllegalArgumentException: Motion easing theme attribute must be an @interpolator resource for ?attr/motionEasing*Interpolator attributes or a string for ?attr/motionEasing* attributes.
	at com.google.android.material.motion.MotionUtils.resolveThemeInterpolator(MotionUtils.java:74)
	at com.google.android.material.textfield.IndicatorViewController.<init>(IndicatorViewController.java:148)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:225)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:451)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by imhappi** [comment]
This bug should be filed for Android Studio https://developer.android.com/studio/report-bugs

**Comment by Gizmodo** [comment]
https://issuetracker.google.com/issues/258646238
