### ISSUE TITLE
[MaterialButton] German letter 'ß' causes a crash from 1.7.0

### ISSUE THREAD

**Issue by AurimasSikorskas** [material-components/material-components-android#3086]
**Description:** 
adding a string with the letter `ß` to the material button + icon attributes results in a crash. Can be even observed in the Android studio editor view. Will add an xml snipset whit minimal attributes that cause the issue. The snipset produces an error inside Android studio editor, but its the same error that we are seeing on our app.

From my experience if I don't specify the icon gravity it works fine or if I use `textAllCaps`, or if you donth specify the icon at all, it works correctly.

This started happening after updating the library version 1.6.1 -> 1.7.0

The error trace
```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: begin 0, end 11, length 10
       at java.lang.String.checkBoundsBeginEnd(String.java:3942)
       at java.lang.String.substring(String.java:2467)
       at java.lang.String.subSequence(String.java:2517)
       at com.google.android.material.button.MaterialButton.getTextInLine(MaterialButton.java:658)
       at com.google.android.material.button.MaterialButton.getTextLayoutWidth(MaterialButton.java:619)
       at com.google.android.material.button.MaterialButton.updateIconPosition(MaterialButton.java:571)
       at com.google.android.material.button.MaterialButton.onLayout(MaterialButton.java:453)
       at android.view.View.layout(View.java:24958)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
       at android.view.View.layout(View.java:24958)
       at android.view.ViewGroup.layout(ViewGroup.java:6784)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24958)
       at android.view.ViewGroup.layout(ViewGroup.java:6784)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
       at android.view.View.layout(View.java:24958)
       at android.view.ViewGroup.layout(ViewGroup.java:6784)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24958)
       at android.view.ViewGroup.layout(ViewGroup.java:6784)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24958)
       at android.view.ViewGroup.layout(ViewGroup.java:6784)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24958)
       at android.view.ViewGroup.layout(ViewGroup.java:6784)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24958)
       at android.view.ViewGroup.layout(ViewGroup.java:6784)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1418)
       at android.view.View.layout(View.java:24958)
       at android.view.ViewGroup.layout(ViewGroup.java:6784)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4787)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4115)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2991)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10665)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:852)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

**Expected behavior:** The app should not crash

**Source code:**
```
        <com.google.android.material.button.MaterialButton
            android:id="@+id/button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Großartig!"
            android:textAllCaps="true"
            app:iconGravity ="textStart"
            app:icon="@drawable/vector_start_brown" />
```

**Android API version:** API level 33

**Material Library version:** 'com.google.android.material:material:1.7.0'

**Device:** Galaxy S22 Ultra

**Comment by drchen** [comment]
I believe this has been fixed by https://github.com/material-components/material-components-android/commit/3b333ee8343dc0bde20d110a39ccc4654977eb23

I'll talk to the team to check if we should cherry-pick the change to 1.7 versions.
