### ISSUE TITLE
AppBarLayout give an error in Android

### ISSUE THREAD

**Issue by aiyu-ayaan** [material-components/material-components-android#3105]
Here is the exception. 
`com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild`

```
Exception java.lang.IllegalArgumentException: parameter must be a descendant of this view
  at android.view.ViewGroup.offsetRectBetweenParentAndChild (ViewGroup.java:6362)
  at android.view.ViewGroup.offsetDescendantRectToMyCoords (ViewGroup.java:6291)
  at androidx.core.widget.NestedScrollView.isWithinDeltaOfScreen (NestedScrollView.java)
  at androidx.core.widget.NestedScrollView.onSizeChanged (NestedScrollView.java)
  at android.view.View.sizeChange (View.java:23256)
  at android.view.View.setFrame (View.java:23206)
  at android.view.View.layout (View.java:23062)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild (HeaderScrollingViewBehavior.java:155)
  at com.google.android.material.appbar.ViewOffsetBehavior.h (ViewOffsetBehavior.java:1)
  at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout (CoordinatorLayout.java:43)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at androidx.drawerlayout.widget.DrawerLayout.onLayout (DrawerLayout.java:58)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1829)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1673)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1582)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
  at com.android.internal.policy.DecorView.onLayout (DecorView.java:804)
  at android.view.View.layout (View.java:23065)
  at android.view.ViewGroup.layout (ViewGroup.java:6479)
  at android.view.ViewRootImpl.performLayout (ViewRootImpl.java:3625)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3085)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2076)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8508)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1076)
  at android.view.Choreographer.doCallbacks (Choreographer.java:897)
  at android.view.Choreographer.doFrame (Choreographer.java:826)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1061)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8107)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
```
May be related to #511

**Comment by drchen** [comment]
I don't think it's related to HeaderScrollingViewBehavior. (Check the crash call stack, it actually went through a lot of layout layers beyond the one associated with the behavior.)

You probably want to check your inner layout and debug from there - like replace certain inner layouts and see if that fixes the crash. It seems like you are using a NestedScrollView, I'll suggest you starting from there.

**Comment by ytheekshana** [comment]
This was the crash i was getting. 

`Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'boolean android.animation.AnimatorSet$Node.mEnded' on a null object reference
       at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:799)
       at android.animation.AnimatorSet.start(AnimatorSet.java:640)
       at android.animation.StateListAnimator.start(StateListAnimator.java:188)
       at android.animation.StateListAnimator.setState(StateListAnimator.java:181)
       at android.view.View.drawableStateChanged(View.java:18049)
       at android.view.ViewGroup.drawableStateChanged(ViewGroup.java:6479)
       at android.view.View.refreshDrawableState(View.java:18108)
       at android.view.View.dispatchAttachedToWindow(View.java:15589)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2955)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4510)
       at android.view.ViewGroup.addView(ViewGroup.java:4312)
       at android.view.ViewGroup.addView(ViewGroup.java:4252)
       at android.view.ViewGroup.addView(ViewGroup.java:4225)
       at androidx.viewpager2.adapter.FragmentStateAdapter.addViewToContainer(FragmentStateAdapter.java:406)
       at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:328)
       at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:273)
       at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:73)
       at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:8377)
       at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:954)
       at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:131)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:9430)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9388)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9375)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1676)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
       at android.view.View.layout(View.java:17702)
       at android.view.ViewGroup.layout(ViewGroup.java:5631)
       at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
       at android.view.View.layout(View.java:17702)
       at android.view.ViewGroup.layout(ViewGroup.java:5631)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
       at android.view.View.layout(View.java:17702)
       at android.view.ViewGroup.layout(ViewGroup.java:5631)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17702)
       at android.view.ViewGroup.layout(ViewGroup.java:5631)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
       at android.view.View.layout(View.java:17702)
       at android.view.ViewGroup.layout(ViewGroup.java:5631)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17702)
       at android.view.ViewGroup.layout(ViewGroup.java:5631)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
       at android.view.View.layout(View.java:17702)
       at android.view.ViewGroup.layout(ViewGroup.java:5631)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
       at android.view.View.layout(View.java:17702)
       at android.view.ViewGroup.layout(ViewGroup.java:5631)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2519)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2234)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6774)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
       at android.view.Choreographer.doCallbacks(Choreographer.java:735)
       at android.view.Choreographer.doFrame(Choreographer.java:667)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`
