### ISSUE TITLE
Date picker error in catalog of version 1.1.0-alpha05

### ISSUE THREAD

**Issue by qinglok** [material-components/material-components-android#317]
`    Process: io.material.catalog, PID: 26219
    android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at android.app.DatePickerDialog.<init>(DatePickerDialog.java:119)
        at android.app.DatePickerDialog.<init>(DatePickerDialog.java:109)
        at com.google.android.material.picker.MaterialStyledDatePickerDialog.<init>(MaterialStyledDatePickerDialog.java:84)
        at io.material.catalog.picker.PickerMainDemoFragment.materialStyledTodayDatePicker(PickerMainDemoFragment.java:122)
        at io.material.catalog.picker.PickerMainDemoFragment.onCreateDemoView(PickerMainDemoFragment.java:68)
        at io.material.catalog.feature.DemoFragment.onCreateView(DemoFragment.java:74)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2440)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:885)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:686)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2057)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1847)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1802)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1709)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:147)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at android.widget.DatePickerCalendarDelegate.<init>(DatePickerCalendarDelegate.java:125)
        at android.widget.DatePicker.createCalendarUIDelegate(DatePicker.java:181)
        at android.widget.DatePicker.<init>(DatePicker.java:161)
        at android.widget.DatePicker.<init>(DatePicker.java:138)
        at android.widget.DatePicker.<init>(DatePicker.java:134)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at android.app.DatePickerDialog.<init>(DatePickerDialog.java:119) 
        at android.app.DatePickerDialog.<init>(DatePickerDialog.java:109) 
        at com.google.android.material.picker.MaterialStyledDatePickerDialog.<init>(MaterialStyledDatePickerDialog.java:84) 
        at io.material.catalog.picker.PickerMainDemoFragment.materialStyledTodayDatePicker(PickerMainDemoFragment.java:122) 
        at io.material.catalog.picker.PickerMainDemoFragment.onCreateDemoView(PickerMainDemoFragment.java:68) 
        at io.material.catalog.feature.DemoFragment.onCreateView(DemoFragment.java:74) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2440) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:885) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:686) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2057) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1847) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1802) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1709) 
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:147) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:159) 
        at android.app.ActivityThread.main(ActivityThread.java:6364) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883) `

**Comment by ldjcmu** [comment]
Hello,

Can you provide the android API level you found this issue on? I can't currently repro this on Kitkat or Pie.

It'd also be helpful to know if the "Default Date Picker" demo button works or if just the Material Styled ones are broken.

Thanks!
