### ISSUE TITLE
Appcompact

### ISSUE THREAD

**Issue by nikzk2** [material-components/material-components-android#322]
Caused by: java.lang.RuntimeException: Unknown scene name: transitionManager
        at android.transition.TransitionInflater.createTransitionFromXml(TransitionInflater.java:181)
        at android.transition.TransitionInflater.inflateTransition(TransitionInflater.java:79)
        at com.android.internal.policy.PhoneWindow.getTransition(PhoneWindow.java:3026)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2937)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2184)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.example.datetimepicker.MainActivity.onCreate(MainActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by nikzk2** [comment]
Please How i resolve this error

**Comment by wcshi** [comment]
@nikzk2 Please provide a sample app and steps to reproduce this error.
