### ISSUE TITLE
[MaterialSwitch] can't be used in Menu

### ISSUE THREAD

**Issue by DontTrustMicrosoft-MicrosoftIsAsshole** [material-components/material-components-android#3237]
**Description:**

So SwitchCompat could be used inside DrawerLayout menu with the following method:

create a layout that holds a SwitchCompat (widget_switch.xml):

```
<androidx.appcompat.widget.SwitchCompat
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/switchcompat_hide_read"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"
    />

```
a menu would include this layout like so:

```
<menu
                    >
                        <item
                            android:id="@+id/nav_hide_read_msg"
                            android:icon="@drawable/baseline_visibility_off_white_36"
                            android:title="@string/nav_hide_read"
                            app:actionLayout="@layout/widget_switch"

                            />
</menu>
```

Now if we replace :

`<androidx.appcompat.widget.SwitchCompat
`
with:

`<com.google.android.material.materialswitch.MaterialSwitch
`
The App crashes, (somewhere after onResume() is done):

Error:
```


2023-02-14 22:25:23.571 AndroidRuntime           E  FATAL EXCEPTION: main
                                                    Process: com.APP.COM, PID: 2984
                                                    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                    	at android.text.StaticLayout.<init>(StaticLayout.java:474)
                                                    	at androidx.appcompat.widget.SwitchCompat.makeLayout(SwitchCompat.java:995)
                                                    	at androidx.appcompat.widget.SwitchCompat.onMeasure(SwitchCompat.java:916)
                                                    	at android.view.View.measure(View.java:26357)
                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                    	at android.view.View.measure(View.java:26357)
                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
                                                    	at androidx.appcompat.widget.LinearLayoutCompat.measureChildBeforeLayout(LinearLayoutCompat.java:1401)
                                                    	at androidx.appcompat.widget.LinearLayoutCompat.measureHorizontal(LinearLayoutCompat.java:1048)
                                                    	at androidx.appcompat.widget.LinearLayoutCompat.onMeasure(LinearLayoutCompat.java:577)
                                                    	at android.view.View.measure(View.java:26357)
                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9681)
                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1657)
                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
                                                    	at android.view.View.layout(View.java:23693)
                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                    	at android.view.View.layout(View.java:23693)
                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                    	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1287)
                                                    	at android.view.View.layout(View.java:23693)
                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                    	at android.view.View.layout(View.java:23693)
                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                                    	at android.view.View.layout(View.java:23693)
                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                    	at android.view.View.layout(View.java:23693)
                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                                    	at android.view.View.layout(View.java:23693)
                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                    	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
                                                    	at android.view.View.layout(View.java:23693)
                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                                    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3999)
                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3372)
                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
2023-02-14 22:25:23.571 AndroidRuntime           E  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                    	at android.view.Choreographer.doFrame(Choreographer.java:832)
                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                    	at android.os.Looper.loop(Looper.java:288)
                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)


```

**Expected behavior:** 

I expected that MaterialSwitch being a subclass of SwitchCompat behaves the same as before, just with the new nice Material Extra design

**Source code:** The code snippet which is causing this issue

See description

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** Android API version here

compiled and target SDK 33

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-alpha07)

1.8.0

**Device:** Device on which the bug was encountered here

emulator SDK 33

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by marcinbln** [comment]
what is the base theme? if it is not Theme.Material3.* it will crash

**Comment by DontTrustMicrosoft-MicrosoftIsAsshole** [comment]
@marcinbln 

"for splashscreen logic"
    <application   android:theme="@style/Theme.App.Starting"  >
           which is  ---->         <style name="Theme.App.Starting" parent="Theme.SplashScreen">

all other activitys have a standard apptheme :

  <style name="AppTheme" parent="Theme.AppCompat.DayNight">


@hunterstich 
by label you mean android:text="abc"  ? There's no label tag I can't find. If I add this text, same crash.  We are in crunch, I can't create a sample project right now. maybe later. 

Method I use basically is this:  https://stackoverflow.com/questions/56638356/how-to-add-switch-button-in-navigation-drawer

It's really simple: put a switch in a drawer layout. Works with switchcompat, does not with MaterialSwitch
Is there an example that shows it does work?



Also: when using MaterialSwitch i get three warnings. before the crash ( which happens in setContentView() )


```
Failed to inflate ColorStateList, leaving it to the framework
                                                    java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040101 a=-1}, theme={InheritanceMap=[id=0x7f13013fmy.app:style/NavDrawerTextStyle], Themes=[my.app:style/NavDrawerTextStyle, forced, my.app:style/AppTheme.NoActionBar, forced, my.app:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
                                                    	at android.content.res.TypedArray.getColor(TypedArray.java:529)
                                                    	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
                                                    	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
                                                    	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
                                                    	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
                                                    	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
                                                    	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
                                                    	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
                                                    	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
                                                    	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:93)
                                                    	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:72)
                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                    	at androidx.appcompat.view.menu.MenuItemImpl.setActionView(MenuItemImpl.java:772)
                                                    	at androidx.appcompat.view.menu.MenuItemImpl.setActionView(MenuItemImpl.java:52)
                                                    	at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:504)
                                                    	at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:531)
                                                    	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:207)
                                                    	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:185)
                                                    	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:129)
                                                    	at com.google.android.material.navigation.NavigationView.inflateMenu(NavigationView.java:528)
                                                    	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:327)
                                                    	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:141)
                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
                                                    	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
                                                    	at my.app.myactivity.onCreate(MyActivity.class:178)
                                                    	at android.app.Activity.performCreate(Activity.java:8305)
2023-02-16 13:03:15.479 ResourcesCompat          W  	at android.app.Activity.performCreate(Activity.java:8284)
                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                    	at android.os.Looper.loop(Looper.java:288)
                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-02-16 13:03:15.480 ResourcesCompat          W  Failed to inflate ColorStateList, leaving it to the framework
                                                    java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0400ee a=-1}, theme={InheritanceMap=[id=0x7f13013fmy.app:style/NavDrawerTextStyle], Themes=[my.app:style/NavDrawerTextStyle, forced, my.app:style/AppTheme.NoActionBar, forced, my.app:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
                                                    	at android.content.res.TypedArray.getColor(TypedArray.java:529)
                                                    	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
                                                    	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
                                                    	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
                                                    	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
                                                    	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
                                                    	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
                                                    	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
                                                    	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
                                                    	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:101)
                                                    	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:72)
                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                    	at androidx.appcompat.view.menu.MenuItemImpl.setActionView(MenuItemImpl.java:772)
                                                    	at androidx.appcompat.view.menu.MenuItemImpl.setActionView(MenuItemImpl.java:52)
                                                    	at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:504)
                                                    	at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:531)
                                                    	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:207)
                                                    	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:185)
                                                    	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:129)
                                                    	at com.google.android.material.navigation.NavigationView.inflateMenu(NavigationView.java:528)
                                                    	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:327)
                                                    	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:141)
                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
                                                    	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
                                                    	at my.app.myactivity.onCreate(MyActivity.class:178)
                                                    	at android.app.Activity.performCreate(Activity.java:8305)
2023-02-16 13:03:15.480 ResourcesCompat          W  	at android.app.Activity.performCreate(Activity.java:8284)
                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                    	at android.os.Looper.loop(Looper.java:288)
                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by DontTrustMicrosoft-MicrosoftIsAsshole** [comment]
@marcinbln 
you got it:  I used "    <style name="AppTheme" parent="Theme.Material3.DayNight">

And it's working. The colours are totally messed up, the app looks like in "revert color" mode... but no more crash !

**Comment by marcinbln** [comment]
Yep, I struggled with it today as well. If you don't want to use Material3 as a base theme you can also try setting style on the MaterialSwitch directly:

 <com.google.android.material.materialswitch.MaterialSwitch
        **style="@style/Widget.Material3.CompoundButton.MaterialSwitch"**
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
 />

The colors probably will also be messed up but only for one component :D
