### ISSUE TITLE
Error inflating class com.google.android.material.tabs.TabLayout happens on Samsung Galaxy S3 - API 18

### ISSUE THREAD

**Issue by rr0055256** [material-components/material-components-android#340]
Error inflating class com.google.android.material.tabs.TabLayout
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
       at android.app.ActivityThread.access$700(ActivityThread.java:159)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ldjcmu** [comment]
Thanks for the report. I've opened a bug at P1 at https://issuetracker.google.com/issues/131755504

**Comment by ldjcmu** [comment]
Did this newly start occurring in one of the recent alphas? Does it occur both in alpha2 and alpha5? 

And is there any chance you can provide us a github link to a small sample app?

**Comment by ldjcmu** [comment]
We cannot repro this.

**Comment by Arciles** [comment]
Same problem happened to me on Galaxy S5 API21. I can provide more details if it's required.

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.expertech.fieldobservationsdev/net.expertech.fieldobservations.MainActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.google.android.material.tabs.TabLayout
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by dongzhixuanyuan** [comment]
theme must be android:theme="@style/Theme.AppCompat.Light.NoActionBar" or its inherit
