### ISSUE TITLE
[DynamicColors] StrictMode Violation in DynamicColors.applyToActivityIfAvailable

### ISSUE THREAD

**Issue by mtotschnig** [material-components/material-components-android#3413]
When calling applyToActivityIfAvailable in Activity's onCreate, as explained in the documentation, with StrictMode activated, the following violation is raised:

```
        StrictMode policy violation; ~duration=135 ms: android.os.strictmode.DiskWriteViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1615)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:446)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:951)
	at libcore.io.IoBridge.write(IoBridge.java:649)
	at java.io.FileOutputStream.write(FileOutputStream.java:401)
	at java.io.FileOutputStream.write(FileOutputStream.java:379)
	at com.google.android.material.color.ColorResourcesLoaderCreator.create(ColorResourcesLoaderCreator.java:56)
	at com.google.android.material.color.ResourcesLoaderUtils.addResourcesLoaderToContext(ResourcesLoaderUtils.java:35)
	at com.google.android.material.color.ResourcesLoaderColorResourcesOverride.applyIfPossible(ResourcesLoaderColorResourcesOverride.java:66)
	at com.google.android.material.color.ResourcesLoaderColorResourcesOverride.applyIfPossible(ResourcesLoaderColorResourcesOverride.java:50)
	at com.google.android.material.color.DynamicColors.applyToActivityIfAvailable(DynamicColors.java:331)
``` 

**Android API version:** 32

**Material Library version:** 1.10.0-alpha03

**Device:** API 32 emulator

**Comment by dsn5ft** [comment]
@mtotschnig can you provide your full code snippet that uses the DynamicColors class? (including your DynamicColorsOptions)

**Comment by mtotschnig** [comment]
@dsn5ft Sorry for having left this out.
This is how I use it in my project: https://github.com/mtotschnig/MyExpenses/blob/a58000514c9b6bbceb50a3078651fd770bf4cc44/myExpenses/src/main/java/org/totschnig/myexpenses/activity/ExpenseEdit.kt#LL233C1-L238C4
so essentially:
```
            DynamicColors.applyToActivityIfAvailable(
                this,
                DynamicColorsOptions.Builder()
                    .setContentBasedSource(color)
                    .build()
            )
```

**Comment by mtotschnig** [comment]
Method HarmonizedColors.applyToContextIfAvailable suffers from the same problem.
