### ISSUE TITLE
[Tabs] TabLayout render problem

### ISSUE THREAD

**Issue by 3dylson** [material-components/material-components-android#3419]
**Description:** TabLayout cannot be previewed on layout inspector (edit mode) when using Material Library version > 1.7.0 - Render problem:

```
java.lang.NullPointerException: Cannot invoke "android.content.res.BridgeTypedArray.setTheme(android.content.res.Resources$Theme)" because "ta" is null
	at android.content.res.Resources_Theme_Delegate.obtainStyledAttributes(Resources_Theme_Delegate.java:74)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java:1631)
	at android.content.Context.obtainStyledAttributes(Context.java:874)
	at android.widget.TextView.setTextAppearance(TextView.java:3965)
	at androidx.appcompat.widget.AppCompatTextView.setTextAppearance(AppCompatTextView.java:216)
	at com.google.android.material.textview.MaterialTextView.setTextAppearance(MaterialTextView.java:106)
	at android.widget.TextView.setTextAppearance(TextView.java:3954)
	at androidx.core.widget.TextViewCompat.setTextAppearance(TextViewCompat.java:289)
	at com.google.android.material.tabs.TabLayout$TabView.updateTab(TabLayout.java:2824)
	at com.google.android.material.tabs.TabLayout$TabView.update(TabLayout.java:2853)
	at com.google.android.material.tabs.TabLayout$TabView.setTab(TabLayout.java:2765)
	at com.google.android.material.tabs.TabLayout.createTabView(TabLayout.java:1725)
	at com.google.android.material.tabs.TabLayout.newTab(TabLayout.java:1008)
	at com.google.android.material.tabs.TabLayout.addTabFromItemView(TabLayout.java:876)
	at com.google.android.material.tabs.TabLayout.addViewInternal(TabLayout.java:1782)
	at com.google.android.material.tabs.TabLayout.addView(TabLayout.java:1772)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1131)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:353)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:450)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:122)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:727)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:884)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:195)
	at com.android.tools.idea.rendering.RenderExecutor$PriorityRunnable.run(RenderExecutor.kt:293)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Material Library version:** 1.9.0

**Comment by 3dylson** [comment]
> Please update your android studio #3007

I already have the latest version of Android Studio:

Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 aarch64

**Comment by imhappi** [comment]
If it is not working, please file a bug with Android Studio https://developer.android.com/studio/report-bugs
