### ISSUE TITLE
Error while compiling an app with 1.1.0-alpha06 (Program type already present: androidx.transition.R)

### ISSUE THREAD

**Issue by EdricChan03** [material-components/material-components-android#343]
After bumping the version of the Material Components for Android library to `1.1.0-alpha06` from `1.1.0-alpha05`, I have encountered the error as specified in the title.

The full error log is as shown below:
```
Caused by: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: androidx.transition.R
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:445)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:336)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:55)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:105)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 6 more
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: androidx.transition.R
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:435)
	... 28 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.t.a(:55)
	at com.android.tools.r8.D8.run(:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
	... 30 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: androidx.transition.R
	at com.android.tools.r8.utils.Reporter.a(:21)
	at com.android.tools.r8.utils.Reporter.a(:7)
	at com.android.tools.r8.utils.t.a(:36)
	... 32 more
```

I'm currently not using the AndroidX Transition library.

This can be reproduced [here](https://github.com/EdricChan03/StudyBuddy-android/tree/repro/program-type-transition-issue) on the `repro/program-type-transition-issue` branch, or by simply bumping the version of the library to `1.1.0-alpha06`.

**Comment by ethan627hsu** [comment]
@EdricChan03, based on the information I have gathered about building the `1.1.0-alpha06` repository (and utilizing your repository), here is what I have concluded so far:
* In general, developers utilizing the variant of the library have not faced building issues
* When building the variant on a generic Android project, I faced no issues
* After using your provided repository, I builded it and still was not able to find the error 

Based on my assessments, it seems to me that the issue at hand is system-specific (problematic to only your system/setup).  In order to reset Gradle's state on your copy of your app repository, you can clean your project, and then rebuild it. In addition if those options do not work, you can try invalidating caches, and syncing gradle files with project. All of these commands can be accessed through the Android Studio's action prompt, by this command `ctrl/cmd + shift + a`

If you have any other context to provide about the situation, it would be good to respond with it. I hope my explanation aids you in solving your issue! 🚑

**Comment by EdricChan03** [comment]
Running `Build > Rebuild project` has cleared the error. Thanks @ethan627hsu! I'll close this issue.

**Comment by ethan627hsu** [comment]
Cool, glad to help you out, congrats on your fix 🎊
