### ISSUE TITLE
[Material Carousel] Null Pointer Exception

### ISSUE THREAD

**Issue by CodeWithAthari** [material-components/material-components-android#3532]
**Description:** It was working fine but when i made an app for someone & he published on playstore we got this error:
Attempt to invoke virtual method 'com.google.android.material.carousel.KeylineState com.google.android.material.carousel.KeylineStateList.getDefaultState()' on a null object reference\

App simply crashes because carousel is on main activity
**complete logs:**\
Attempt to invoke virtual method 'com.google.android.material.carousel.KeylineState com.google.android.material.carousel.KeylineStateList.getDefaultState()' on a null object reference
                                                                                                    	at com.google.android.material.carousel.CarouselLayoutManager.computeHorizontalScrollExtent(CarouselLayoutManager.java:1024)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.computeHorizontalScrollExtent(RecyclerView.java:2027)
                                                                                                    	at android.view.View.canScrollHorizontally(View.java:21461)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10378)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10348)
                                                                                                    	at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:74)
                                                                                                    	at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:91)
                                                                                                    	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:9095)
                                                                                                    	at android.view.View.createAccessibilityNodeInfoInternal(View.java:9056)
                                                                                                    	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:32408)
                                                                                                    	at android.view.View.createAccessibilityNodeInfo(View.java:9039)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1520)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1543)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1543)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1543)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1543)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1543)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1543)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1543)
                                                                                                    	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1309)
                                                                                                    	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:416)
                                                                                                    	at android.view.AccessibilityInteractionController.-$$Nest$mfindAccessibilityNodeInfoByAccessibilityIdUiThread(Unknown Source:0)
                                                                                                    	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1713)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by imhappi** [comment]
Hi @CodeWithAthari ! What version are you using? This looks like the same issue as https://github.com/material-components/material-components-android/issues/3372 and should have been fixed.

Will close this issue, feel free to re-open if it hasn't been fixed

**Comment by CodeWithAthari** [comment]
I'm using version 1.9.0 & I don't think it's fixed

**Comment by CodeWithAthari** [comment]
Should i upgrade my project to alpha?
