### ISSUE TITLE
FloatingActionButton rendering problem.

### ISSUE THREAD

**Issue by yamin335** [material-components/material-components-android#368]
When I am adding a FAB inside a layout the FAB is blocking the total view because of rendering the FAB.

Caused error:

 java.lang.IllegalArgumentException: java.lang.ClassCastException@2e73a48b
	at sun.reflect.GeneratedMethodAccessor279.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at android.animation.PropertyValuesHolder_Delegate.callMethod(PropertyValuesHolder_Delegate.java:108)
	at android.animation.PropertyValuesHolder_Delegate.nCallFloatMethod(PropertyValuesHolder_Delegate.java:143)
	at android.animation.PropertyValuesHolder.nCallFloatMethod(PropertyValuesHolder.java)
	at android.animation.PropertyValuesHolder.access$400(PropertyValuesHolder.java:38)
	at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1387)
	at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:674)
	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:637)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1069)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1088)
	at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
	at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1081)
	at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1142)
	at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1227)
	at android.animation.AnimatorSet.start(AnimatorSet.java:729)
	at android.animation.AnimatorSet.start(AnimatorSet.java:684)
	at android.animation.StateListAnimator.start(StateListAnimator.java:188)
	at android.animation.StateListAnimator.setState(StateListAnimator.java:181)
	at android.view.View.drawableStateChanged(View.java:21105)
	at android.widget.ImageView.drawableStateChanged(ImageView.java:1294)
	at com.google.android.material.floatingactionbutton.FloatingActionButton.drawableStateChanged(FloatingActionButton.java:805)
	at android.view.View.refreshDrawableState(View.java:21160)
	at android.view.View.dispatchAttachedToWindow(View.java:18379)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:335)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:391)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:195)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:540)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:666)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by leticiarossi** [comment]
Hiello, could you provide more context about your issue such as screenshots of the problem, source code, and library and API versions?
