### ISSUE TITLE
[Slider] slider with label formatter crashes

### ISSUE THREAD

**Issue by manabu-nakamura** [material-components/material-components-android#3847]
**Description:** The slider with a label formatter crashes:
```
java.lang.NumberFormatException: For input string: "12.5K"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
    at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
    at java.lang.Float.parseFloat(Float.java:451)
    at com.google.android.material.slider.BaseSlider.positionLabel(BaseSlider.java:2674)
    at com.google.android.material.slider.BaseSlider.setValueForLabel(BaseSlider.java:2668)
    at com.google.android.material.slider.BaseSlider.ensureLabelsAdded(BaseSlider.java:2655)
    at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:2017)
    ...
```
https://github.com/material-components/material-components-android/commit/5e5eee01bd11f14cf5fbccd17bc18c5926d74774

**Expected behavior:** The slider with a label formatter doesn't crash.

**Minimal sample app repro:** Catalog app (SliderDiscreteDemoFragment)

**Android API version:** 34

**Material Library version:** 1.12.0-alpha01

**Device:** Emulator 32.1.15 (API 32)

**Comment by imhappi** [comment]
Rolled back in https://github.com/material-components/material-components-android/commit/83a7ed8dd59c9b66b7f6c33b8742adfa60704561

**Comment by manabu-nakamura** [comment]
Reopen #2869.
