### ISSUE TITLE
App crashes on launch with Material-1.1.0 and minifyEnabled true

### ISSUE THREAD

**Issue by adityabhaskar** [material-components/material-components-android#385]
My app crashes on launch since I added the dependency for latest Material library:

```
implementation 'com.google.android.material:material:1.1.0-alpha06'
```

This only happens when I test it with `minifyEnabled true`. It works fine without minification.

The crash log is at the bottom - it never appears to touch my code, apparently crashing before even getting to it.

I'm guessing the material library uses reflection, and I need to add more rules to my proguard rules file. I could find these ones from this repository, but they haven't resolved the issue:
```
# MaterialComponentsViewInflater inflates Material Components rather than their AppCompat counterparts.
-keep class com.google.android.material.theme.MaterialComponentsViewInflater { *; }


# CoordinatorLayout resolves the behaviors of its child components with reflection.
-keep public class * extends androidx.coordinatorlayout.widget.CoordinatorLayout$Behavior {
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>();
}

# Make sure we keep annotations for CoordinatorLayout's DefaultBehavior
-keepattributes RuntimeVisible*Annotation*
```
Really appreciate any help to resolve this issue!

---

The crash log:
```
java.lang.LinkageError: Method void g.a.a.g.e.a() overrides final method in class Lb/n/I; (declaration of 'g.a.a.g.e' appears in /data/app/net.c306.ttsuper-Xpl60mXuZR_TLN-idGkg1Q==/base.apk)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(SourceFile:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by cketcham** [comment]
Could you de-obfuscate the stacktrace with retrace? That would make it easier for us to see what's going on.

**Comment by cketcham** [comment]
To me this looks like maybe it's trying to create an instance of an Activity?

**Comment by adityabhaskar** [comment]
Hi Cameron

Apologies for that. I pasted from the wrong window.

The deobfuscated stack trace is below:

```
    java.lang.LinkageError: g.a.a.g.e
        at net.c306.super.view.ui.MainActivity$searchStackViewModel$2.net.c306.super.search.SearchStateViewModel invoke()(SourceFile:180)
        at net.c306.super.view.ui.MainActivity$searchStackViewModel$2.java.lang.Object invoke()(SourceFile:155)
        at kotlin.SynchronizedLazyImpl.a(SourceFile:74)
        at net.c306.super.view.ui.MainActivity.net.c306.super.search.SearchStateViewModel getSearchStackViewModel()(SourceFile)
        at net.c306.super.view.ui.MainActivity.void handleIntent(android.content.Intent)(SourceFile:1625)
        at net.c306.super.view.ui.MainActivity.void initDataAndView(boolean,boolean)(SourceFile:1777)
        at net.c306.super.view.ui.MainActivity.void initDataAndView$default(net.c306.super.view.ui.MainActivity,boolean,boolean,int,java.lang.Object)(SourceFile:1751)
        at net.c306.super.view.ui.MainActivity.void onCreate(android.os.Bundle)(SourceFile:304)
        at android.app.Activity.performCreate(Activity.java:6251)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

The statement at line 180 is:
```
    private val searchStackViewModel: SearchStateViewModel by lazy {
        ViewModelProviders.of(this).get(SearchStateViewModel::class.java)
    }
```

This statement works fine without the library in dependencies, but fails with it included. The `this` refers to the activity which extends from `AppCompatActivity`. My guess is that the material library modifies AppCompatActivity[^1], and that may be causing the ViewModel creation to fail.

[^1]: A few activity method signatures changed after I included the library, e.g.: onCreateOptionsMenu, onSaveInstanceState, etc.

**Comment by adityabhaskar** [comment]
Just checked the library gradle file. It uses `1.1.0-alpha05` of AppCompat:
```
appCompat             : '1.1.0-alpha05', // Needed for CSL + theme attr fixes
```

My app currently includes the stable v `1.0.2`. This may have something to do with the problem.

I also use the stable `2.0.0` versions of `androidx.lifecycle.*` components. I tried after upgrading them to `2.1.0-beta01`, but that still causes the crash.

**Comment by adityabhaskar** [comment]
Is there an update on this?

Is AppCompat `1.1.0-alpha` a requirement for using 1.1.x-alpha of this material components library?

**Comment by adityabhaskar** [comment]
Ok, figured out the issue.

`Material 1.1.0-alpha` uses `AppCompat 1.1.0-alpha` uses `LifeCycle 2.1.0-...` which has breaking changes from `LifeCycle 2.0.0`. That is causing the app crash on ViewModel creation.

Nothing to do specifically with the Material library, so closing.
