### ISSUE TITLE
[BaseSlider] LabelFormatter regression with String[] values in 1.12.0-alpha01

### ISSUE THREAD

**Issue by kuznikowski** [material-components/material-components-android#3877]
**Description:** App doesn't show any label/crashed when sliding. Stack trace below. Used to work in previous versions.

**Sample part of code:**

```
final Slider slider = extensionToast.findViewById(R.id.extension_slider);
final String[] periods = new String[]{"1 day", "1 week", "1 month", "1/2 year", "1 year"};
slider.setLabelFormatter(value -> periods[(int) value]);
```

**Stack trace:** 

```
java.lang.NumberFormatException: For input string: "my_string_here"
                                                                                                    	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
                                                                                                    	at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
                                                                                                    	at java.lang.Float.parseFloat(Float.java:455)
                                                                                                    	at com.google.android.material.slider.BaseSlider.positionLabel(BaseSlider.java:2674)
                                                                                                    	at com.google.android.material.slider.BaseSlider.setValueForLabel(BaseSlider.java:2668)
                                                                                                    	at com.google.android.material.slider.BaseSlider.ensureLabelsAdded(BaseSlider.java:2655)
                                                                                                    	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:2017)
```

**Android API version:** 33

**Material Library version:** 1.12.0-alpha01, worked correctly until version 1.11.0-rc01

**Comment by paulfthomas** [comment]
Fixed in https://github.com/material-components/material-components-android/commit/144b5159ce414211cf37946ecb819cc976cedae1
