### ISSUE TITLE
Restarter must be created only during owner's initialization stage

### ISSUE THREAD

**Issue by richanshah** [material-components/material-components-android#389]
We're transitioning from github issues to a public buganizer component. Rather
than submitting a bug here on github, please file any bugs or feature requests
at https://issuetracker.google.com/issues/new?component=439535.

I am using a FragmentActivity and sometimes on Crashlytics, I am able to see an exception Fatal Exception: java.lang.RuntimeException: Unable to pause activity

I have main dashboard with 3 different recycleview data ,when i click to detailed fragment and come back to previous using mActivity.onbakcPressed () , at that time i am getting this issue ,can any one help me with this?

Here is the stack trace of this crash.

`Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.avail.easyloans.android/com.avail.easyloans.feature.marketplace.activities.ActivityMarketplace}: java.lang.IllegalStateException: Restarter must be created only during owner's initialization stage
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3471)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3430)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3402)
       at android.app.ActivityThread.access$1300(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5601)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
Caused by java.lang.IllegalStateException: Restarter must be created only during owner's initialization stage
       at androidx.savedstate.SavedStateRegistryController.performRestore(SavedStateRegistryController.java:59)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2522)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:834)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1227)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2612)
       at androidx.fragment.app.FragmentManagerImpl.dispatchPause(FragmentManagerImpl.java:2588)
       at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:279)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:406)
       at com.avail.easyloans.feature.marketplace.activities.ActivityMarketplace.onPause(ActivityMarketplace.java:351)
       at android.app.Activity.performPause(Activity.java:6467)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1312)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3457)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3430)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3402)
       at android.app.ActivityThread.access$1300(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5601)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)`

**Comment by melaniegoetz** [comment]
Are you utilizing material components / does that appear to be related to the crash ?

**Comment by richanshah** [comment]
No ,I am getting this because of fragment  transition ,when i commented the code below of transition I am not getting that issue, I have finally find the cause of  issue ,I am using androidx but I don't know why there is issue with this 
`public void pushFragment(String tag, Fragment fragment, boolean shouldAnimate, boolean shouldAdd) {
		if (shouldAdd) {
			mStacks.get(tag).push(fragment);
		}
		FragmentManager manager = getSupportFragmentManager();
		FragmentTransaction ft = manager.beginTransaction();
//		if (shouldAnimate)
//
//			ft.setCustomAnimations(R.anim.slide_in_right, R.anim.slide_out_left);
		ft.replace(R.id.container, fragment);
		ft.commit();
		manager.executePendingTransactions();
	}


	public void popFragment() {
		/*
		 *    Select the second last fragment in current tab's stack..
		 *    which will be shown after the fragment transaction given below
		 */
		Fragment fragment = mStacks.get(mCurrentTab).elementAt(mStacks.get(mCurrentTab).size() - 2);

		/*pop current fragment from stack.. */
		mStacks.get(mCurrentTab).pop();

		/* We have the target fragment in hand.. Just show it.. Show a standard navigation animation*/
		FragmentManager manager = getSupportFragmentManager();
		FragmentTransaction ft = manager.beginTransaction();
//		ft.setCustomAnimations(R.anim.slide_in_left, R.anim.slide_out_right);
		ft.replace(R.id.container, fragment);
		ft.commit();
	}
`

**Comment by melaniegoetz** [comment]
Ah, the appropriate channel for General Android usage questions is stackoverflow. These issues are reserved for bugs with the Material components library. For usage questions related to material components, stackoverflow questions can be tagged with material-components-android. Closing this issue for now!
