### ISSUE TITLE
AppBarLayout: Rendering problem with Android Studio Giraffe and Hedgehog

### ISSUE THREAD

**Issue by ArcherEmiya05** [material-components/material-components-android#3913]
**Description:** Whenever `AppBarLayout` is use with `CoordinatorLayout`, the preview render is failing causing it to not load the rest of the view or UI component.

```
java.lang.NoSuchFieldError: ACTION_SCROLL_IN_DIRECTION
	at androidx.core.view.accessibility.AccessibilityNodeInfoCompat$AccessibilityActionCompat.<clinit>(AccessibilityNodeInfoCompat.java:748)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.updateAccessibilityActions(AppBarLayout.java:1846)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.setHeaderTopBottomOffset(AppBarLayout.java:2082)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.setHeaderTopBottomOffset(AppBarLayout.java:1458)
	at com.google.android.material.appbar.HeaderBehavior.setHeaderTopBottomOffset(HeaderBehavior.java:158)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1792)
	at com.google.android.material.appbar.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:1439)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1458)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout_Original(CoordinatorLayout.java:918)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java)
	at android.view.View.layout_Original(View.java:23694)
	at android.view.View_Delegate.layout(View_Delegate.java:91)
	at android.view.View.layout(View.java:23680)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout_Original(View.java:23694)
	at android.view.View_Delegate.layout(View_Delegate.java:91)
	at android.view.View.layout(View.java:23680)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout_Original(View.java:23694)
	at android.view.View_Delegate.layout(View_Delegate.java:91)
	at android.view.View.layout(View.java:23680)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout_Original(View.java:23694)
	at android.view.View_Delegate.layout(View_Delegate.java:91)
	at android.view.View.layout(View.java:23680)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:384)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:450)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:122)
	at com.android.tools.rendering.RenderTask.createRenderSession(RenderTask.java:742)
	at com.android.tools.rendering.RenderTask.lambda$inflate$7(RenderTask.java:889)
	at com.android.tools.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:202)
	at com.android.tools.rendering.RenderExecutor$PriorityRunnable.run(RenderExecutor.kt:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

<img width="218" alt="image" src="https://github.com/material-components/material-components-android/assets/38008900/42f78e81-b473-4846-9ec0-63b1e61561b5">

**Expected behavior:** 
It supposed to be look like this

<img width="217" alt="image" src="https://github.com/material-components/material-components-android/assets/38008900/6faad8e2-2b6a-4f44-99e7-0c2f94b6eb76">

**Source code:** 

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/containerView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".presentation.AssetInfoActivity">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            app:navigationIcon="?attr/homeAsUpIndicator"
            app:navigationContentDescription="@string/abc_action_bar_up_description"
            app:layout_scrollFlags="scroll|snap"
            app:menu="@menu/activity_asset_menu"
            app:title="@string/home"
            app:subtitle="@string/home"
            app:titleCentered="true"
            app:subtitleCentered="true" />

    </com.google.android.material.appbar.AppBarLayout>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <androidx.appcompat.widget.LinearLayoutCompat
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <androidx.appcompat.widget.LinearLayoutCompat
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:paddingHorizontal="@dimen/space_14">

                <androidx.appcompat.widget.LinearLayoutCompat
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="center_vertical">

                    <androidx.appcompat.widget.AppCompatImageView
                        android:id="@+id/assetIcon"
                        android:layout_width="60dp"
                        android:layout_height="60dp"
                        android:paddingVertical="@dimen/space_8"
                        android:paddingStart="0dp"
                        android:paddingEnd="@dimen/space_8"
                        android:transitionName="asset_logo"
                        android:src="@drawable/placeholder" />

                    <com.google.android.material.textview.MaterialTextView
                        android:id="@+id/priceUsd"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:ellipsize="end"
                        android:maxLines="1"
                        android:paddingStart="0dp"
                        android:paddingEnd="@dimen/space_8"
                        android:text="@string/empty"
                        android:textColor="?android:textColorHighlight"
                        android:textSize="@dimen/textSize24"
                        android:textStyle="bold" />

                    <com.google.android.material.textview.MaterialTextView
                        android:id="@+id/percentageRateTxt"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:ellipsize="end"
                        android:maxLines="1"
                        android:text="@string/empty"
                        android:textSize="@dimen/textSize16" />

                </androidx.appcompat.widget.LinearLayoutCompat>

                <com.google.android.material.textview.MaterialTextView
                    android:id="@+id/descriptionTxt"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:maxLines="5"
                    android:ellipsize="end"
                    tools:text="@tools:sample/lorem/random" />

                <androidx.appcompat.widget.LinearLayoutCompat
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical">

                    <com.google.android.material.textview.MaterialTextView
                        android:id="@+id/categoryTxt"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textColor="?android:textColorHighlight"
                        android:textStyle="bold"
                        tools:text="@tools:sample/full_names"/>

                    <com.google.android.material.textview.MaterialTextView
                        android:id="@+id/sectorTxt"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textColor="?android:textColorHighlight"
                        android:textStyle="bold"
                        tools:text="@tools:sample/cities" />

                </androidx.appcompat.widget.LinearLayoutCompat>

            </androidx.appcompat.widget.LinearLayoutCompat>

            <com.google.android.material.tabs.TabLayout
                android:id="@+id/tabLayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:tabMode="auto">

                <com.google.android.material.tabs.TabItem
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    tools:text="@tools:sample/cities" />

                <com.google.android.material.tabs.TabItem
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    tools:text="@tools:sample/cities" />

                <com.google.android.material.tabs.TabItem
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    tools:text="@tools:sample/cities" />

                <com.google.android.material.tabs.TabItem
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    tools:text="@tools:sample/cities" />

                <com.google.android.material.tabs.TabItem
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    tools:text="@tools:sample/cities" />

            </com.google.android.material.tabs.TabLayout>

            <androidx.viewpager2.widget.ViewPager2
                android:id="@+id/viewPagerContainer"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </androidx.appcompat.widget.LinearLayoutCompat>

    </FrameLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Minimal sample app repro:** Please consider attaching a minimal sample app that reproduces the issue. This will help narrow down the conditions required for reproducing the issue, and it will speed up the bug fix process. You may attach a zip file of the sample app or link to a GitHub repo that contains the sample app.

**Android API version:** 21 and above

**Material Library version:** 1.10.0

**Device:** N/A

**Comment by drchen** [comment]
Reported to the Android Studio team: https://issuetracker.google.com/issues/315159092, please keep tracking the issue there.

I'll close the issue.
