### ISSUE TITLE
Crash on API 15 from ShadowRenderer/MaterialShapeDrawable

### ISSUE THREAD

**Issue by maltaisn** [material-components/material-components-android#3965]
**Description:** I'm having an "UnsupportedOperationException" crash. I'm not sure where it originates from, but the sample app is simple enough. The crash doesn't occur on API 21 & 34 but does on API 15. I haven't tested other versions. I'm not sure if it is planned to continue supporting down to API 14 since the minSdk for 1.12 and up appears to be 19? I opened a bug report anyway, if it can help.

Here's the stacktrace:
```text
E  FATAL EXCEPTION: main
   java.lang.UnsupportedOperationException
   	at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:413)
   	at com.google.android.material.shadow.ShadowRenderer.drawCornerShadow(ShadowRenderer.java:176)
   	at com.google.android.material.shape.ShapePath$ArcShadowOperation.draw(ShapePath.java:430)
   	at com.google.android.material.shape.ShapePath$1.draw(ShapePath.java:263)
   	at com.google.android.material.shape.ShapePath$ShadowCompatOperation.draw(ShapePath.java:368)
   	at com.google.android.material.shape.MaterialShapeDrawable.drawCompatShadow(MaterialShapeDrawable.java:1099)
   	at com.google.android.material.shape.MaterialShapeDrawable.maybeDrawCompatShadow(MaterialShapeDrawable.java:978)
   	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:958)
   	at android.graphics.drawable.InsetDrawable.draw(InsetDrawable.java:158)
   	at android.view.View.draw(View.java:10963)
   	at android.widget.FrameLayout.draw(FrameLayout.java:450)
   	at android.view.View.getDisplayList(View.java:10417)
   	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
   	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
   	at android.view.View.getDisplayList(View.java:10415)
   	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
   	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
   	at android.view.View.draw(View.java:10981)
   	at android.widget.FrameLayout.draw(FrameLayout.java:450)
   	at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:2328)
   	at android.view.View.getDisplayList(View.java:10417)
   	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
   	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
   	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
   	at android.view.View.getDisplayList(View.java:10415)
   	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
   	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
   	at android.view.View.draw(View.java:10981)
   	at android.widget.FrameLayout.draw(FrameLayout.java:450)
   	at android.view.View.getDisplayList(View.java:10417)
   	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
   	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
   	at android.view.View.getDisplayList(View.java:10415)
   	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
   	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
   	at android.view.View.getDisplayList(View.java:10415)
   	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
   	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
   	at android.view.View.getDisplayList(View.java:10415)
   	at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
   	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
   	at android.view.View.draw(View.java:10981)
   	at android.widget.FrameLayout.draw(FrameLayout.java:450)
   	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2126)
   	at android.view.View.getDisplayList(View.java:10417)
   	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:841)
   	at android.view.ViewRootImpl.draw(ViewRootImpl.java:1910)
   	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1634)
   	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
   	at android.os.Handler.dispatchMessage(Handler.java:99)
   	at android.os.Looper.loop(Looper.java:137)
   	at android.app.ActivityThread.main(ActivityThread.java:4424)
   	at java.lang.reflect.Method.invokeNative(Native Method)
   	at java.lang.reflect.Method.invoke(Method.java:511)
   	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
   	at dalvik.system.NativeStart.main(Native Method)
```

**Minimal sample app repro:** Build the demo app from https://github.com/maltaisn/calcdialoglib the app should crash on startup on API 15.

**Android API version:** 15

**Material Library version:** 1.3.0 through 1.12.0-alpha02

**Device:** Emulator API 15

**Comment by dsn5ft** [comment]
@maltaisn thanks for the report, but as you hinted at we no longer support API 15 so we will not be prioritizing fixes for these lower API levels.
