### ISSUE TITLE
[Slider] Setting large values to the max amount causes issues

### ISSUE THREAD

**Issue by the-alchemist-07** [material-components/material-components-android#4152]
**Description:** 
We have created a slider in our app, which was actually used to select an amount. We have multiple items with their own minAmount and maxAmount values, and on the selection of the amount from the slider, we will only show the items whose minAmount to maxAmount range covers the selected amount. 

The issue arises when setting large values (such as a 9 digit number) as the valueTo for the slider. I will describe the exact issue we have faced. By our logic, we are setting the valueFrom as 0 and valueTo as 500050000. We are also setting the stepSize as 50000. The step size is hardcoded, and the valueFrom and valueTo are dynamically calculated to make the range in between them evenly divisible by the stepSize, which is 50000 (or else it was giving an exception). 

So in the scenario described above, the difference between the valueTo(500050000) and valueFrom(0) is properly divisible by the stepSize(50000).
(500050000 - 0) / 50000 = 10001
But, when we were running the project and opening the screen with the slider in it, it was giving IllegalStateException.

The full exception log is given below:
`FATAL EXCEPTION: main
Process: com.example.sliderissue, PID: 26658
java.lang.IllegalStateException: The stepSize(50000.0) must be 0, or a factor of the valueFrom(0.0)-valueTo(5.00049984E8) range
	at com.google.android.material.slider.BaseSlider.validateStepSize(BaseSlider.java:567)
    at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:627)
    at com.google.android.material.slider.BaseSlider.maybeCalculateTicksCoordinates(BaseSlider.java:1724)
	at com.google.android.material.slider.BaseSlider.updateTrackWidth(BaseSlider.java:1745)
	at com.google.android.material.slider.BaseSlider.onSizeChanged(BaseSlider.java:1715)
	at android.view.View.sizeChange(View.java:25947)
	at android.view.View.setFrame(View.java:25880)
	at android.view.View.layout(View.java:25731)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:25737)
	at android.view.ViewGroup.layout(ViewGroup.java:6818)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25737)
	at android.view.ViewGroup.layout(ViewGroup.java:6818)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25737)
	at android.view.ViewGroup.layout(ViewGroup.java:6818)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25737)
	at android.view.ViewGroup.layout(ViewGroup.java:6818)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25737)
	at android.view.ViewGroup.layout(ViewGroup.java:6818)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1075)
	at android.view.View.layout(View.java:25737)
	at android.view.ViewGroup.layout(ViewGroup.java:6818)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:5193)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4466)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3239)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11197)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
	at android.view.Choreographer.doFrame(Choreographer.java:1055)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

When I checked inside the slider library, it was using the float values everywhere. The given valueTo(500050000) was actually converted to 500049984. When I checked on the internet, I have seen someone mentioning that float data type is very much prone to precision errors. 

So my doubt is, why a material library from google is using float data type, if it has problems like this. Can we fix this by updating the library to use Double or BigDecimal?

**Expected behavior:** 
Whatever value we throw to it, the slider is supposed to handle them. Please correct me if I am wrong.

**Source code:**
```
    private void calculateMinMaxValuesForSlider(float minAmount, float maxAmount) {
        int stepSize = viewModel.stepSize;
        int sliderMinAmount = (int) minAmount;
        int sliderMaxAmount = (int) maxAmount;

        // Calculating the minAmount according to step interval
        if (sliderMinAmount < stepSize)
            sliderMinAmount = 0;
        else if (sliderMinAmount > stepSize && sliderMinAmount % stepSize != 0) {
            int roundedDownIntervalValue = (int) (sliderMinAmount / stepSize);
            sliderMinAmount = stepSize * roundedDownIntervalValue;
        }

        // Calculating the maxAmount according to step interval
        if (sliderMaxAmount < stepSize)
            sliderMaxAmount = stepSize;
        else if (sliderMaxAmount > stepSize && sliderMaxAmount % stepSize != 0) {
            float intervalValue = (float) sliderMaxAmount / stepSize;
            int roundedUpIntervalValue = (int) Math.ceil(intervalValue);
            sliderMaxAmount = stepSize * roundedUpIntervalValue;
        }

        Log.d("TEST111", "Min value: " + sliderMinAmount);
        Log.d("TEST111", "Max value: " + sliderMaxAmount);

        // Set the values to the slider
        binding.sliderAmount.setValueFrom(sliderMinAmount);
        binding.sliderAmount.setValueTo(sliderMaxAmount);

        // Check and confirming that the stepSize is suitable and is properly divisible
        // by the difference of min and max amounts. If not, this will make the slider
        // to cause IllegalStateException and will crash.
        // Doc: https://developer.android.com/reference/com/google/android/material/slider/Slider#setStepSize(float)
        if ((sliderMaxAmount - sliderMinAmount) % stepSize == 0) {
            Log.d("TEST111", "Step size: " + stepSize);
            binding.sliderAmount.setStepSize(stepSize);
        } else Log.d("TEST111", "Step size: --");
    }
```
We have converted the original min and max values taken as parameters into int datatype, to avoid any precision errors in our calculations. Even though we are setting 500050000 as the max value to the slider, the slider is treating its max value as 500049984 or 5.00049984E8

**Minimal sample app repro:** 
This is not the original project. Since I didn't have the permission to share the original project, I have created a simple project which will recreate the same issue.
https://github.com/the-alchemist-07/material-slider-issue

**Android API version:** 
I was testing on Android-14 in a Samsung device. But I think this issue will occur in any device irrespective of the Android version.

**Material Library version:** 
Tested with two versions of material library, 1.6.0 and 1.11.0

**Device:** 
I tested it on Samsung Galaxy S21 FE 5G (SM-G990B2/DS) and some other devices. This is occurring in all devices.

**Comment by ymarian** [comment]
Hi, 
This isn't slider problem yes float cannot represent a number that big accurately. Lots of Java APIs use floats cause it's more performant than the alternatives mentioned and well suited for majority of use cases. 

In your case just divide your values by 5000 when you use it in Slider and multiply by 5000 when you need to convert back, for example in your label formatter for Slider.

**Comment by the-alchemist-07** [comment]
Ok. Thanks for the suggestion 👍
