### ISSUE TITLE
[Android] Crash happens when running for the first time with apptentive-react-native v6.8.0

### ISSUE THREAD

**Issue by EliG-TA** [material-components/material-components-android#4215]
**Description:**  
```
FATAL EXCEPTION: main
Process: XYZ, PID: 14565
java.lang.IllegalArgumentException: com.google.android.material.dialog.MaterialAlertDialogBuilder requires a value for the XYZ:attr/colorSurface attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
    at com.google.android.material.resources.MaterialAttributes.resolveTypedValueOrThrow(MaterialAttributes.java:72)
    at com.google.android.material.color.MaterialColors.getColor(MaterialColors.java:89)
    at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:121)
    at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:104)
    at apptentive.com.android.feedback.textmodal.TextModalDialogFragment.onCreateDialog(TextModalDialogFragment.kt:47)
    at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:647)
    at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:561)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1698)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:492)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8501)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Expected behavior:** Run without crashing the first time

**Android API version:** 28

**Device:** Mac mini 2018 running Sonoma 14.3.1

**Comment by kendrickumstattd** [comment]
Hey hey -- @EliG-TA, could you make sure that your base app theme inherits from a Theme.MaterialComponents theme?

**Comment by kendrickumstattd** [comment]
Going to close due to inactivity, but if that wasn't the fix, feel free to reopen.
