### ISSUE TITLE
[BottomSheet] Back Callback Produces java.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN

### ISSUE THREAD

**Issue by cliuff** [material-components/material-components-android#4307]
**Description:** I received a bug report from one of my users with the following stacktrace
```
java.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN
at android.view.View.sanitizeFloatPropertyValue(View.java:19180)
at android.view.View.sanitizeFloatPropertyValue(View.java:19154)
at android.view.View.setScaleX(View.java:18519)
at com.google.android.material.motion.MaterialBottomContainerBackHelper.updateBackProgress(MaterialBottomContainerBackHelper.java:88)
at com.google.android.material.motion.MaterialBottomContainerBackHelper.updateBackProgress(MaterialBottomContainerBackHelper.java:69)
at com.google.android.material.bottomsheet.BottomSheetBehavior.updateBackProgress(BottomSheetBehavior.java:1608)
at com.google.android.material.motion.MaterialBackOrchestrator$Api34BackCallbackDelegate$1.onBackProgressed(MaterialBackOrchestrator.java:137)
at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackStarted$0(WindowOnBackInvokedDispatcher.java:329)
at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda5.onProgressUpdate(Unknown Source:2)
at android.window.BackProgressAnimator.updateProgressValue(BackProgressAnimator.java:161)
at android.window.BackProgressAnimator.-$$Nest$mupdateProgressValue(Unknown Source)
at android.window.BackProgressAnimator$1.setValue(BackProgressAnimator.java:61)
at android.window.BackProgressAnimator$1.setValue(BackProgressAnimator.java:57)
at com.android.internal.dynamicanimation.animation.DynamicAnimation.setPropertyValue(DynamicAnimation.java:731)
at com.android.internal.dynamicanimation.animation.DynamicAnimation.doAnimationFrame(DynamicAnimation.java:687)
at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:369)
at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source)
at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:92)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1758)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1769)
at android.view.Choreographer.doCallbacks(Choreographer.java:1273)
at android.view.Choreographer.doFrame(Choreographer.java:1134)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1743)
at android.os.Handler.handleCallback(Handler.java:1013)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:328)
at android.app.ActivityThread.main(ActivityThread.java:9231)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
```

**Android API version:** 34

**Material Library version:** 1.11.0

**Device:** Manufacturer: vivo, Model: V2303A, Product: PD2303, Device(Code name): PD2303

**Comment by dsn5ft** [comment]
Hi @cliuff, I think this should be addressed by:

https://github.com/material-components/material-components-android/commit/122c2966fd4abc867bc74270fcd1366bcdb239e7#diff-46608c4c5c0457eaebe659e9bb0b37f6120cc1252eb4135b16ebfcd4d91d5905

That commit should be included in v1.10.0 and higher, but I see you've listed v1.11.0 as the version you're using. Is it possible the crash report is from an older version of your app which may have used an older version of Material?

**Comment by cliuff** [comment]
@dsn5ft The stacktrace indicates the line number `MaterialBottomContainerBackHelper.java:88`, which matches the latest file that includes the specified commit.

**Comment by cliuff** [comment]
**Lines from branch `release-1.12`**
https://github.com/material-components/material-components-android/blob/88acfcdb63281714d64e863d2e7da3b53b8da9ce/lib/java/com/google/android/material/motion/MaterialBottomContainerBackHelper.java#L76-L90

**Comment by dsn5ft** [comment]
Good point. We could add more early return checks for `scaleX/scaleY != Float.NaN` to be safe, but I'm confused at how that could even be happening since we already have the `width <= 0f || height <= 0f` checks.
