### ISSUE TITLE
[Color] Failed to create the ColorResourcesTableCreator.

### ISSUE THREAD

**Issue by brahmkshatriya** [material-components/material-components-android#4472]
**Description:** Applying `DynamicColors` 2nd time, generates error after recreating the activity. The color does not get applied.
```
Failed to create the ColorResourcesTableCreator. 
 java.lang.IllegalArgumentException: Non color resource found: name=com.example.dynamiccolortest:?5/com.example.dynamiccolortest:color/material_personalized_color_on_secondary, typeId=5
  at com.google.android.material.color.ColorResourcesTableCreator.create(ColorResourcesTableCreator.java:90)
  at com.google.android.material.color.ColorResourcesLoaderCreator.create(ColorResourcesLoaderCreator.java:46)
  at com.google.android.material.color.ResourcesLoaderUtils.addResourcesLoaderToContext(ResourcesLoaderUtils.java:35)
  at com.google.android.material.color.ResourcesLoaderColorResourcesOverride.applyIfPossible(ResourcesLoaderColorResourcesOverride.java:49)
  at com.google.android.material.color.DynamicColors.applyToActivityIfAvailable(DynamicColors.java:310)
  at com.google.android.material.color.DynamicColors$DynamicColorsActivityLifecycleCallbacks.onActivityPreCreated(DynamicColors.java:451)
  at android.app.Application.dispatchActivityPreCreated(Application.java:356)
  at android.app.Activity.dispatchActivityPreCreated(Activity.java:1505)
  at android.app.Activity.performCreate(Activity.java:8947)
  at android.app.Activity.performCreate(Activity.java:8938)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1536)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
  at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6242)
  at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6133)
  at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:80)
  at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
  at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
  at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
  at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:70)
  at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6199)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2605)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loopOnce(Looper.java:232)
  at android.os.Looper.loop(Looper.java:317)
  at android.app.ActivityThread.main(ActivityThread.java:8592)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Expected behavior:**  Color gets applied.

**Minimal Sample code:** 
```kotlin
class MainActivity : AppCompatActivity() {

    private val colors = listOf(Color.RED, Color.GREEN, Color.BLUE)
    private fun applyColor(){
        val color = colors.random()
        val options = DynamicColorsOptions.Builder()
            .setContentBasedSource(color)
            .build()
        DynamicColors.applyToActivitiesIfAvailable(application, options)
        recreate()
    }
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        findViewById<Button>(R.id.button).setOnClickListener { applyColor() }
    }
}
```

**Comment by brahmkshatriya** [comment]
I also got this error on [my app](https://github.com/brahmkshatriya/echo/blob/main/app/src/main/java/dev/brahmkshatriya/echo/EchoApplication.kt#L70-L95)
```
Failed to create the ColorResourcesTableCreator.
 java.lang.ArrayIndexOutOfBoundsException: src.length=132 srcPos=0 dst.length=135 dstPos=2 length=-124
  at java.lang.System.arraycopy(Native Method)
  at com.google.android.material.color.ColorResourcesTableCreator.stringToByteArrayUtf8(ColorResourcesTableCreator.java:616)
  at com.google.android.material.color.ColorResourcesTableCreator.access$800(ColorResourcesTableCreator.java:40)
  at com.google.android.material.color.ColorResourcesTableCreator$StringPoolChunk.processString(ColorResourcesTableCreator.java:299)
  at com.google.android.material.color.ColorResourcesTableCreator$StringPoolChunk.<init>(ColorResourcesTableCreator.java:223)
  at com.google.android.material.color.ColorResourcesTableCreator$PackageChunk.<init>(ColorResourcesTableCreator.java:347)
  at com.google.android.material.color.ColorResourcesTableCreator$ResTable.<init>(ColorResourcesTableCreator.java:140)
  at com.google.android.material.color.ColorResourcesTableCreator.create(ColorResourcesTableCreator.java:114)
  at com.google.android.material.color.ColorResourcesLoaderCreator.create(ColorResourcesLoaderCreator.java:46)
  at com.google.android.material.color.ResourcesLoaderUtils.addResourcesLoaderToContext(ResourcesLoaderUtils.java:35)
  at com.google.android.material.color.ResourcesLoaderColorResourcesOverride.applyIfPossible(ResourcesLoaderColorResourcesOverride.java:49)
  at com.google.android.material.color.DynamicColors.applyToActivityIfAvailable(DynamicColors.java:310)
  at com.google.android.material.color.DynamicColors$DynamicColorsActivityLifecycleCallbacks.onActivityPreCreated(DynamicColors.java:451)
  at android.app.Application.dispatchActivityPreCreated(Application.java:356)
  at android.app.Activity.dispatchActivityPreCreated(Activity.java:1505)
  at android.app.Activity.performCreate(Activity.java:8947)
  at android.app.Activity.performCreate(Activity.java:8938)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1536)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
  at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6242)
  at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6133)
  at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:80)
  at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
  at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
  at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
  at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:70)
  at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6199)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2605)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loopOnce(Looper.java:232)
  at android.os.Looper.loop(Looper.java:317)
  at android.app.ActivityThread.main(ActivityThread.java:8592)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
  ```

**Comment by brahmkshatriya** [comment]
any updates @hunterstich

**Comment by brahmkshatriya** [comment]
@pubiqq can you please look at this?

**Comment by pubiqq** [comment]
> ```kotlin
> class MainActivity : AppCompatActivity() {
>
>     // ...
> 
>     private fun applyColor(){
>         // ...
>         DynamicColors.applyToActivitiesIfAvailable(application, options)
>         recreate()
>     }
>     
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         setContentView(R.layout.activity_main)
>         findViewById<Button>(R.id.button).setOnClickListener { applyColor() }
>     }
> }
> ```

`DynamicColors#applyToActivitiesIfAvailable` is not supposed to be called multiple times. Each time you call this method, you register a _new_ `ActivityLifecycleCallbacks` that calls `DynamicColors#applyToActivityIfAvailable` for each created activity ([doc](https://github.com/material-components/material-components-android/blob/b5ff3020eb0fa07e19a4a36cef95532ac8bd15db/docs/theming/Color.md#apply-dynamic-colors-to-all-activities-in-the-app)). 

In order to apply different dynamic color options to the activity, you just need to call `DynamicColors#applyToActivityIfAvailable` in `Activity#onCreate`. In this case, every time you call `Activity#recreate`, you will have the `applyToActivityIfAvailable` method called with the options you set.

--

However, multiple calls to the `DynamicColors#applyToActivitiesIfAvailable` method shouldn't throw any exceptions, so I'm still going to investigate this issue.

**Comment by pubiqq** [comment]
> I also got this error on [my app](https://github.com/brahmkshatriya/echo/blob/main/app/src/main/java/dev/brahmkshatriya/echo/EchoApplication.kt#L70-L95)
> 
> ```
> Failed to create the ColorResourcesTableCreator.
>  java.lang.ArrayIndexOutOfBoundsException: src.length=132 srcPos=0 dst.length=135 dstPos=2 length=-124
>   at java.lang.System.arraycopy(Native Method)
>   at com.google.android.material.color.ColorResourcesTableCreator.stringToByteArrayUtf8(ColorResourcesTableCreator.java:616)
>   ...
> ```

It looks like some other bug, I'll look into it.

**Comment by pubiqq** [comment]
> [@pubiqq](https://github.com/pubiqq) How do you repro this? I can't repro with the snippet in the original post.

I reproduced that on the "Basic Views Activity" template (Android Studio: "File" -> "New" -> "New project..." -> [Templates: Phone and Tablet] -> "Basic Views Activity").
