### ISSUE TITLE
[NavigationRailView] "NavigationRailView does not support submenus" [NavigationBarMenu.java:58]

### ISSUE THREAD

**Issue by fkelava** [material-components/material-components-android#4484]
**Description:**
Inflating a `NavigationRailView` with a menu containing submenus fails with a `UnsupportedOperationException` as follows:
```
{...}
android.view.InflateException: Binary XML file line #1 in {...}:layout/{...}: Error inflating class com.google.android.material.navigationrail.NavigationRailView
{...}
Caused by: java.lang.UnsupportedOperationException: NavigationRailView does not support submenus
    at com.google.android.material.navigation.NavigationBarMenu.addSubMenu(NavigationBarMenu.java:58)
    at androidx.appcompat.view.SupportMenuInflater$MenuState.addSubMenuItem(SupportMenuInflater.java:552)
    at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:198)
    at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:142)
    at com.google.android.material.navigation.NavigationBarView.inflateMenu(NavigationBarView.java:388)
    at com.google.android.material.navigation.NavigationBarView.<init>(NavigationBarView.java:296)
    at com.google.android.material.navigationrail.NavigationRailView.<init>(NavigationRailView.java:133)
    at com.google.android.material.navigationrail.NavigationRailView.<init>(NavigationRailView.java:128)
    at com.google.android.material.navigationrail.NavigationRailView.<init>(NavigationRailView.java:123)
                                                                                                    	... 29 more
```
Menu layout that causes it to trip up attached below, as well as the overall layout being inflated.

**Expected behavior:**
The layout inflates, as per its documentation [which shows the possibility of inflating menu XML with submenus](https://github.com/material-components/material-components-android/blob/master/docs/components/NavigationRail.md).

**Source code:**
Layout at large:
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/dl_activity_main_constraint"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    >

    <com.google.android.material.navigationrail.NavigationRailView
        android:id="@+id/dl_activity_main_nav_rail"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/dl_nav_drawer_menu"
        />

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:id="@+id/dl_activity_main_coordinator"
        android:layout_width="0dp"
        android:layout_height="match_parent"
        app:layout_constraintStart_toEndOf="@id/dl_activity_main_nav_rail"
        app:layout_constraintEnd_toEndOf="parent"
        >

        <com.google.android.material.appbar.AppBarLayout
            android:id="@+id/dl_activity_main_appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:fitsSystemWindows="true">

            <com.google.android.material.appbar.MaterialToolbar
                android:id="@+id/dl_activity_main_toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="@android:color/transparent"
                android:elevation="0dp"
                app:title="@string/dl_app_name"
                />

            <com.google.android.material.progressindicator.LinearProgressIndicator
                android:id="@+id/dl_activity_main_progress_indicator"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:indeterminate="true"
                app:showAnimationBehavior="inward"
                app:hideAnimationBehavior="outward" />

        </com.google.android.material.appbar.AppBarLayout>

        <androidx.fragment.app.FragmentContainerView
            android:id="@+id/dl_activity_main_fragment_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            />

    </androidx.coordinatorlayout.widget.CoordinatorLayout>

</androidx.constraintlayout.widget.ConstraintLayout>
```

Menu:
`android:icon` on the various items abridged for brevity.
```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:id="@+id/dl_nav_drawer_menu_home"
        android:title="@string/dl_label_nav_home"" />
    <item
        android:id="@+id/dl_nav_drawer_menu_config"
        android:title="@string/dl_label_nav_config" />
    <item
        android:id="@+id/dl_nav_cat_adas"
        android:title="@string/dl_label_nav_cat_adas" >
        <menu>
            <item
                android:id="@+id/dl_nav_drawer_menu_adas_ctrl"
                android:title="@string/dl_label_nav_adas_ctrl" />
            <item
                android:id="@+id/dl_nav_drawer_menu_adas_map"
                android:title="@string/dl_label_nav_adas_map" />
            <item
                android:id="@+id/dl_nav_drawer_menu_adas_select"
                android:title="@string/dl_label_nav_adas_select" />
        </menu>
    </item>
    <item
        android:id="@+id/dl_nav_cat_dynui"
        android:title="@string/dl_label_nav_cat_dynui" >
        <menu>

        </menu>
    </item>
</menu>
```

**Android API version:** 
Target 35, minimum 24.

**Material Library version:** 
1.12.0

**Device:** 
Samsung SM-T515 (Android 11.0 - API 30)

**Comment by fkelava** [comment]
For context, I was playing around with replacing a standard `NavigationView` (i.e. a navigation drawer), in which this same menu inflates seamlessly. It does not occur to me from perusing the MDC-Android docs why a rail should not accept it. The environment is in every way the same between the two.

**Comment by imhappi** [comment]
Hi @fkelava, I see that you are using 1.12.0; we started to support this in 1.13.0-alpha06!

**Comment by fkelava** [comment]
I see. Thank you for the prompt explanation.
