### ISSUE TITLE
[MaterialColors] Resolve attribute colors using Resources

### ISSUE THREAD

**Issue by ologe** [material-components/material-components-android#492]
I'm building a library that desaturates colors when Dark theme is enabled (as described in [Material Docs](https://material.io/design/color/dark-theme.html#ui-application))

Basically, I'm overriding `getColor` and `getColorStateList` in `android.content.res.Resources`, and them returning the requested color desaturated. But when it comes to material widgets, it doesn't work.

So, diving into material widgets, I noticed that the colors are retrieved calling `MaterialColors.getColor` that calls `MaterialAttributes.resolveOrThrow`, and after resolving the attributeId, the color is directly available in `typedValue.data` (line 71). But in this way, the call to`Resources` is skipped and my desaturation methods will never be called.

My solution is to call `ContextCompat.getColor(context, typedValue.resourceId)` instead of `typeValue.data` at line 71 of `MaterialAttributes.java`.

I understand that this can cause some performance impact by retrieving the color another time, but I'm writing this library because a lot of application has dynamic primary and accent colors, and it's a pain to calculate manually the desaturated colors by hand and then add to `night-values`.

Or please let me know if the problem can be resolved in another way.

[Here the desaturation code](https://github.com/ologe/color-desaturation/blob/master/lib/src/main/java/dev/olog/lib/DarkDesaturatedResources.java)

Here's the screenshot
[not desaturated](https://github.com/ologe/color-desaturation/blob/master/img/light_mode.png)
[desaturated](https://github.com/ologe/color-desaturation/blob/master/img/dark_mode.png)

**Comment by drchen** [comment]
Hi, thanks for the suggestion!!

We are having similar internal needs in developing the new version of Material library. Therefore we are discussing internally about adding the support of it. We'll update once we have the final solution/decision.

**Comment by axitasavani** [comment]
Hi, We are getting the same issue relevant to "getColorStateList" this & it has come at the material alert dialog title view

`Caused by java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
       at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)
       at android.widget.TextView.readTextAppearance(TextView.java:3889)
       at android.widget.TextView.<init>(TextView.java:1223)
       at android.widget.TextView.<init>(TextView.java:1112)
       at android.widget.TextView.<init>(TextView.java:1108)
       at com.android.internal.widget.DialogTitle.<init>(DialogTitle.java:41)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:686)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:457)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:467)
       at com.android.internal.app.AlertController.installContent(AlertController.java:281)
       at android.app.AlertDialog.onCreate(AlertDialog.java:440)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:550)
       at android.app.Dialog.show(Dialog.java:391)
       at com.android.facebook.ads.get(ads.java:175)
       at com.ui.activity.MainActivity.onResume(MainActivity.java:458)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416)
       at android.app.Activity.performResume(Activity.java:7585)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4026)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4066)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7127)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
`
File Name: alert_dialog_title_material.xml


`<?xml version="1.0" encoding="utf-8"?>


<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:id="@+id/topPanel"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:orientation="vertical">

    

    <LinearLayout
        android:id="@+id/title_template"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:gravity="center_vertical|start"
        android:paddingStart="?attr/dialogPreferredPadding"
        android:paddingEnd="?attr/dialogPreferredPadding"
        android:paddingTop="@dimen/dialog_padding_top_material">

        <ImageView
            android:id="@+id/icon"
            android:layout_width="32dip"
            android:layout_height="32dip"
            android:layout_marginEnd="8dip"
            android:scaleType="fitCenter"
            android:src="@null" />

        <com.android.internal.widget.DialogTitle ----------[Getting issue in this line]------------
            android:id="@+id/alertTitle"
            android:singleLine="true"
            android:ellipsize="end"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textAlignment="viewStart"
            style="?attr/windowTitleStyle" />
    </LinearLayout>

    <Space
        android:id="@+id/titleDividerNoCustom"
        android:visibility="gone"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dialog_title_divider_material" />
</LinearLayout>`


**Configuration as below**
- at Build.gradle file 


` compileSdkVersion 30
    buildToolsVersion '30.0.3'
    defaultConfig {
        applicationId "com.rollerbannermaker"
        // TODO ONE SIGNLE
        minSdkVersion 19
        targetSdkVersion 30
        vectorDrawables.useSupportLibrary = true
        // Enabling multidex support.
        multiDexEnabled true
    }`

- dependencies Versions

  ``` {
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.3.0'} ```



- Please let me know where we have mistake,bcz there are too many crashes in our app.

![image](https://user-images.githubusercontent.com/44259547/156705853-0ab7ce39-4443-40fb-b7cb-ab0d7882b743.png)
