### ISSUE TITLE
[MaterialCardView] strokeColor do not follow card corner

### ISSUE THREAD

**Issue by LajosNeto** [material-components/material-components-android#498]
**Description:** MaterialCardView stroke color do not follow exactly the card corners, leaving a blank space.

**Source code:** 

     <com.google.android.material.card.MaterialCardView
            android:layout_width="48dp"
            android:layout_height="48dp"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            android:layout_margin="30dp"
            app:strokeColor="#000000"
            app:strokeWidth="2dp"
            app:cardCornerRadius="6dp"/>

**Android API version:** 29

**Material Library version:** 1.1.0

This is the output:

<img width="237" alt="Screen Shot 2019-08-04 at 21 44 22" src="https://user-images.githubusercontent.com/19560506/62433094-0ba93680-b701-11e9-83ac-d92a2ad244da.png">

**Comment by LajosNeto** [comment]
I just updated my version for 1.1.0-alpha09 and it is working correctly.

**Comment by LajosNeto** [comment]
I just updated my version for 1.1.0-alpha09 and it is working correctly.

**Comment by nikitamarysolomanpvt** [comment]
> 1.1.0-alpha09

while using this iam not able to run .
` android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.google.android.material.card.MaterialCardView
    Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class com.google.android.material.card.MaterialCardView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at org.oppia.app.topic.review.ReviewSkillSelectionAdapter.onCreateViewHolder(ReviewSkillSelectionAdapter.kt:20)
        at org.oppia.app.topic.review.ReviewSkillSelectionAdapter.onCreateViewHolder(ReviewSkillSelectionAdapter.kt:14)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7046)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6214)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6097)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6093)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4115)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3521)
        at android.view.View.measure(View.java:23169)`

**Comment by matszrmn** [comment]
**app:contentPadding** worked for me:

https://stackoverflow.com/questions/63360214/problem-with-changing-the-radius-of-corners-in-materialcardview
