### ISSUE TITLE
[MaterialButton] causes the layout preview to not render

### ISSUE THREAD

**Issue by MarkNjunge** [material-components/material-components-android#508]
**Description:** Adding a MaterialButton to a layout causes the layout preview to not render

**Expected behavior:** The preview renders.
**Without button**
![studio64_Zk4hnDA4Zt](https://user-images.githubusercontent.com/19492506/62539704-876cc580-b85e-11e9-84a3-32718baf313f.png)
 
**With button**
![studio64_4e7eNn9J2X](https://user-images.githubusercontent.com/19492506/62539747-a1a6a380-b85e-11e9-943a-f63b8725ae50.png)

**Stacktrace**
```
java.lang.IllegalArgumentException: java.lang.ClassCastException@74ede7a7
	at sun.reflect.GeneratedMethodAccessor729.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at android.animation.PropertyValuesHolder_Delegate.callMethod(PropertyValuesHolder_Delegate.java:108)
	at android.animation.PropertyValuesHolder_Delegate.nCallFloatMethod(PropertyValuesHolder_Delegate.java:143)
	at android.animation.PropertyValuesHolder.nCallFloatMethod(PropertyValuesHolder.java)
	at android.animation.PropertyValuesHolder.access$400(PropertyValuesHolder.java:38)
	at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1387)
	at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
	at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1339)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
	at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1490)
	at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1163)
	at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1146)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1046)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer_Delegate.doFrame(Choreographer_Delegate.java:66)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:559)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:425)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:120)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:151)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:133)
	at com.android.tools.idea.rendering.RenderTask.lambda$null$8(RenderTask.java:755)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Source code:** Any button code
```XML
    <com.google.android.material.button.MaterialButton
        android:id="@+id/btnBuy"
        android:layout_width="match_parent"
        android:layout_height="56dp"
        android:layout_marginLeft="32dp"
        android:layout_marginTop="32dp"
        android:layout_marginRight="32dp"
        android:layout_marginBottom="32dp"
        android:text="Buy" />
```

**Android API version:** 28

**Material Library version:** 1.1.0-alpha09

Occurs on Android Studio 3.4.2

**Comment by cketcham** [comment]
this is the duplicate that we are tracking: https://issuetracker.google.com/issues/134566530
