### ISSUE TITLE
[TextView, FloatingActionButton] App crashes when colorAccent not specified

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [material-components/material-components-android#565]
I switched one of my apps to `com.google.android.material:material:1.1.0-alpha09` and updated the styles. However, the app started to crash when I removed this from my styles.xml:
```
<item name="colorAccent">@color/colorAccent</item>
```

As per the logcat, I realized that this code was making it crash:
```
<com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="@dimen/fab_margin"
        app:srcCompat="@android:drawable/stat_sys_data_bluetooth"/>
```

And also, this code (I commented the above code to test each component):
```
<TextView
    android:id="@+id/tvStatus"
    android:visibility="gone"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center" />
```
I understand that I'm supposed to use MaterialTextView. However, using material should not break my old TextView's. Also, I think the reason FAB crashes is because there are references to colorAccent within it's codebase. Here's my logcat partial dump if it would help:
```
--------- beginning of crash
09-04 19:55:29.750 20113-20113/com.acme E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.acme, PID: 20113
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.acme/com.acme.MainActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2452)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
    at android.app.ActivityThread.access$900(ActivityThread.java:155)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:152)
    at android.app.ActivityThread.main(ActivityThread.java:5497)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
    at android.content.res.TypedArray.getColorStateList(TypedArray.java:482)
    at android.widget.TextView.<init>(TextView.java:753)
    at android.widget.TextView.<init>(TextView.java:674)
    at android.widget.TextView.<init>(TextView.java:670)
    at android.widget.TextView.<init>(TextView.java:666)
    at android.widget.Toolbar.setTitle(Toolbar.java:590)
    at com.android.internal.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:262)
    at com.android.internal.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:244)
    at com.android.internal.widget.ActionBarOverlayLayout.setWindowTitle(ActionBarOverlayLayout.java:669)
    at com.android.internal.policy.PhoneWindow.setTitle(PhoneWindow.java:504)
    at android.app.Activity.onTitleChanged(Activity.java:5370)
    at android.app.Activity.onPostCreate(Activity.java:1114)
    at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1210)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535) 
    at android.app.ActivityThread.access$900(ActivityThread.java:155) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:152) 
    at android.app.ActivityThread.main(ActivityThread.java:5497) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Android API version:** API 19

**Material Library version:** 1.1.0-alpha09

**Device:** OnePlus 2

**Comment by EdricChan03** [comment]
You're supposed to use the `colorSecondary` attribute instead of the `colorAccent` attribute.

For more info about color in Material Components, check out the [docs](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md).

**Comment by SaifurRahmanMohsin** [comment]
I know. I have added that as well along with colorOnSecondary and several other ones that is needed.

My bug report here is that the app crashes when I don’t put colorAccent.

**Comment by hunterstich** [comment]
Hey there. Any way you'd be able to attach a sample project which reproduces this issue?

**Comment by hunterstich** [comment]
Closing this. If this comes back up we can re-open!
