### ISSUE TITLE
[TabLayout] Widget.MaterialComponents.TabLayout crash in 1.1.0-alpha10

### ISSUE THREAD

**Issue by bembem1011** [material-components/material-components-android#619]
**Description:** For simple implementation, I use style="@style/Widget.MaterialComponents.TabLayout but application will crash in version 1.1.0-alpha01 to 1.1.0-alpha10

**Expected behavior:** Can use style="@style/Widget.MaterialComponents.TabLayout  in version 1.1.0-alpha1 to 1.1.0-alpha10

**Source code:** 
XML:
`        <com.google.android.material.tabs.TabLayout
                style="@style/Widget.MaterialComponents.TabLayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="top">

            <com.google.android.material.tabs.TabItem
                    android:layout_height="wrap_content"
                    android:layout_width="match_parent"
                    android:text="Tab 1"/>
            <com.google.android.material.tabs.TabItem
                    android:layout_height="wrap_content"
                    android:layout_width="match_parent"
                    android:text="Tab 2"/>
        </com.google.android.material.tabs.TabLayout>`

Crash Log:
`Process: com.example.myapplication, PID: 20289
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: android.view.InflateException: Binary XML file line #23: Binary XML file line #20: Error inflating class com.google.android.material.tabs.TabLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #20: Error inflating class com.google.android.material.tabs.TabLayout
     Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class com.google.android.material.tabs.TabLayout`

**Android API version:** API 28

**Material Library version:** 1.1.0-alpha01 to 1.1.0-alpha10

**Device:** real device Samsung S7, simulator Pixel 2

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).

**Comment by ldjcmu** [comment]
Thanks for testing this with the latest version. We'll take a look.

**Comment by bembem1011** [comment]
I see using Theme.MaterialComponents instead of Theme.AppCompat, the app doesn't crash any more

**Comment by wcshi** [comment]
Did you see something about theme enforcement in your stacktrace? If so, this is working as intended.

**Comment by bembem1011** [comment]
I see :d
