### ISSUE TITLE
[TabLayout]App crashes when badge is created then notifyDataSetChanged is called

### ISSUE THREAD

**Issue by elshadsm** [material-components/material-components-android#620]
**Description:** When a badge is created then notifyDataSetChanged is called at run time, the app crashes.

**Stack trace:**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.google.android.material.tabs.TabLayout$Tab.getIcon()' on a null object reference
        at com.google.android.material.tabs.TabLayout$TabView.tryUpdateBadgeAnchor(TabLayout.java:2634)
        at com.google.android.material.tabs.TabLayout$TabView.update(TabLayout.java:2516)
        at com.google.android.material.tabs.TabLayout$TabView.setTab(TabLayout.java:2446)
        at com.google.android.material.tabs.TabLayout$TabView.reset(TabLayout.java:2451)
...
```

**Expected behavior:** notifyDataSetChanged should not crash the app, whether a badge is set or not.

**Source code:** [See sample project](https://github.com/elshadsm/simple-test-application/blob/master/app/src/main/java/com/example/simple_test_application/MainActivity.kt)

**Android API version:** 29

**Material Library version:** 1.1.0-alpha10

**Device:** Pixel 3

**Comment by wcshi** [comment]
Thank you for reporting this issue, this has been fixed internally and will be part of the next release.
