### ISSUE TITLE
[Catalog App] Crash when running Demo of Shape Theming

### ISSUE THREAD

**Issue by dziry** [material-components/material-components-android#655]
**Description:** As described in the title, the demo app intituled **catalog-debug** that i've downloaded from [https://github.com/material-components/material-components-android/releases/download/1.1.0-beta01/catalog-debug.apk](url) crashes when i try to start the Demo or any additional example of Sahpe Theaming.

**Expected behavior:** N/A

**Source code:** Crash Log below
`E: FATAL EXCEPTION: main
    Process: io.material.catalog, PID: 2061
    java.lang.ClassCastException: androidx.appcompat.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at io.material.catalog.feature.DemoUtils.shouldApplyBottomInset(DemoUtils.java:129)
        at io.material.catalog.feature.DemoUtils.access$000(DemoUtils.java:33)
        at io.material.catalog.feature.DemoUtils$1.onLayoutChange(DemoUtils.java:95)
        at android.view.View.layout(View.java:22416)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1193)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:880)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:899)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1042)
        at android.view.View.layout(View.java:22398)
        at android.view.ViewGroup.layout(ViewGroup.java:6577)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3340)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2804)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1850)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)`

**Android API version:** 27

**Material Library version:** 1.1.0-beta01

**Device:** Samsung Galaxy S9+

**Comment by gabrielemariotti** [comment]
This should be fixed with #572 .
Building [from the source](https://github.com/material-components/material-components-android/blob/master/docs/catalog-app.md) works.
