### ISSUE TITLE
TextInputLayout with TextInputEditText fast input crash

### ISSUE THREAD

**Issue by asterixorobelix** [material-components/material-components-android#668]
**Description:**

I have a com.google.android.material.textfield.TextInputLayout containing a com.google.android.material.textfield.TextInputEditText.

If I type quickly into the TextInputEditText my app crashes silently (there is no output to Android Studio logcat).
However, if I type slowly into the TextInputEditText, there is no crash.

**Expected behavior:**
I would expect that typing quickly into the TextInputEditText does not cause a crash.

**Source code:** 

Fragment layout:
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

        <variable
            name="addCardFragmentViewModel"
            type="feature_cardmanagement.AddCardViewModel" />
    </data>

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginStart="@dimen/medium_margin"
        android:layout_marginEnd="@dimen/medium_margin"
        android:orientation="vertical"
        tools:context=".AddCardFragment">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/medium_margin"
            android:layout_marginBottom="@dimen/medium_margin"
            android:gravity="center_horizontal"
            android:text="@{addCardFragmentViewModel.customizationOptions.addCardFormTitleText}" />

        <com.google.android.material.textfield.TextInputLayout
            android:id="@+id/card_number_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="@{addCardFragmentViewModel.customizationOptions.cardNumberInputHint}"
            app:endIconDrawable="@{addCardFragmentViewModel.customizationOptions.cardNumberEndIconDrawable}"
            app:endIconMode="custom"
            app:startIconDrawable="@{addCardFragmentViewModel.customizationOptions.cardNumberStartIconDrawable}">

            <com.google.android.material.textfield.TextInputEditText
                android:id="@+id/card_number_input"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:imeOptions="actionNext"
                android:inputType="number"
                android:maxLength="@{addCardFragmentViewModel.cardNumberMaxLength}" />

        </com.google.android.material.textfield.TextInputLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal"
            android:orientation="horizontal">

            <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/card_expiry_layout"
                android:layout_width="@dimen/medium_text_input_width"
                android:layout_height="wrap_content"
                android:hint="@{addCardFragmentViewModel.customizationOptions.cardExpiryInputHint}"
                app:counterEnabled="true"
                app:counterMaxLength="@{addCardFragmentViewModel.cardExpiryDateMaxLength}"
                app:endIconDrawable="@{addCardFragmentViewModel.customizationOptions.cardExpiryIconDrawableRes}"
                app:endIconMode="custom"
                app:helperText="@{addCardFragmentViewModel.customizationOptions.cardExpiryHelperText}">

                <com.google.android.material.textfield.TextInputEditText
                    android:id="@+id/card_expiry_input"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:imeOptions="actionNext"
                    android:inputType="date"
                    android:maxLength="@{addCardFragmentViewModel.cardExpiryDateMaxLength}" />

            </com.google.android.material.textfield.TextInputLayout>

            <com.google.android.material.textfield.TextInputLayout
                android:id="@+id/ccv_input_layout"
                android:layout_width="@dimen/medium_text_input_width"
                android:layout_height="wrap_content"
                android:hint="@{addCardFragmentViewModel.customizationOptions.cardCCVInputHint}"
                app:counterEnabled="true"
                app:counterMaxLength="@{addCardFragmentViewModel.ccvMaxLength}"
                app:endIconDrawable="@{addCardFragmentViewModel.customizationOptions.cCVEndIconDrawableRes}"
                app:endIconMode="custom">

                <com.google.android.material.textfield.TextInputEditText
                    android:id="@+id/card_ccv_input"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:imeOptions="actionDone"
                    android:inputType="number"
                    android:maxLength="@{addCardFragmentViewModel.ccvMaxLength}" />

            </com.google.android.material.textfield.TextInputLayout>

        </LinearLayout>

        <Button
            android:id="@+id/submit_card_data_button"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/medium_margin"
            android:text="@{addCardFragmentViewModel.customizationOptions.submitButtonText}" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/medium_margin"
            android:gravity="center_horizontal"
            android:text="@{addCardFragmentViewModel.customizationOptions.faqButtonTitleText}" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_horizontal"
            android:id="@+id/faq_button"
            android:text="@{addCardFragmentViewModel.customizationOptions.faqButtonText}" />
    </LinearLayout>
</layout>
```

AddCardFragment.kt

```
import androidx.lifecycle.ViewModelProviders
import android.os.Bundle
import android.text.Editable
import android.util.Log
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import android.widget.Toast
import androidx.core.widget.addTextChangedListener
import androidx.core.widget.doAfterTextChanged
import androidx.core.widget.doOnTextChanged
import androidx.databinding.DataBindingUtil
import androidx.lifecycle.Observer
import com.entersekt.feature_cardmanagement.databinding.AddCardFragmentBinding

class AddCardFragment : Fragment() {

    companion object {
        private fun newInstance() = AddCardFragment()
        private var _customizationOptions: AddCardFragmentCustomizationOptions? = null
        fun newInstance(addCardFragmentCustomizationOptions: AddCardFragmentCustomizationOptions): AddCardFragment {
            val fragmentInstance = newInstance()
            _customizationOptions = addCardFragmentCustomizationOptions
            return fragmentInstance
        }

        const val NO_CUSTOMIZATION_SUPPLIED =
            "No customization object has been provided to the AddCardFragment"
    }

    private lateinit var viewModel: AddCardViewModel
    private lateinit var binding: AddCardFragmentBinding

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding =
            DataBindingUtil.inflate(layoutInflater, R.layout.add_card_fragment, container, false)

        binding.apply {
            cardNumberInput.doAfterTextChanged {
                it?.let {
                    viewModel.setCardNumberData(it.toString())
                }
            }
            cardCcvInput.doAfterTextChanged {
                it?.let {
                    viewModel.setCardCCVData(it.toString())
                }
            }

            cardExpiryInput.doAfterTextChanged {
                it?.let {
                    viewModel.setCardExpiryData(it.toString())
                }
            }
        }
        return binding.root
    }

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        viewModel = ViewModelProviders.of(this).get(AddCardViewModel::class.java)

        if (_customizationOptions != null) {
            viewModel.customizationOptions = _customizationOptions
        } else {
            IllegalArgumentException(NO_CUSTOMIZATION_SUPPLIED).apply {
                throw this
            }
        }

        binding.addCardFragmentViewModel = viewModel

        viewModel.apply {
            cardDataIsValid.observe(viewLifecycleOwner, Observer {
                binding.submitCardDataButton.visibility = if (it) View.VISIBLE else View.GONE
            })

            customizationOptions?.apply {
                binding.ccvInputLayout.setEndIconOnClickListener {
                    this.cCVEndIconClickListener.onClick(it)
                }

                binding.cardNumberLayout.setEndIconOnClickListener {
                    this.cardNumberEndIconClickListener.onClick(it)
                }

                binding.cardExpiryLayout.setEndIconOnClickListener {
                    this.cardExpiryEndIconClickListener.onClick(it)
                }

                binding.faqButton.setOnClickListener {
                    this.faqButtonClickListener.onClick(it)
                }

                binding.faqButton.setTextColor(resources.getColor(this.faqButtonTextColor))
            }
        }
    }
}
```

**Android API version:**
API 28

**Material Library version:** 
com.google.android.material:material:1.1.0-beta01

However, I have also tried with a number of the 1.1.0-alpha libraries and the issue is still present.

**Device:**
Android Emulator running on a Mac (Pixel 3 API 28) and on Pixel 2 XL physical device running Android 9

**Comment by asterixorobelix** [comment]
I have since discovered that this is due to a problem with converting the string to an int on the viewmodel side:

```
2019-10-10 17:01:16.381 12313-12313/cardmanagementdemoapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cardmanagementdemoapplication, PID: 12313
    java.lang.NumberFormatException: For input string: "9999999999"
        at java.lang.Integer.parseInt(Integer.java:618)
        at java.lang.Integer.parseInt(Integer.java:650)
        at feature_cardmanagement.AddCardViewModel.setCardNumberData(AddCardViewModel.kt:30)
        at feature_cardmanagement.AddCardFragment$onCreateView$$inlined$apply$lambda$1.afterTextChanged(TextView.kt:101)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:9770)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12522)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1273)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:506)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:36)
        at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:131)
        at android.widget.TextView.doKeyDown(TextView.java:7665)
        at android.widget.TextView.onKeyDown(TextView.java:7442)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2692)
        at android.view.View.dispatchKeyEvent(View.java:12450)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:428)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3360)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:115)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:133)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5037)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4905)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4618)
2019-10-10 17:01:16.382 12313-12313/cardmanagementdemoapplication E/AndroidRuntime:     at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4779)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
