### ISSUE TITLE
[BottomNavigationView] Crash when inflating Menu

### ISSUE THREAD

**Issue by KelvinEC** [material-components/material-components-android#688]
**Description:** When using app:menu attribute, app crashes. When its empty, app runs normally.

**Expected behavior:** Expects to correct inflate menu.

**Source code:** 
`
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
                                                   xmlns:app="http://schemas.android.com/apk/res-auto"
                                                   xmlns:tools="http://schemas.android.com/tools"
                                                   android:id="@+id/doors_activity_id"
                                                   android:layout_width="match_parent"
                                                   android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay"
        app:elevation="0dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/mainBackground"
            />
    </com.google.android.material.appbar.AppBarLayout>

    <FrameLayout
        android:id="@+id/frameContainer"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginBottom="8dp"
        app:layout_constraintBottom_toTopOf="@+id/bottomNavigationView"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/appBarLayout">

    </FrameLayout>

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottomNavigationView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/bottom_navigation_menu"/>

</androidx.constraintlayout.widget.ConstraintLayout>`

**Android API version:** Api 28

**Material Library version:** Material Android Library version you are using here (e.g., 1.1.0-Beta01)

**Device:** Occurs on Simulator and on Physical Device
Stacktrack:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.loopkey.indigo, PID: 6621
    java.lang.NoSuchFieldError: No static field smallLabel of type I in class Lcom/google/android/material/R$id; or its superclasses (declaration of 'com.google.android.material.R$id' appears in /data/app/br.com.loopkey.indigo-cXAvVjFvNTsdqhGXDjsjMw==/base.apk!classes2.dex)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:97)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:84)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:80)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.getNewItem(BottomNavigationMenuView.java:588)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:520)
        at com.google.android.material.bottomnavigation.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:67)
        at com.google.android.material.bottomnavigation.BottomNavigationView.inflateMenu(BottomNavigationView.java:343)
        at br.com.loopkey.indigo.presentation.view.activity.DoorActivity._setupBottomNavigation(DoorActivity.kt:78)
        at br.com.loopkey.indigo.presentation.view.activity.DoorActivity.onCreate(DoorActivity.kt:43)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

**Comment by afohrman** [comment]
We're not seeing this on our end; our catalog [uses the `app:menu` attribute]((https://github.com/material-components/material-components-android/blob/a5ec8c66431faba6c601f54071cfbcc13b961f3f/catalog/java/io/material/catalog/bottomnav/res/layout/cat_bottom_navs.xml#L49)) to set menus on its `BottomNavigationViews`.

Can you please provide the code for the menu used in the app:menu attribute?

**Comment by KelvinEC** [comment]
Of Course:

```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto">
    <item android:id="@+id/action_open_door"
          android:title="@string/open_door_tab"
          app:showAsAction="ifRoom"/>
    <item android:id="@+id/action_permissions_door"
          android:title="@string/sharing_tab"
          app:showAsAction="ifRoom"/>
    <item android:id="@+id/action_logs_door"
          android:title="@string/logs_tab"
        app:showAsAction="ifRoom"/>
</menu>
```

If run a sample project generated by AS, it's work well. If generate same view in project, the error still there.

**Comment by afohrman** [comment]
Thank you. We'll take a look and see if we can reproduce it.

**Comment by raajkumars** [comment]
Looking at the entry "No static field smallLabel of type I in class Lcom/google/android/material/R$id" in the stacktrace, it appears that the inflated layout for BottomNavigationItemView does not have a smallLabel defined. Considering that "smallLabel" is defined default layout ("design_bottom_navigation_item.xml") for BottomNavigationItemView, I am wondering if there is either resource clash or if your project somehow overrides the default layout. 

Are you seeing any build warnings to this effect in your project? Also, it would be helpful if you can please attach entire logcat output.

**Comment by raajkumars** [comment]
@KelvinEC We could not reproduce this issue at our end. You mentioned that this issue occurs only in your project and that this issue does not occur in sample project generated by Android Studio. Based on this and comment I made earlier, I believe that this is not a defect in the material component library.

**Comment by KelvinEC** [comment]
Sorry about the delay. 
I'm still facing this issue. 

There's no resource at my application with this name. I tried to run a search under all modules and only finds the "design_bottom_navigation_item.xml" definition.
There's anything that i can do to bring more information to this case?

That's the full log output at app run until the crash occurs.

`11/28 12:37:33: Launching 'app' on Xiaomi MI 8 Lite.
$ adb shell am start -n "br.com.loopkey.indigo/br.com.loopkey.indigo.presentation.view.activity.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 12538 on device 'xiaomi-mi_8_lite-547dd4ba'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/.loopkey.indig: The ClassLoaderContext is a special shared library.
I/.loopkey.indig: The ClassLoaderContext is a special shared library.
I/.loopkey.indig: The ClassLoaderContext is a special shared library.
W/.loopkey.indig: miui_dex2oat: oat file of /data/app/br.com.loopkey.indigo-rfExVDFR96g-pGA3VTVW5g==/base.apk is not exists
I/Perf: Connecting to perf service.
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
V/FA: Registered activity lifecycle callback
I/FirebaseInitProvider: FirebaseApp initialization successful
I/CrashlyticsInitProvider: CrashlyticsInitProvider skipping initialization
W/com.facebook.UserSettingsManager: Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
W/com.facebook.UserSettingsManager: You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/FA: Collection enabled
V/FA: App package, google app id: br.com.loopkey.indigo, 1:402315893272:android:38a6b1e47a592734
I/FA: App measurement is starting up, version: 19000
    To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
    To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app br.com.loopkey.indigo
D/FA: Debug-level message logging enabled
V/FA: Connecting to remote service
W/.loopkey.indig: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
V/FA: Connection attempt already in progress
W/.loopkey.indig: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
    Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
W/.loopkey.indig: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
V/FA: onActivityCreated
W/.loopkey.indig: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/.loopkey.indig: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
V/FA: Activity resumed, time: 131325885
I/Timeline: Timeline: Activity_launch_request time:79448234 intent:Intent { flg=0x10008000 cmp=br.com.loopkey.indigo/.presentation.view.activity.DoorsActivity }
I/FA: Tag Manager is not found and thus will not be used
D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_screen_class(_sc)=SplashActivity, ga_screen_id(_si)=2130643888325722180}]
W/Looper: Slow Looper: Activity br.com.loopkey.indigo/.presentation.view.activity.SplashActivity is 1113ms late (wall=178ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 2 msg, msg 2 took 1111ms (late=27ms h=android.app.ActivityThread$H w=110)
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@9c349f0
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 65
    Connection attempt already in progress
V/FA: Activity paused, time: 131325919
V/FA: onActivityCreated
W/AnalyticsUserIDStore: initStore should have been called before calling setUserID
W/.loopkey.indig: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
W/.loopkey.indig: Accessing hidden method Landroid/text/SpannableStringInternal;->length()I (light greylist, linking)
D/BluetoothAdapter: isLeEnabled(): ON
D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=7 mScannerId=0
W/.loopkey.indig: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (light greylist, reflection)
    Accessing hidden method Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z (light greylist, reflection)
    Accessing hidden method Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z (light greylist, reflection)
W/.loopkey.indig: Accessing hidden method Landroid/graphics/FontFamily;->freeze()Z (light greylist, reflection)
    Accessing hidden method Landroid/graphics/FontFamily;->abortCreation()V (light greylist, reflection)
    Accessing hidden method Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface; (light greylist, reflection)
W/Activity: Slow Operation: Activity br.com.loopkey.indigo/.presentation.view.activity.DoorsActivity onStart took 309ms
V/FA: Activity resumed, time: 131326342
D/FA: Logging event (FE): screen_view(_vs), Bundle[{ga_event_origin(_o)=auto, ga_previous_class(_pc)=SplashActivity, ga_previous_id(_pi)=2130643888325722180, ga_screen_class(_sc)=DoorsActivity, ga_screen_id(_si)=2130643888325722181}]
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
D/SharingType: admin
I/chatty: uid=10215(br.com.loopkey.indigo) identical 1 line
D/SharingType: admin
D/SharingType: owner
W/.loopkey.indig: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 7
W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
W/.loopkey.indig: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
W/.loopkey.indig: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
I/Adreno: QUALCOMM build                   : ce8a911, I385ac5a262
    Build Date                       : 03/28/19
    OpenGL ES Shader Compiler Version: EV031.25.03.01
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.2.R1.09.00.00.442.052
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
    Build Config                     : S L 6.0.7 AArch64
I/Adreno: PFP: 0x005ff112, ME: 0x005ff066
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
W/.loopkey.indig: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
I/.loopkey.indig: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
D/SharingType: admin
I/chatty: uid=10215(br.com.loopkey.indigo) RxIoScheduler-2 identical 1 line
D/SharingType: admin
D/SharingType: owner
W/.loopkey.indig: Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (light greylist, reflection)
W/Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
D/SharingType: admin
I/chatty: uid=10215(br.com.loopkey.indigo) identical 1 line
D/SharingType: admin
D/SharingType: owner
D/SharingType: admin
I/chatty: uid=10215(br.com.loopkey.indigo) RxIoScheduler-3 identical 1 line
D/SharingType: admin
D/SharingType: owner
I/Timeline: Timeline: Activity_launch_request time:79453830 intent:Intent { cmp=br.com.loopkey.indigo/.presentation.view.activity.DoorActivity (has extras) }
V/FA: Recording user engagement, ms: 5164
V/FA: Activity paused, time: 131331506
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@64dc758
D/FA: Logging event (FE): user_engagement(_e), Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=5164, ga_screen_class(_sc)=DoorsActivity, ga_screen_id(_si)=2130643888325722181}]
V/FA: onActivityCreated
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.loopkey.indigo, PID: 12538
    java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.loopkey.indigo/br.com.loopkey.indigo.presentation.view.activity.DoorActivity}: android.view.InflateException: Binary XML file line #39: Binary XML file line #39: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.view.InflateException: Binary XML file line #39: Binary XML file line #39: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
     Caused by: android.view.InflateException: Binary XML file line #39: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at br.com.loopkey.indigo.presentation.view.activity.DoorActivity.onCreate(DoorActivity.kt:34)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NoSuchFieldError: No static field smallLabel of type I in class Lcom/google/android/material/R$id; or its superclasses (declaration of 'com.google.android.material.R$id' appears in /data/app/br.com.loopkey.indigo-rfExVDFR96g-pGA3VTVW5g==/base.apk!classes2.dex)
E/AndroidRuntime:     at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:97)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:84)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:80)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.getNewItem(BottomNavigationMenuView.java:589)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:521)
        at com.google.android.material.bottomnavigation.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:67)
        at com.google.android.material.bottomnavigation.BottomNavigationView.inflateMenu(BottomNavigationView.java:344)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:226)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:133)
        	... 28 more
I/Process: Sending signal. PID: 12538 SIG: 9
Process 12538 terminated.`

**Comment by EarlyWild** [comment]
I also am encountering this issue, but it only happens when Proguard or R8 is enabled.

**Comment by rahulgsa** [comment]
I also am encountering this issue, but it only happens when Proguard or R8 is enabled.

@EarlyWild did you get any solution for it?

**Comment by oqqA** [comment]
My guess is that this is due to the "AndroidStudio" cache. Something happens when a file is cloned, and after changing it, "AndroidStudio" refers to the original file.

**Comment by ahmedeltaher** [comment]
@afohrman @raajkumars 
I also face this when I enable R8.

**Comment by lioriluz** [comment]
Same here

**Comment by Ravinnpawar** [comment]
Same here 
Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195) 
        at news.marathi.myapplication.MainActivity.onCreate(MainActivity.kt:38) 
        at android.app.Activity.performCreate(Activity.java:6440) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2562) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:165) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:179) 
        at android.app.ActivityThread.main(ActivityThread.java:5672) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:683)

**Comment by rlmax** [comment]
same here

**Comment by Duna** [comment]
Same here     
```
<com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottom_navigation"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:background="?attr/colorPrimaryDark"
        app:itemBackground="@color/bottom_nav_bg_color"
        app:itemIconTint="@drawable/bottom_nav_color"
        app:itemTextColor="@drawable/bottom_nav_color"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/bottom_navigation_menu" />
```

**Comment by Toubap** [comment]
Same here only happened in crashlytics in samsung devices

**Comment by raajkumars** [comment]
Have you tried to exclude material android library from proguard? For ex: 

```
dontwarn com.google.android.material.**
-keep class com.google.android.material.** { *; }
```

**Comment by darkengine** [comment]
Happened in Samsung device too - S10. It works again when I comment out items and make it total 5 items.

**Comment by onlycyndi** [comment]
> Have you tried to exclude material android library from proguard? For ex:
> 
> ```
> - dontwarn com.google.android.material.**
> -keep class com.google.android.material.** { *; }
> ```

thanks, it's work for me

**Comment by aleksnamaniuk** [comment]
same here
