### ISSUE TITLE
BottomNavigationView - can't use getOrCreateBadge with AppCompat theme

### ISSUE THREAD

**Issue by boyfox** [material-components/material-components-android#730]
Why we can't use BottomNavigationView widget counter badge functionality with AppCompat theme?

![image](https://user-images.githubusercontent.com/3168694/68024144-1311b900-fccb-11e9-8128-24028172d4de.png)

App build.gradle:

![image](https://user-images.githubusercontent.com/3168694/68024190-2de42d80-fccb-11e9-8ce9-cde6a413fdef.png)

And crash error when trying call to method **getOrCreateBadge**:

```
  --------- beginning of crash
2019-11-01 17:04:08.199 27162-27162/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 27162
    java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
        at com.google.android.material.badge.BadgeDrawable.<init>(BadgeDrawable.java:379)
        at com.google.android.material.badge.BadgeDrawable.createFromAttributes(BadgeDrawable.java:305)
        at com.google.android.material.badge.BadgeDrawable.create(BadgeDrawable.java:273)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.getOrCreateBadge(BottomNavigationMenuView.java:641)
        at com.google.android.material.bottomnavigation.BottomNavigationView.getOrCreateBadge(BottomNavigationView.java:673)
        at com.example.MainActivity$onCreate$1.onPropertyChanged(MainActivity.kt:75)
        at androidx.databinding.PropertyChangeRegistry$1.onNotifyCallback(PropertyChangeRegistry.java:30)
        at androidx.databinding.PropertyChangeRegistry$1.onNotifyCallback(PropertyChangeRegistry.java:26)
        at androidx.databinding.CallbackRegistry.notifyCallbacks(CallbackRegistry.java:201)
        at androidx.databinding.CallbackRegistry.notifyFirst64(CallbackRegistry.java:122)
        at androidx.databinding.CallbackRegistry.notifyRemainder(CallbackRegistry.java:169)
        at androidx.databinding.CallbackRegistry.notifyRecurse(CallbackRegistry.java:145)
        at androidx.databinding.CallbackRegistry.notifyCallbacks(CallbackRegistry.java:91)
        at androidx.databinding.BaseObservable.notifyChange(BaseObservable.java:60)
        at androidx.databinding.ObservableInt.set(ObservableInt.java:89)
        at com.example.viewmodels.AppModel.addToBasket(AppModel.java:120)
        at com.example.viewmodels.AppModel.addToBasket(AppModel.java:125)
        at com.example.fragments.products.ShowProductDetailsBottomSheet$initListeners$$inlined$let$lambda$4.onClick(ShowProductDetailsBottomSheet.kt:386)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by wcshi** [comment]
Hi @boyfox as the stacktrace stated, you will need to set a MaterialComponents theme (at least on the bottom navigation component) in order to use the badge feature because the badge is relying on theme attributes that are guaranteed to be defined in a material theme.

**Comment by boyfox** [comment]
@wcshi I must support older versions from android 5, how I can use material them for older versions if i don't use AppCompat? why you close bug if it is not solved?

**Comment by leticiarossi** [comment]
Hi @boyfox the Material Components library offers support for [APIs 14 (Android 4.0) and above](https://github.com/material-components/material-components-android/blob/master/lib/AndroidManifest.xml#L19). In order to use specific material components such as the badge feature, you will need to use a material theme as explained above.
More info about transitioning to a MaterialComponents theme can be found in our [Getting Started](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md) guide.

**Comment by summerEnd** [comment]
<com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottomNavigation"
        app:theme="@style/Theme.MaterialComponents"
        style="@style/AppWidget.BottomNavigation"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:menu="@menu/bottom_tab_menu" />
@boyfox

**Comment by Jitendran** [comment]
> <com.google.android.material.bottomnavigation.BottomNavigationView
> android:id="@+id/bottomNavigation"
> app:theme="@style/Theme.MaterialComponents"
> style="@style/AppWidget.BottomNavigation"
> app:layout_constraintBottom_toBottomOf="parent"
> app:layout_constraintStart_toStartOf="parent"
> app:menu="@menu/bottom_tab_menu" />
> @boyfox

My problem has resolved using app:theme="@style/Theme.MaterialComponents".
