### ISSUE TITLE
[BottomNavigationView] StrictMode policy violation: NonSdkApiUsedViolation

### ISSUE THREAD

**Issue by niqo01** [material-components/material-components-android#792]
**Description:** 
When enabling strict mode with `.detectNonSdkApiUsage()`, the following issue is reported:

```
D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate;
        at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredField(Native Method)
        at androidx.core.view.ViewCompat.getAccessibilityDelegateInternal(ViewCompat.java:913)
        at androidx.core.view.ViewCompat.setAccessibilityDelegate(ViewCompat.java:687)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:127)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:84)
        at com.google.android.material.bottomnavigation.BottomNavigationItemView.<init>(BottomNavigationItemView.java:80)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.getNewItem(BottomNavigationMenuView.java:589)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:521)
        at com.google.android.material.bottomnavigation.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:67)
        at com.google.android.material.bottomnavigation.BottomNavigationView.inflateMenu(BottomNavigationView.java:344)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:226)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:133)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.nicolasmilliard.socialcats.base.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:44)
        at com.nicolasmilliard.socialcats.base.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:38)
        at com.nicolasmilliard.socialcats.ui.MainActivity.onCreate(MainActivity.kt:44)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-11-26 12:11:06.670 16627-16627/? W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
```

**Expected behavior:** 
No Android Strict mode violation

**Source code:** 
Add the material BottomNavigationView to a project and enable StrictMode:
```
            val builder = VmPolicy.Builder()
                .detectAll()
                .penaltyLog()
                .penaltyDeath()
            StrictMode.setVmPolicy(builder.build())
```

**Android API version:** 
29

**Material Library version:** 
com.google.android.material:material:1.1.0-beta02

**Device:** 
Pixel 2 XL

**Comment by wcshi** [comment]
IIUC, the violation is triggered by a call to ViewCompat#setAccessibilityDelegate?

**Comment by wcshi** [comment]
We are waiting till androidx.core 1.20 stable is released, in the main time, could you try including androidx.core 1.20rc01 in your app?
