### ISSUE TITLE
[Slider] Crashes when initializing the view

### ISSUE THREAD

**Issue by Lennoard** [material-components/material-components-android#793]
**Description:** Crashing when (re?) initializing the view.

```
**java.lang.RuntimeException:** 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2713)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2774)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1511)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6300)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:887)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:777)
  at de.robv.android.xposed.XposedBridge.main (XposedBridge.java:107)
**Caused by: java.lang.NullPointerException:** 
  at android.os.Parcel.readFloatArray (Parcel.java:1048)
  **at com.google.android.material.slider.Slider$SliderState.<init> (Slider.java)**
  **at com.google.android.material.slider.Slider$SliderState.<init> (Slider.java)**
  **at com.google.android.material.slider.Slider$SliderState$1.createFromParcel (Slider.java)**
  **at com.google.android.material.slider.Slider$SliderState$1.createFromParcel (Slider.java)**
  at android.os.Parcel.readParcelable (Parcel.java:2471)
  at android.os.Parcel.readValue (Parcel.java:2365)
  at android.os.Parcel.readSparseArrayInternal (Parcel.java:2813)
  at android.os.Parcel.readSparseArray (Parcel.java:2068)
  at android.os.Parcel.readValue (Parcel.java:2422)
  at android.os.Parcel.readArrayMapInternal (Parcel.java:2732)
  at android.os.BaseBundle.unparcel (BaseBundle.java:269)
  at android.os.Bundle.getSparseParcelableArray (Bundle.java:934)
  at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:64)
  at androidx.fragment.app.FragmentManagerImpl.dispatchCreate (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.allocBackStackIndex (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.beginTransaction (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.completeExecute (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.enqueueAction (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.findFragmentByTag (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.getFragment (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.makeOpenCloseAnimation (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.popBackStack (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.putFragment (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.saveFragmentInstanceState (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.setBackStackIndex (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.allocBackStackIndex (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.beginTransaction (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.completeExecute (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.enqueueAction (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.findFragmentByTag (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.getFragment (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.makeOpenCloseAnimation (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.popBackStack (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.putFragment (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.saveFragmentInstanceState (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.setBackStackIndex (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentManagerImpl.dispatchCreate (FragmentManagerImpl.java)
  at androidx.fragment.app.FragmentController.dispatchCreate (FragmentController.java:9)
  at androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:9)
  at androidx.appcompat.app.AppCompatActivity.onCreate (AppCompatActivity.java)
  [**at com.packagename.activity.MainActivity.onCreate (MainActivity.java)**]
  at android.app.Activity.performCreate (Activity.java:6708)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1118)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2666)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2774)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1511)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6300)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:887)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:777)
```

**Android API version:** 23..29

**Material Library version:** 1.2.0-alpha01/1.2.0-alpha02

**Device:** vince, athene, osprey_udstv, harpia, nicklaus_fn, etc. Mostly Motorola.

**Comment by RomanTsarou** [comment]
A have this error aftrer restore a activity with Material Library version: 1.2.0-alpha05

`
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
       at android.os.Parcel.readListInternal(Parcel.java:2795)
       at android.os.Parcel.readList(Parcel.java:1836)
       at com.google.android.material.slider.Slider$SliderState.<init>(Slider.java:2085)
       at com.google.android.material.slider.Slider$SliderState.<init>(Slider.java:2053)
       at com.google.android.material.slider.Slider$SliderState$1.createFromParcel(Slider.java:2067)
       at com.google.android.material.slider.Slider$SliderState$1.createFromParcel(Slider.java:2062)
       at android.os.Parcel.readParcelable(Parcel.java:2471)
       at android.os.Parcel.readValue(Parcel.java:2365)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
       at android.os.Parcel.readSparseArray(Parcel.java:2068)
       at android.os.Parcel.readValue(Parcel.java:2422)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
       at androidx.fragment.app.FragmentStateManager.restoreState(FragmentStateManager.java:226)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2459)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
       at by.giveaway.activity.GeneralFragmentActivity.onCreate(GeneralFragmentActivity.java:17)
       at android.app.Activity.performCreate(Activity.java:6720)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`
