### ISSUE TITLE
[BaseTransientBottomBar] 1.1.0-rc01 causes View.invalidate(boolean) NullPointerException

### ISSUE THREAD

**Issue by Naitbit** [material-components/material-components-android#917]
**Description:** 
After updating from Material 1.0.0 to 1.1.0-rc01 I saw multiple reports of crashes with BaseTransientBottomBar (and no app specific code in stacktrace).
Stacktraces look like:
Huawei Android 7
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.invalidate(boolean)' on a null object reference
       at android.view.View.setFlags + 11550(View.java:11550)
       at android.view.View.setVisibility + 8046(View.java:8046)
       at com.google.android.material.snackbar.BaseTransientBottomBar$9.run + 849(BaseTransientBottomBar.java:849)
       at android.os.Handler.handleCallback + 761(Handler.java:761)
       at android.os.Handler.dispatchMessage + 98(Handler.java:98)
       at android.os.Looper.loop + 156(Looper.java:156)
       at android.app.ActivityThread.main + 6617(ActivityThread.java:6617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 942(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main + 832(ZygoteInit.java:832)
```
Samsung Android 9
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.invalidate(boolean)' on a null object reference
       at android.view.View.setFlags + 15721(View.java:15721)
       at android.view.View.setVisibility + 10789(View.java:10789)
       at com.google.android.material.snackbar.BaseTransientBottomBar$9.run + 849(BaseTransientBottomBar.java:849)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7094(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 975(ZygoteInit.java:975)
```
Xiaomi Android 9
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.invalidate(boolean)' on a null object reference
       at android.view.View.setFlags + 14186(View.java:14186)
       at android.view.View.setVisibility + 10007(View.java:10007)
       at com.google.android.material.snackbar.BaseTransientBottomBar$9.run + 849(BaseTransientBottomBar.java:849)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 201(Looper.java:201)
       at android.app.ActivityThread.main + 6823(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 547(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main + 873(ZygoteInit.java:873)
```
LGE Android 9
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.invalidate(boolean)' on a null object reference
       at android.view.View.setFlags + 14222(View.java:14222)
       at android.view.View.setVisibility + 10027(View.java:10027)
       at com.google.android.material.snackbar.BaseTransientBottomBar$9.run + 849(BaseTransientBottomBar.java:849)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 193(Looper.java:193)
       at android.app.ActivityThread.main + 6854(ActivityThread.java:6854)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 860(ZygoteInit.java:860)
```
(if needed I can find few more stacktrace, but they seem to differ just by line numbers)

**Expected behavior:** BaseTransientBottomBar should not cause crashes/NPE

Steps to reproduce are unfortunately unknown, it seems to be relatively rare.
The issue did not happen in 1.0.0

**Material Library version:** 1.1.0-rc01

**Device:** Multiple Devices/Android OS versions affected.

**Comment by Naitbit** [comment]
Thanks for quick release. 
I got report of 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.invalidate(boolean)' on a null object reference
       at android.view.View.setFlags + 13449(View.java:13449)
       at android.view.View.setVisibility + 9417(View.java:9417)
       at com.google.android.material.snackbar.BaseTransientBottomBar$9.run + 849(BaseTransientBottomBar.java:849)
       at android.os.Handler.handleCallback + 808(Handler.java:808)
       at android.os.Handler.dispatchMessage + 101(Handler.java:101)
       at android.os.Looper.loop + 166(Looper.java:166)
       at android.app.ActivityThread.main + 7425(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run + 245(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main + 921(ZygoteInit.java:921)
``` 
occurring with **1.1.0-rc02** so it seems like the issue was not resolved fully yet. 
I'll follow up later whether the rate of occurrences was impacted a lot (not enough data yet to tell).

**Comment by Naitbit** [comment]
For now it impacted 20 users out of ~9000 . So the issue in *1.1.0-rc02* was not just one off case (occurrence rate seems to be lower then in *1.1.0-rc01* though due to low user count it may not be statistically significant).

**Comment by dsn5ft** [comment]
@Naitbit do you have any information about the scenario that causes the crash? Do you know if any activities are being created or destroyed while the Snackbar is being shown?

It looks like the NPE is internal to `View`.

**Comment by Naitbit** [comment]
@dsn5ft Sorry, I still don't have steps to reproduce, but with more reports it seems that what happens is:
Screen(fragment) is opened
Snackbar is called (likely twice, v.shortly after the screen is opened, probably via `Snackbar.make(view, message, Snackbar.LENGTH_SHORT).show()`)
There was **no** device rotation in the meantime. Snackbar was called from main thread and activity was likely resumed , as it is was called from LiveData.observe.

That said I still did fail to reproduce it on one of my devices.

**Comment by Naitbit** [comment]
Further information:
I managed to artificially reproduce it.


Not sure if the view hierarchy is important for this bug, but I'm writing it down just in case:

The hierarchy was _Activity>CoordinatorLayout as content_>Fragment*1*
that after navigation tap switched to
_Activity>CoordinatorLayout as content_>Fragment*2* with ViewPager that displayed > Fragment*3* with viewPager > that displayed Fragment*4*
In my artificial way *Fragment4* did call Snackbar immediately in onResume, then 2 frames later  it did call Snackbar again which caused a crash. Snackbar used CoordinatorLayout from Activity as an container.


After throttling the calls to Snackbar I was no longer able to reproduce the issue. (worth noting that even with this convoluted setup it was reproducible on Huawei, but not reproducible on emulator nor Pixel - it is known to happen also at least on Samsung, LG, Xiamoi, Motorola Rockhip so maybe it requires different timing). 

There seem to be no good reason to call Snackbar twice in such a short period though, so I'll change this in our app (and let you know if that was sufficient). (There is probably also no good enough reason for such a deep fragment hierarchy :D )

**Comment by Naitbit** [comment]
I can confirm that stopping app from displaying snackbar twice on consecutive frames did stop crashes. 
(calling snackbar twice in a row on the same frame AFAIK did not crash).
We did fix the hierarchy later too, but that not displaying snackbar twice was sufficient to fix the issue.

**Comment by Naitbit** [comment]
(so I'm not sure if this needs fixing after all, but  maybe there should be note somewhere in documentation to not spam Snackbar)

**Comment by wcshi** [comment]
The snackbarManager is supposed to handle multiple show() calls on the same snackbar.
https://github.com/material-components/material-components-android/blob/7ef37a05dd75a1c2bf2f138b2ce29ad0092a625d/lib/java/com/google/android/material/snackbar/SnackbarManager.java#L76-L84

**Comment by vonox7** [comment]
For everyone experiencing the same issue: https://github.com/material-components/material-components-android/commit/ebd322314719fb65bdfa7299274ed4662a29d88c fixed almost all cases of NPEs in our project. But the issue is still not 100% resolved on Android 8 and Android 9.
It seems like https://android.googlesource.com/platform/frameworks/base/+/254c25f347a321b687c3b83c943640d565f7578d%5E%21/core/java/android/view/View.java fixed the NPE in the Android source code - so at least with Android 10 the issue should be 100% resolved.

**Comment by vonox7** [comment]
Fyi: Some issues are still present, see https://github.com/material-components/material-components-android/pull/1938. E.g. 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.invalidate(boolean)' on a null object reference
       at android.view.View.setFlags(View.java:15710)
       at android.view.View.setVisibility(View.java:10777)
       at com.google.android.material.snackbar.BaseTransientBottomBar$10.run(BaseTransientBottomBar.java:896)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

As a possible workaround you might use ` implementation 'com.github.material-components:material-components-android:d9fa78f176'` as jitpack-dependency, in that version the NPEs are resolved.
@wcshi since the issue is only partially resolved, you might open this issue again.

**Comment by tomerpetel** [comment]
Any news here? I'm seeing it on  'com.google.android.material:material:1.2.1' as well

**Comment by carstenhag** [comment]
@tomerpetel it's fixed at https://github.com/material-components/material-components-android/releases/tag/1.4.0-alpha01 :)

**Comment by tomerpetel** [comment]
@carstenhag many thanks :) I'll give it a try

**Comment by tomerpetel** [comment]
@carstenhag this version is working on Android 10 & 11 but I'm still seeing issues on earlier versions (Android 8 & 9) - anyway to workaround that? Do you know on which version it started? Maybe it'll be best to revert back to it...

**Comment by carstenhag** [comment]
Unfortunately I'm not a project member or maintainer and I haven't looked into it. Perhaps someone else knows more.

**Comment by BYogatama** [comment]
Having same issue on Android 5, with `com.google.android.material:material:1.4.0`
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.invalidate(boolean)' on a null object reference
        at android.view.View.setFlags(View.java:9682)
        at android.view.View.setVisibility(View.java:6663)
        at android.widget.FrameLayout.setVisibility(FrameLayout.java:208)
        at com.google.android.material.snackbar.BaseTransientBottomBar$10.run(BaseTransientBottomBar.java:896)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by drchen** [comment]
I kind feel this looks like an old framework issue and is not really something we can "fixed".

Does the crash happen frequently? I'm pretty reluctant to add a try-catch so the crash will be hidden. 
If it's just an edge case on old APIs, I'll tend to close the issue as won't fix.

**Comment by HolimaX** [comment]
Still crashing with NPE.
Code:
```
                final View sbw = snackBar[0].getView();
                TextView textView = sbw.findViewById(com.google.android.material.R.id.snackbar_action);
```
Log (obfuscated by _<>_):
```
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View com.google.android.material.snackbar.BaseTransientBottomBar.E()' on a null object reference
        at com.<>.MainActivity.onCreate(:878)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by drchen** [comment]
That's absolutely a different crash and not related to the Material library.

You probably need to check why your snackBar[0] is null.

**Comment by drchen** [comment]
I think the earliest version that includes the fix is 1.6.0-alpha02. : )

**Comment by Velja85** [comment]
@drchen Thx for the update, really appreciate it! We updated the material version to the most recent one today.

**Comment by ikegps-simon** [comment]
Issue appears to still be persistent even on 1.6.1
![image](https://user-images.githubusercontent.com/103982645/193711435-1a43d26f-50d1-4d61-94e4-4902c6bfb77a.png)
Whats interesting is that my error here has a few more stack trace lines that some of the others posted in this thread dont have.
Do you think this is because the device is running Android 5.1 as per this comment?

> I kind feel this looks like an old framework issue and is not really something we can "fixed".
> 
> Does the crash happen frequently? I'm pretty reluctant to add a try-catch so the crash will be hidden. If it's just an edge case on old APIs, I'll tend to close the issue as won't fix.

As for the question, I've seen it show up once in that 5.1 device ~1 week after launch. The user in question had the app open for just over an hour, then had the app background for about 4 hours before using it again for about 10 min before the crash.
Just in case that info helps :)

Thanks

**Comment by drchen** [comment]
Hi thanks for the info and sorry for the confusion - 

The associated PR that closed the issue is (partially, I believe) fixing the similar NPE in a different place.
The original NPE (the NPE your app runs into) is unfortunately a framework bug on the old APIs and I don't think we have a way to workaround or avoid it. 

(We already guard the visibility setter with nullity check but it doesn't fully eliminate the NPE.)

**Comment by ikegps-simon** [comment]
OK cool thanks for the update :)
