### ISSUE TITLE
[MaterialDatePicker] Crash - Scroll to Min Year of CalendarConstraint

### ISSUE THREAD

**Issue by zkovar** [material-components/material-components-android#980]
**Description:**

I have a calendar set up that requires a user to enter their DOB

```
        val datePicker = MaterialDatePicker.Builder.datePicker()
            .setTitleText(getString(R.string.birthdate))
            .setCalendarConstraints(
                CalendarConstraints.Builder()
                    .setStart(start)
                    .setEnd(end)
                    .setOpenAt(currentDate)
                    .build()
            )
            .setSelection(currentDate)
            .build()
```

The constraints are in reference to **TODAY** and require a user to be within 18 and 100 years of age.

```
        val calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"))
        val currentYear = calendar.get(Calendar.YEAR)

        calendar.set(Calendar.YEAR, currentYear - 100)
        val start = calendar.timeInMillis

        calendar.set(Calendar.YEAR, currentYear - 18)
        val end = calendar.timeInMillis
```

If the **current** selection of the calendar is set to `January 1st, 1975` which is within the valid range, and the user changes the active `YEAR` to 1920 — the app crashes with the following stack trace.

The calendar is attempting to scroll to `JANUARY OF 1920` which is an invalid target position (-1) as the minimum date is in `FEBRUARY of 1920`. This scenario works just fine when scrolling to the `MAXIMUM` end

**Stack Trace:**

```
java.lang.IllegalArgumentException: Invalid target position
        at androidx.recyclerview.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:11807)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:8470)
        at com.google.android.material.datepicker.SmoothCalendarLayoutManager.smoothScrollToPosition(SmoothCalendarLayoutManager.java:49)
        at androidx.recyclerview.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1790)
        at com.google.android.material.datepicker.MaterialCalendar$10.run(MaterialCalendar.java:453)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Expected behavior:**
The calendar should scroll to `February of 1920` [i.e. the minimum allowed date within that year]

**Source code:**
See above

**Android API version:** Android API version here
28

**Material Library version:**
1.1.0

**Device:**
Pixel

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/material-components/material-components-android/releases) of the library.
Confirmed on latest stable release 👍 

We also happily accept [pull requests](https://github.com/material-components/material-components-android/pulls).
@pekingme Please let me know if you'd like some support on this. Since this scenario works just fine scrolling to the maximum constraint, I anticipate the fix should be a quick one.

**Comment by zkovar** [comment]
Upon further investigation, the **MAXIMUM** case works as calling `scrollToPosition(max + 5)` will simply `scrollToPosition(max)` without error.

**Comment by klblk** [comment]
reproduced to demo app: 
https://drive.google.com/file/d/1KQkQ1uzqQ6SfaXwDrLoInJaskfA5INbc/view?usp=sharing
